### ISSUE TITLE
FairRoot uses wrong ROOT during compilation

### ISSUE THREAD

**Issue by knopers8** [alisw/alidist#1015]
I have 'standalone' ROOT installed on the system. 

During aliBuilding, FairROOT seems to be using root-config in` /usr/bin/root-config` instead of the one in the ROOT compiled with aliBuild ( `/home/pkonopka/alice/sw/slc7_x86-64/ROOT/v6-12-04-1/bin/root-config` in my case ), which fails compilation. E.g.
```
fatal error: 'TMCtls.h' file not found
#include "TMCtls.h"                     // for multi-threading
```

Doing `mv /usr/bin/root-config /usr/bin/.root-config` helps.

**Comment by dberzano** [comment]
Hi @knopers8, this is a FairRoot issue and it should be reported to them. Probably, even if our ROOT has priority in PATH, they will consider a system-installed ROOT first. You should entirely remove your system ROOT installation in my opinion, for a full fix.
