### ISSUE TITLE
xrootd 3.3.6 :: openssl error as it is picked from system

### ISSUE THREAD

**Issue by adriansev** [alisw/alidist#1018]
Hi! It seems that on fedora 26 openssl is picked from system (version 1.1.0) which gives errors like : 
/home.hdd/physics-tools/ALIBUILD/sw/SOURCES/XRootD/v3.3.6-alice2/v3.3.6-alice2/src/XrdCrypto/XrdCryptosslAux.cc:447:64: error: invalid use of incomplete type ‘EVP_PKEY {aka struct evp_pkey_st}’
                      if (PEM_read_bio_RSAPrivateKey(bkey,&(evpp->pkey.rsa),0,0)) {

for all usage of xrootd 3.3.6 a local old openssl should be built

**Comment by dberzano** [comment]
Hi Adrian, on Fedora 26 and 27 you need to install an older version of OpenSSL. We are not building/enabling our own (which is obsolete and serves some production purposes only).

```
dnf install compat-openssl10-devel compat-openssl10 --allowerasing
```

This is a workaround on your system.

Note that it is extremely tricky to provide support for Fedora systems given their, er, "bleeding-edge" update policy (and at the moment, for other reasons, O2 does not build correctly on Fedora 27).

**Comment by adriansev** [comment]
Thanks for info! i imagined that i need the compat packages but i thought that usage of alidist packages would be the correct one .. Thanks!
