### ISSUE TITLE
Tests for ThePEG

### ISSUE THREAD

**Issue by dberzano** [alisw/alidist#107]
We currently have the `thepeg-test.sh` recipe containing a simple generation done with ThePEG, based on the examples @qgp provided me with some time ago.

We would like to extend this test by adding some plots we can check to understand that everything is correct, and ultimately merge it with the `aliroot-tests.sh` recipe, so that they will become visible on [ali-ci.cern.ch](https://ali-ci.cern.ch/).

If you look at `aliroot-tests.sh` you'll notice that only `.root`, `.sql` and `.log` files are copied to the destination.

@qgp, could you please take care of it? We think this will be useful for everybody :-)

**Comment by qgp** [comment]
@dberzano: Will do, sounds good to me. And I anyway have to test the new version of ThePEG, so it's a good moment. I'll have to see in what format we can get the output (e.g. if we use Rivet for testing).

**Comment by dberzano** [comment]
Any chance you use ROOT for doing the plots? ROOT is available in the `aliroot-tests.sh` environment.

**Note:** as you have noticed already, issue your PRs to `IB/v5-06/prod`, as `master` has been deleted.

**Comment by qgp** [comment]
Point taken, I'll try with ROOT then, i.e. I would need at least AliRoot to have the HepMC parsing, and probably AliPhysics to have some task to test. I'll have a look how much I can strip it down - while retaining the usefulness of the test, of course.

**Comment by ktf** [comment]
Happy New Year!
Any update on this? If not I will close it and you can reopen it when you have time to work on it.

**Comment by qgp** [comment]
Happy New Year!
If I am realistic, I won't get this done in January. So, let's close it now and I'll reopen it later.
