### ISSUE TITLE
cmake check for version 3.5.? fails with 3.10

### ISSUE THREAD

**Issue by davidrohr** [alisw/alidist#1089]
The cmake recipe fails to detect the correct version of system cmake, treating 3.10 like 3.1, and thus as too old.

**Comment by ktf** [comment]
@brinick can you please look into this? Thanks.

**Comment by ktf** [comment]
Isn't this fixed by https://github.com/alisw/alidist/issues/1089 ? Or you mean for AliRoot?

**Comment by davidrohr** [comment]
@ktf: The problem is this line in cmake.sh:
which cmake && case `cmake --version | sed -e 's/.* //' | cut -d. -f1,2,3 | head -n1` in [0-2]*|3.[0-4].*|3.5.[0-1]) exit 1 ;; esac

It sees cmake 3.10 as 3.1 and thinks it is too old.
Consequently, alibuild will build its own cmake instead of using the system one.

**Comment by brinick** [comment]
Maybe my brain is switched off, but with a test script using this line,
3.10 does not go down that exit 1 case statement. In other words, it is not
labelled as too old. This said, 3.1 does not trigger it either (which it should do
I suppose, unless cmake versions are always of the form x.y.z and not just x.y)

**Comment by davidrohr** [comment]
@brinick : Indeed...
I had this issue when I updated cmake to 3.10 on my system, but I just retried with alidist master (even though the cmake recipe didn't change), and now it detects cmake correctly.
I cannot reproduce what was the problem back then, sorry for the noise, I am closing this.
