### ISSUE TITLE
Create a repository for lhapdf

### ISSUE THREAD

**Issue by dberzano** [alisw/alidist#110]
This should include in separate branches the code used for both the `lhapdf` and the `lhapdf5` recipes, and should also integrate #109.

**Comment by qgp** [comment]
Hi @dberzano, I just add this here. Definitely needed would be for LHAPDF5: 
- cteq6ll
- EPS09LOR_208
and for LHAPDF6:
- cteq6l (the one we already put in lhapdf for ThePEG)

That's what I have on my list immediately, I would have to look deeper to see what else is needed. But this can also be done in the more systematic way as (will be) discussed.

**Comment by dberzano** [comment]
cteq6l does not exist for lhapdf6...

**Comment by dberzano** [comment]
Btw I have added a check in the recipe that makes it fail if a requested PDF set was not installed. This is also for dealing with the case where, say, the remote server is down, and we publish a corrupted package because it does not return error...

**Comment by qgp** [comment]
My bad, for LHAPDF6 it should be cteq6l1. Sorry!
