### ISSUE TITLE
ThePEG version bump

### ISSUE THREAD

**Issue by qgp** [alisw/alidist#111]
We want to move to ThePEG 20150811 in conjunction with PYTHIA 8.211_prelease. Can we make ThePEG depend on that version and then use it together with AliPhysics? How can we make sure there is no clash of PYTHIA versions?

PS: I know that this is ugly but we miss features without the special PYTHIA version for ThePEG.

**Comment by dberzano** [comment]
@qgp, this cannot be done the way you say.

AliPhysics depends on an AliRoot-builtin Pythia 8 version and does not use any external package, and we are not going to change that.

What we can do is building an external Pythia 8 package that conforms your request, and then you'll load it _after_ AliPhysics/AliRoot in your JDL and _maybe_ if Pythia people worked OK you'll be able to use it overriding the builtin one.

**Comment by qgp** [comment]
@dberzano, that's one of the fundamental problems of having PYTHIA built into AliRoot; in fact, this has caused problems already in the past. Why is it off the table to move PYTHIA into a separate package, now that also all the build infrastructure is there?

For the time being, I would indeed try with what you propose and see if we can get it to work.

**Comment by dberzano** [comment]
No, it's not off-the-table, actually the proper solution would be to have it as an external package and drop it completely from AliRoot. I am just saying that this is not something that's going to happen in a finger snap and that we're expected to raise complaints for breaking a perfectly "working" runtime environment :-)

For the purpose of supporting ThePEG, then, we'll try to do it like I have suggested.

**Comment by qgp** [comment]
Sure, I fully agree that this is nothing that should be done quickly.

Thanks for importing the new versions into the alisw repos. Are you going to also do the version bumps in the recipes or should I do it and file a pull request?

**Comment by dberzano** [comment]
I am taking care of everything, I will tag you when I make the PR.

**Comment by qgp** [comment]
Perfect, thanks a lot!
