### ISSUE TITLE
Bump FairRoot tag

### ISSUE THREAD

**Issue by sawenzel** [alisw/alidist#1112]
We need a new FairRoot tag, containing at least commit 3b01d287cdd.

This is needed in order to merge https://github.com/AliceO2Group/AliceO2/pull/1044.

**Comment by dennisklein** [comment]
Hi,

I suggest to only bump to FairRootGroup/FairRoot@3b01d28, because the next commit splits couple of components into new repos, which will need new recipes. I will propose a PR with the new repos probably beginning of next week.

Cheers

**Comment by ktf** [comment]
Closing in favour of #1114.

**Comment by sawenzel** [comment]
Reopening since this was reverted.

**Comment by ktf** [comment]
Closing in favour of #1150
