### ISSUE TITLE
Separate package for LHAPDF's PDF sets

### ISSUE THREAD

**Issue by dberzano** [alisw/alidist#119]
We need to know how to handle the difference between LHAPDF v5 and v6 formats, and what PDF sets to include.

**Comment by dberzano** [comment]
@qgp

**Comment by ktf** [comment]
The format should be the same, IIRC.

**Comment by qgp** [comment]
We should see if we find a way that adding a PDFset does not require a rebuild of all the dependencies.

Food for thought:
- package LHAPDF(5) without the PDFsets,
  a package using LHADPF(5) `requires` LHAPDF(5)
- depending packages do not `require` LHAPDF(5)_pdfs (or whatever the name would be
  LHAPDF(5)_pdfs `build_requires` LHAPDF(5)
  (but does not depend on a specific (minor) version of LHAPDF
- the PDFs are usually only needed at run time,
  a specific version of the package LHAPDF(5)_pdfs is loaded from the JDL/script/...

@dberzano, @ktf: I will have a look into this, let me know if you have thoughts on this.

**Comment by ktf** [comment]
This is almost 2 years old. I assume this has either been done, or it's not relevant anymore. Closing it.
