### ISSUE TITLE
dim.sh depends on unzip (recipe for unzip?)

### ISSUE THREAD

**Issue by omasanori** [alisw/alidist#1207]
[dim.sh uses unzip](https://github.com/alisw/alidist/blob/111983b529a922217894ee450c551c66f691fb71/dim.sh#L16) so it fails to build if the package is not installed. However, `aliDoctor` does not warn us against this. [The instructions of aliBuild prerequisites installation](https://alice-doc.github.io/alice-analysis-tutorial/building/prereq-centos7.html#install-or-upgrade-required-packages) also lacks unzip, but I am not sure if it is a right place to add.

It would be great if `aliDoctor` checks whether unzip is available on the system or not when dim (or other recipes using unzip) is requested. Building our own unzip if it is not installed might also be nice.

**Comment by dberzano** [comment]
> The instructions of aliBuild prerequisites installation also lacks unzip, but I am not sure if it is a right place to add.

Yes it's the right place, can you please add it with a PR to https://github.com/alice-doc/alice-analysis-tutorial/?

**Comment by omasanori** [comment]
@dberzano Thank you for your answer! I will do it.

**Comment by omasanori** [comment]
Here is the PR: https://github.com/alice-doc/alice-analysis-tutorial/pull/39
