### ISSUE TITLE
Ninja and Fortran: ROOT configuration fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by mpuccio** [alisw/alidist#1222]
Hi @dberzano ,
it looks like that enabling explicitly Fortran (#1218) breaks the configuration of ROOT6 when using the o2-ninja defaults on Ubuntu 18.04 with system ninja.
Here the small log:

```
CMake Error at cmake/modules/CheckCompiler.cmake:15 (enable_language):
  The Ninja generator does not support Fortran using Ninja version

    1.8.2

  due to lack of required features.  Kitware has implemented the required
  features but as of this version of CMake they have not been integrated to
  upstream ninja.  Pending integration, Kitware maintains a branch at:

    https://github.com/Kitware/ninja/tree/features-for-fortran#readme

  with the required features.  One may build ninja from that branch to get
  support for Fortran.
```

Reverting the commit of PR #1218 fix the issue for me, but it cannot work as a general solution.

Ciao,
Max

**Comment by dberzano** [comment]
Out of completeness, where does this error occur? What's the package involved?

**Comment by mpuccio** [comment]
It breaks the cmake configuration of ROOT6

**Comment by dberzano** [comment]
OK sorry I keep needing a vacation :smile:
