### ISSUE TITLE
Using VC with ROOT/CLING fails

### ISSUE THREAD

**Issue by KlewinS** [alisw/alidist#1225]
I don't know, if this is the correct place for this issue... nevertheless I put it here...

I tried to use VC in a macro, which doesn't seem to work, I get the warning 
> IncrementalExecutor::executeFunction: symbol '_ZN4Vc_16Common15checkLibraryAbiEjjPKc' unresolved while linking function '_GLOBAL__sub_I_cling_module_10'!
You are probably missing the definition of Vc_1::Common::checkLibraryAbi(unsigned int, unsigned int, char const*)
Maybe you need to load the corresponding shared library?

and afterwards, the code runs horribly slow (although it seems to find the corresponding types and functions).

Compiling the macro with ROOT fails with
> Undefined symbols for architecture x86_64:
  "Vc_1::Common::checkLibraryAbi(unsigned int, unsigned int, char const*)", referenced from:
      __GLOBAL__sub_I_simd_C_ACLiC_dict.cxx in simd_C_ACLiC_dict.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error in <ACLiC>: Compilation failed!

even just including the VC-Library in ROOT doesn't work (but also here, the corresponding types are found afterwards)
> root [0] #include <Vc/Vc>
IncrementalExecutor::executeFunction: symbol '_ZN4Vc_16Common15checkLibraryAbiEjjPKc' unresolved while linking function '_GLOBAL__sub_I_cling_module_7'!
You are probably missing the definition of Vc_1::Common::checkLibraryAbi(unsigned int, unsigned int, char const*)
Maybe you need to load the corresponding shared library?

I have the same problem on Ubuntu 16.04 and MacOS 10.13.5.

I find some similar issues on the internet, here seems to be the problem that ROOT was compiled with GCC >=5 and therefore some new ABI (I don't really know, what this means) was used. Having some global `_GLIBCXX_USE_CXX11_ABI=0` compile flag should solve the problem, but then all libraries depending on the one build with that flag, also have to be build with this flag (https://sft.its.cern.ch/jira/browse/ROOT-7978)

**Comment by KlewinS** [comment]
The main question for me is, how does O2 compiles (using VC) but I can't use VC in a macro?

**Comment by MichaelLettrich** [comment]
Hi, is this issue still relevant?

**Comment by thakurd3** [comment]
Hi,
Is you problem solved?  I am getting similar issue to Link with Vc library.

The error message as follow:

Error: Function checkLibraryAbi(VC_LIBRARY_ABI_VERSION,VC_VERSION_NUMBER,VC_VERSION_STRING) is not defined in current scope  version.h:45: 

Can you please guide, how to solve.

Thank you

**Comment by ktf** [comment]
I think this is now fixed. Reopen if not the case.
