### ISSUE TITLE
Change PACKAGE_VERSION to PACKAGE_ROOT 

### ISSUE THREAD

**Issue by Barthelemy** [alisw/alidist#1268]
Giulio explained the rationale for using PACKAGE_ROOT instead of PACKAGE_VERSION when passing variables to cmake : https://github.com/alisw/alidist/pull/1265#discussion_r212537643

There are a number of recipes that still use PACKAGE_VERSION and that should be modified to have a uniformity accross recipes.

**Comment by ktf** [comment]
I think this is now cleaned up. Closing.
