### ISSUE TITLE
Update arrow@v.0.10.0-alice1 to solve macOS compilation problem

### ISSUE THREAD

**Issue by preghenella** [alisw/alidist#1295]
I have Apple LLVM version 10.0.0 (clang-1000.10.44.2) and could not build arrow@v.0.9.0-alice1 on my system (macOS 10.13.6). I locally updated alidist to arrow@v.0.10.0-alice1 and I managed to get the compilation thru it.

**Comment by ktf** [comment]
I have done the same myself on the laptop but forgot to do a PR. Closing this in favour of #1296 which should fix it.
