### ISSUE TITLE
ROOT does not compile due to linking error with lssl

### ISSUE THREAD

**Issue by awegrzyn** [alisw/alidist#1324]
Error:
```
[ 80%] Linking CXX shared library ../../lib/libRMySQL.so
ld: library not found for -lssl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libRMySQL.6.14.04.so] Error 1
```

Environment:
- OS: macOS 10.14
- clang: clang-1000.11.45.2
- `brew --prefix openssl`: /usr/local/opt/openssl

Any ideas?

**Comment by ktf** [comment]
Notice that MySQL should not be built at all on OSX.

**Comment by Barthelemy** [comment]
@ktf why ? 

By the way, maybe I could get rid of mysql now that we opted for CCDB as backend of the QC.

**Comment by ktf** [comment]
Because in the root.sh I see `MySQL: slc7.*`. Maybe we should explicitly say that we disable it in ROOT. I think what is happening is that @awegrzyn has a local installation of MySQL, ROOT picks it up because "why not?", but effectively no one tried that combination on Mojave, hence the failure.

**Comment by awegrzyn** [comment]
Ofc I need MySQL as it’s required by one of the packages. With —disable-mysql it compiles well.

**Comment by ktf** [comment]
Yeah, understood, but the question is do you need it also in ROOT?

**Comment by dennisklein** [comment]
On Mac I usually have to do

```
export OPENSSL_ROOT_DIR=`brew --prefix openssl`
```

when compiling ROOT with FairSoft. Maybe you need a similar hint with alibuild? Instead of an environment variable you can also pass it via `-D` to cmake.

**Comment by Barthelemy** [comment]
@ktf I came to the same conclusion. I have fixes for both the recipe and QualityControl to avoid this problem. On mac, Mysql is not built and ROOT does not enable mysql whether it finds it or not. Then in QualityControl I handle properly the fact that mysql might be found but not rMysql. 
I will prepare the PRs now.

**Comment by Barthelemy** [comment]
@dennisklein I think that we already have something similar. For some reason it does not work. As we don't need it on mac for the time being, I will just skip it. thank you for the help.
