### ISSUE TITLE
geant3 fails to compile centos7

### ISSUE THREAD

**Issue by mkrzewic** [alisw/alidist#1345]
Hi, it started a few days ago, nothing special about the installation here are the relevant parts of the log:

+ cmake /home/mkrzewic/o2/sw/SOURCES/GEANT3/v2-5/v2-5 -DCMAKE_INSTALL_PREFIX=/home/mkrzewic/o2/sw/INSTALLROOT/c8c138df881dc801d5b519f646406e35a6adfaea/slc7_x86-64/GEANT3/v2-5-12 -DCMAKE_BUILD_TYPE=RELWITHDEBINFO -DCMAKE_SKIP_RPATH=TRUE
-- The C compiler identification is GNU 7.3.1                                                       
-- The CXX compiler identification is GNU 7.3.1                                                     
-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc                               
-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc -- works                      
-- Detecting C compiler ABI info                                                                    
-- Detecting C compiler ABI info - done                                                             
-- Detecting C compile features                                                                     
-- Detecting C compile features - done                                                              
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++                            
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++ -- works                   
-- Detecting CXX compiler ABI info                                                                  
-- Detecting CXX compiler ABI info - done                                                           
-- Detecting CXX compile features                                                                   
-- Detecting CXX compile features - done                                                            
-- The Fortran compiler identification is GNU 7.3.1                                                 
-- Check for working Fortran compiler: /opt/rh/devtoolset-7/root/usr/bin/gfortran                   
-- Check for working Fortran compiler: /opt/rh/devtoolset-7/root/usr/bin/gfortran  -- works         
-- Detecting Fortran compiler ABI info                                                              
-- Detecting Fortran compiler ABI info - done                                                       
-- Checking whether /opt/rh/devtoolset-7/root/usr/bin/gfortran supports Fortran 90                  
-- Checking whether /opt/rh/devtoolset-7/root/usr/bin/gfortran supports Fortran 90 -- yes           
-- Found ROOT 6.14/04 in /home/mkrzewic/o2/sw/slc7_x86-64/ROOT/v6-14-04-5                           
-- Configuring done                                                                                 
-- Generating done                                                                                  
-- Build files have been written to: /home/mkrzewic/o2/sw/BUILD/c8c138df881dc801d5b519f646406e35a6adfaea/GEANT3         
+ make -j 4 install                                                                                 

................

[ 47%] Building Fortran object CMakeFiles/geant321.dir/matx55/rsmt5t.F.o                            
[ 48%] Building Fortran object CMakeFiles/geant321.dir/matx55/ssmt5t.F.o                            
[ 48%] Building Fortran object CMakeFiles/geant321.dir/matx55/xmm55.F.o                             
[ 48%] Building Fortran object CMakeFiles/geant321.dir/miface/gfmdis.F.o                            
[ 48%] Building Fortran object CMakeFiles/geant321.dir/miface/gfmfin.F.o                            
[ 48%] Building Fortran object CMakeFiles/geant321.dir/miface/gmicap.F.o                            
/home/mkrzewic/o2/sw/SOURCES/GEANT3/v2-5/v2-5/geant321/gcbank.inc:29:19:                            
                                                                                                    
       EQUIVALENCE (Q(1),IQ(1),LQ(9)),(LQ(1),LMAIN),(IWS(1),WS(1))                                  
                   1                                                                                
Error: COMMON attribute conflicts with SAVE attribute in 'q' at (1)                                 
/home/mkrzewic/o2/sw/SOURCES/GEANT3/v2-5/v2-5/geant321/gcbank.inc:29:19:                            
                                                                                                    
       EQUIVALENCE (Q(1),IQ(1),LQ(9)),(LQ(1),LMAIN),(IWS(1),WS(1))                                  
                   1                                                                                
Error: COMMON attribute conflicts with SAVE attribute in 'q' at (1)                                 
/home/mkrzewic/o2/sw/SOURCES/GEANT3/v2-5/v2-5/geant321/gcbank.inc:29:19:                            
                                                                                                    
       EQUIVALENCE (Q(1),IQ(1),LQ(9)),(LQ(1),LMAIN),(IWS(1),WS(1))                                  
                   1                                                                                
Error: COMMON attribute conflicts with SAVE attribute in 'q' at (1)                                 
/home/mkrzewic/o2/sw/SOURCES/GEANT3/v2-5/v2-5/geant321/gcbank.inc:29:19:                            
                                                                                                    
       EQUIVALENCE (Q(1),IQ(1),LQ(9)),(LQ(1),LMAIN),(IWS(1),WS(1))                                  
                   1                                                                                
Error: COMMON attribute conflicts with SAVE attribute in 'q' at (1)                                 
/home/mkrzewic/o2/sw/SOURCES/GEANT3/v2-5/v2-5/geant321/gcbank.inc:29:19:                            
                                                                                                    
       EQUIVALENCE (Q(1),IQ(1),LQ(9)),(LQ(1),LMAIN),(IWS(1),WS(1))                                  
                   1                                                                                
Error: COMMON attribute conflicts with SAVE attribute in 'q' at (1)                                 
/home/mkrzewic/o2/sw/SOURCES/GEANT3/v2-5/v2-5/geant321/gcbank.inc:29:19:                            
                                                                                                    
       EQUIVALENCE (Q(1),IQ(1),LQ(9)),(LQ(1),LMAIN),(IWS(1),WS(1))                                  
                   1                                                                                
Error: COMMON attribute conflicts with SAVE attribute in 'q' at (1)                                 
/home/mkrzewic/o2/sw/SOURCES/GEANT3/v2-5/v2-5/geant321/gcbank.inc:29:19:                            
                                                                                                    
       EQUIVALENCE (Q(1),IQ(1),LQ(9)),(LQ(1),LMAIN),(IWS(1),WS(1))                                  
                   1                                                                                
.......................

Error: COMMON attribute conflicts with SAVE attribute in 'q' at (1)                                 
make[2]: *** [CMakeFiles/geant321.dir/build.make:7216: CMakeFiles/geant321.dir/miface/gmicap.F.o] Error 1               
make[2]: *** Waiting for unfinished jobs....                                                        
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/geant321.dir/all] Error 2                         
make: *** [Makefile:152: all] Error 2

**Comment by mkrzewic** [comment]
that sounds brutal, aren't there any compiler options to make it less strict?

**Comment by dberzano** [comment]
It really seems that a recent update in devtoolset-7 broke it... this does not happen with our own compiler.

**Comment by mkrzewic** [comment]
do you have an official recommendation (as this might hit more users after a yum upgrade) or should I just hack something together?

**Comment by dberzano** [comment]
Just to have some context. What's the exact version of devtoolset you are using?

```
rpm -qa | grep devtoolset
```

[Here](https://access.redhat.com/errata/RHBA-2018:2604) it refers to a similar problem:

> Previously, the GNU Fortran Compiler did not handle "EQUIVALENCE" statements that involved variables with the "AUTOMATIC" attribute. Support for handling these legacy constructs has been added, and they are now processed correctly. (BZ#1622238)

but I honestly don't know whether this patch "fixes" our issue or "creates" it. Given that this happens with very recent devtoolset versions, I'd say... the latter.

This probably means that the fix is correct, and we actually need to fix GEANT3.

But then again: I am anything but a Fortran expert.

In the meanwhile, you can compile using `--defaults user` to exclude a number of packages, including GEANT3. That is, in case you don't need it.

**Comment by aphecetche** [comment]
Following the issue with GEANT3 my current playbook installs : 

- devtoolset-7-gcc-c++
- devtoolset-7-make
- devtoolset-7-gdb

which results in : 

~ > rpm -qa | grep devtoolset
devtoolset-7-gcc-7.3.1-5.13.el7.x86_64
devtoolset-7-runtime-7.1-4.el7.x86_64
devtoolset-7-libstdc++-devel-7.3.1-5.13.el7.x86_64
devtoolset-7-gdb-8.0.1-36.el7.x86_64
devtoolset-7-binutils-2.28-11.el7.x86_64
devtoolset-7-make-4.2.1-3.el7.x86_64
devtoolset-7-gcc-c++-7.3.1-5.13.el7.x86_64

**Comment by dberzano** [comment]
Bummer. You've got the latest. Do you know how to fix GEANT3? Or, if it needs fixing?

**Comment by aphecetche** [comment]
I won't comment on what's left of my Fortran knowledge after ~20 years without writing a single line of it ... Let me just answer : no, I don't know how to fix GEANT3 ;-)

**Comment by mkrzewic** [comment]
in the end I just removed the devtoolset-7 gfortran like @aphecetche did. From what I can tell the error has something to do with the generous use of the argumentless SAVE statement in one of the source files. Not sure what actually should be saved so I will not even try to fix this, someone with GEANT3 knowledge should do it. giving up on this.

**Comment by Barthelemy** [comment]
I think that it is a very serious issue as our users can't compile the software following the instructions provided. Could we update the instructions to say that devtoolset7 meta package should be avoided and that only devtoolset-7-gcc-c++, devtoolset-7-make, devtoolset-7-gdb must be installed ?

**Comment by dberzano** [comment]
Thanks to @pzhristov I have proposed a fix to GEANT3 (see the PR).

**Comment by pzhristov** [comment]
The problem comes from the SAVE statement in miface/gmicap.F:51. According to the Fortran 77 standard, "Any variable in EQUIVALENCE, DATA, or SAVE statements is static regardless of any previous AUTOMATIC specification." which makes the SAVE statement redundant and for some reason the new version of the compiler doesn't like it. Commenting this line should be fine for the old and new compiler on all platforms.

**Comment by dberzano** [comment]
After testing I confirm it works with different compilers as well.
