### ISSUE TITLE
FairMQ fails to find system nanomsg Ubuntu 16.04

### ISSUE THREAD

**Issue by sawenzel** [alisw/alidist#1389]
When libnanomsg-dev is present on the system (Ubuntu 16.04), the compilation of FairMQ fails.
Apparently the cmake does not find the package.

**Comment by ktf** [comment]
@dennisklein is this a feature of the new CMake?

**Comment by dennisklein** [comment]
We currently require nanomsg 1.1.3 and import it via the CMake package (prior versions dont have CMake package). Unfortunately, I could not add a version check, because nanomsg does not install any version information. I have fixed this upstream and since it is released now with nanomsg 1.1.5, I should probably require that version.

@sawenzel How does it fail btw? Can you show the CMake output?

**Comment by dennisklein** [comment]
So, libnanomsg-dev in Ubuntu 16.04 is too old.

**Comment by ktf** [comment]
https://github.com/alisw/alidist/pull/1390 bumps the `nanomsg` version we ship with alidist, however we have the same version detection issue in our recipe. We simply check if `nn.h` can be compile. I guess we should fall back to not use `nanomsg` from the system.

**Comment by ktf** [comment]
@dberzano ideas?

**Comment by dennisklein** [comment]
> however we have the same version detection issue in our recipe. We simply check if nn.h can be compile. I guess we should fall back to not use nanomsg from the system.

Or we could check for the existence of a `lib*/cmake/nanomsg-*` directory in the recipe system check.

**Comment by dennisklein** [comment]
Or `cmake -P /dev/stdin <<< "find_package(nanomsg REQUIRED)"`. Not sure, if this works on Mac though.

**Comment by dberzano** [comment]
I think that trying to find out how to get it from the system is a bit of a burden in terms of support. I agree with @ktf that we should get it from our recipes always.

**Comment by mpuccio** [comment]
Hello, I still encounter this issue on Ubuntu. Unfortunately I cannot use another OS nor alidock for my developments. If the proper fix will take a while, is there any quick workaround I can use?

**Comment by ktf** [comment]
nanomsg is now gone. Closing.
