### ISSUE TITLE
FreeType URL link dead

### ISSUE THREAD

**Issue by davidrohr** [alisw/alidist#1453]
FreeType fails to build as the download link in the recipe is dead.

http://download.savannah.gnu.org/releases/freetype/freetype-${PKGVERSION:1}.tar.gz
gives:
Pagina non trovata
Il sito che cercavi potrebbe essere non disponibile o non più esistente. 

For me, it works with the following link, but perhaps we want to switch to the current patchlevel 2.6.5:
https://downloads.sourceforge.net/project/freetype/freetype2/2.6/freetype-2.6.tar.gz?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Ffreetype%2Ffiles%2Ffreetype2%2F2.6%2Ffreetype-2.6.tar.gz%2Fdownload&ts=1546900484

**Comment by ktf** [comment]
I think this was fixed long time ago. Closing.
