### ISSUE TITLE
Build fails in building boost

### ISSUE THREAD

**Issue by hscheid** [alisw/alidist#1485]
Hi,
I just ran into an issue when building AliPhysics. As far as I understand it the header pyconfig.h is not found. This is no wonder when looking in "/usr/includes/python3.5" since on my system it should be "python3.5m".
I am not sure why its picking up the wrong one. A small extract from the log you can find below.

Cheers,
Sebastian

```
gcc.compile.c++ build-boost/boost/bin.v2/libs/python/build/gcc-7.3.0/release/threading-multi/long.o

    "g++"   -fPIC -m64 -pthread -O3 -finline-functions -Wno-inline -Wall  -DBOOST_ALL_NO_LIB=1 -DBOOST_PYTHON_SOURCE -DNDEBUG  -I"." -I"/usr/include/python3.5" -c -o "build-boost/boost/bin.v2/libs/python/build/gcc-7.3.0/release/threading-multi/long.o" "libs/python/src/long.cpp"

In file included from ./boost/python/detail/prefix.hpp:13:0,
                 from ./boost/python/long.hpp:8,
                 from libs/python/src/long.cpp:5:
./boost/python/detail/wrap_python.hpp:50:11: fatal error: pyconfig.h: No such file or directory
 # include <pyconfig.h>
           ^~~~~~~~~~~~
compilation terminated.
```

**Comment by kreisl** [comment]
I have the same problem when using conda with python 3.6 the includes are in the folder with a suffix m, but it's looking in the folder ".../includes/python3.6". A quick fix was to add a line to the boost.sh
```
    chmod +x fake_bin/python-config
    ln -nfs "$(which python3)" fake_bin/python
    ln -nfs "$(which pip3)" fake_bin/pip
    export PATH="$PWD/fake_bin:$PATH"
    BOOST_CXXFLAGS="$(fake_bin/python-config --includes)" # added this line
  fi
fi
```
The fake_bin/python-config was created but it was not called before compilation.
During compilation boost then picked up the wrong includes.
Is it supposed to go into this branch of the if when python is picked up from the system?

**Comment by ktf** [comment]
Please have a look if https://github.com/alisw/alidist/pull/1610 fixes your issue.

**Comment by kreisl** [comment]
#1610 doesn't fix it for me.
I still need to add the line 45 for it to compile boost with python.
Otherwise it cannot find the python includes during compilation.
```
   41     chmod +x fake_bin/python-config
   42     ln -nfs "$(which python3)" fake_bin/python
   43     ln -nfs "$(which pip3)" fake_bin/pip
   44     export PATH="$PWD/fake_bin:$PATH"
+  45     BOOST_CXXFLAGS="$(fake_bin/python-config --includes)"
```
