### ISSUE TITLE
Update DIM version to v20r24

### ISSUE THREAD

**Issue by pebond** [alisw/alidist#1505]
Please update to the latest version of DIM: v20r24. It is needed for ALF software. This is a backwards-compatible update.

**Comment by awegrzyn** [comment]
@pebond Just create a PR with bumped version. The following lines needs to be edited: https://github.com/alisw/alidist/blob/03c5e5fe46d57da9f96bd8e2884aae3606b82a64/dim.sh#L2

**Comment by pebond** [comment]
Completed with PR #1532
