### ISSUE TITLE
ThePEG crashes in LEGO train and on lxplus

### ISSUE THREAD

**Issue by qgp** [alisw/alidist#151]
@dberzano, @mfloris: The new version of ThePEG segfaults in the LEGO trains and on lxplus. I just recompiled everything in the docker container and there it works. Any idea what is different for the LEGO train or lxplus installation? The relocation is already done for the installation in the container, right?

**Comment by dberzano** [comment]
Hello, please use JIRA for this. The packages are exactly the same, so is the build environment. I guess some more information would help...

**Comment by qgp** [comment]
As far as I can see, there's not really a suitable JIRA project for these issues. I can file it for AliRoot, of course.

**Comment by dberzano** [comment]
Sure, use AliRoot. Not sure how much we can help though... a stacktrace can help.
