### ISSUE TITLE
Clang recipe : clang-format load fails

### ISSUE THREAD

**Issue by Barthelemy** [alisw/alidist#1510]
On CC7 : 
1. `aliBuild build --defaults o2 Clang`
2. `alienv load Clang/latest  # or enter`
3. `clang-format -style=file -i *.cpp`
3. Get : 
```
[Clang/latest] ~/dev/alice/QualityControl $> clang-format -style=file -i *.cpp
clang-format: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by clang-format)
clang-format: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /local/alice/sw/slc7_x86-64/Clang/7.0.0-1/bin/../lib/libLLVMSupport.so.7)
clang-format: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /local/alice/sw/slc7_x86-64/Clang/7.0.0-1/bin/../lib/libLLVMSupport.so.7)
clang-format: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /local/alice/sw/slc7_x86-64/Clang/7.0.0-1/bin/../lib/libLLVMSupport.so.7)
clang-format: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /local/alice/sw/slc7_x86-64/Clang/7.0.0-1/bin/../lib/libclangBasic.so.7)
clang-format: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /local/alice/sw/slc7_x86-64/Clang/7.0.0-1/bin/../lib/libclangBasic.so.7)
clang-format: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /local/alice/sw/slc7_x86-64/Clang/7.0.0-1/bin/../lib/libclangFormat.so.7)
clang-format: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /local/alice/sw/slc7_x86-64/Clang/7.0.0-1/b
```

**Comment by bazinski** [comment]
you need the compiler as well to get the corresponding glibc.

for me:
alienv enter Clang/latest,GCC-Toolchain/latest

**Comment by Barthelemy** [comment]
Thanks for the prompt reply. I would say that Clang should therefore depend on GCC-Toolchain in the recipe. If you agree with this, I can prepare the fix.

**Comment by bazinski** [comment]
I would concur.

I dont think this is a problem in the docker method of working though.

**Comment by Barthelemy** [comment]
I am giving it a try on my CC machine. It takes some time as it has to recompile Clang.

**Comment by ktf** [comment]
Another alternative would be to have clang compiled using `libc++` (https://libcxx.llvm.org), rather than `libstdc++`, making it standalone.

**Comment by bazinski** [comment]
@ktf your suggestion would certainly be more elegant.

**Comment by sawenzel** [comment]
Did someone try to add GCC as a runtime dependency in the modulefile for Clang? This should easily solve the problem.

**Comment by ktf** [comment]
It's there, AFAICT.

**Comment by Barthelemy** [comment]
@sawenzel see #1511

**Comment by Barthelemy** [comment]
I should close this issue.
