### ISSUE TITLE
OpenSSL fails to compile on macOS

### ISSUE THREAD

**Issue by awegrzyn** [alisw/alidist#1531]
The recipe does not pick up OpenSSL from `brew` due to `fatal error: 'openssl/opensslv.h' file not found` and then fails to compile its own version:
```
*** Because of configuration changes, you MUST do the following before
*** building:

	make depend
+ make depend
making depend in crypto...
clang: error: argument unused during compilation: '-Wa,--noexecstack' [-Werror,-Wunused-command-line-argument]
make[1]: *** [local_depend] Error 1
make: *** [depend] Error 1
```

This affects https://github.com/alisw/alidist/pull/1515

**Comment by awegrzyn** [comment]
Okay I think the recipe is not meant to be compiled on macOS.
@dberzano Could you please confirm?

**Comment by dberzano** [comment]
I do.
