### ISSUE TITLE
Two recipes for go ?

### ISSUE THREAD

**Issue by aphecetche** [alisw/alidist#1542]
Hi @teo @sbinet 

I see there are two recipes for go : go.sh and golang.sh 

Do we actually need both ?

**Comment by teo** [comment]
I'm not sure. I'm maintaining `golang.sh`, it's more recent than the other one and it works for me. I don't know if we have any packages relying on `go.sh`. I'd be in favor of removing `go.sh` if it currently serves no purpose.

**Comment by ktf** [comment]
I think @sbinet is the author of the other one. Not sure why it got duplicated...

**Comment by teo** [comment]
@ktf It is probably my fault, I had no idea the other one was already there when I made `golang.sh`.

**Comment by ktf** [comment]
I need to configure your tab completion properly... ;-) Given I do not see go.sh used anywhere*, unless @sbinet has any objections, I agree we should remove it.

```bash
→ git grep -- "-[ ]*go[^a-z]"
go.sh:mkdir ali-go-tmp
go.sh:pushd ali-go-tmp
go.sh:/bin/cp -a ./ali-go-tmp/go/* $INSTALLROOT/.
go.sh:/bin/rm -rf ali-go-tmp
```

**Comment by ktf** [comment]
Let's move the discussion to the PR.

**Comment by sbinet** [comment]
Yeah, go.sh can be replaced with golang.sh
(Although, the language is called Go, not golang :P)
