### ISSUE TITLE
ROOT 6.16 compilation error

### ISSUE THREAD

**Issue by marcovanleeuwen** [alisw/alidist#1583]
I just recompiled with the latest alidist with user-next-root6 on a recent Ubuntu and get an error while compiling ROOT:

collect2: error: ld returned 1 exit status
core/metacling/src/CMakeFiles/Cling.dir/build.make:200: recipe for target 'lib/libCling.so.6.16.00' failed
make[2]: *** [lib/libCling.so.6.16.00] Error 1
CMakeFiles/Makefile2:17681: recipe for target 'core/metacling/src/CMakeFiles/Cling.dir/all' failed
make[1]: *** [core/metacling/src/CMakeFiles/Cling.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

I was trying to find more information and/or rerun make, but could not manage. When I cd to the root build dir:

marco@pcalice194:/opt/alice/sw/BUILD/ROOT-latest/ROOT$ pwd
/opt/alice/sw/BUILD/ROOT-latest/ROOT

and try make:

marco@pcalice194:/opt/alice/sw/BUILD/ROOT-latest/ROOT$ make
/opt/alice/sw/ubuntu1604_x86-64/CMake/v3.13.1-1/bin/cmake: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /opt/alice/sw/ubuntu1604_x86-64/CMake/v3.13.1-1/bin/cmake)
Makefile:8844: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1

I also looked at the file: compile_commands.json
but it does not seem to contain the link commands (the string 'libCling' is not found)

Also tried
export VERBOSE
to get make/cmake to show what it is doing, but this does not seem to affect the building inside aliBuild.

Any suggestions for how to debug this further?

Marco.

**Comment by marcovanleeuwen** [comment]
Oops, disk was full; please ignore...

**Comment by ktf** [comment]
yeah, that's what I was about to say. Maybe you should try to do `aliBuild clean` to see if that frees up some space.
