### ISSUE TITLE
Boost 1.70.0 and CMake lessons

### ISSUE THREAD

**Issue by dennisklein** [alisw/alidist#1614]
Dear alidist maintainers,

I would like to share some lessons I learned with Boost `1.70` to save some time when these issues pop up. Since version `1.70` Boost installs its own CMake package by default. While I applaud this effort (no need to update CMake any more for newest `FindBoost.cmake`), it comes with some issues:
* The `QUIET` argument passed to `find_package()` is ignored ([this is fixed](https://github.com/boostorg/boost_install/issues/3) in the next release on Boost side, CMake side [will be fixed](https://gitlab.kitware.com/cmake/cmake/issues/19186) in `3.15`)
* When building with `link=shared` (as we currently do), a simple `find_package(Boost)` may fail by complaining about an unsuitable build variant.
  * The error string which hints the solution (`... BUILD_SHARED_LIBS not ON, set Boost_USE_STATIC_LIBS=OFF to override ...`) does not work ([this is fixed](https://github.com/boostorg/boost_install/commit/160c7cb2b2c720e74463865ef0454d4c4cd9ae7c) in the next Boost release).
  * (The problem of inspecting the `BUILD_SHARED_LIBS` variable at all [is reported](https://github.com/boostorg/boost_install/issues/5), too.)
* If the [basic function signature (or module mode) of `find_package()`](https://cmake.org/cmake/help/latest/command/find_package.html) is used - should be most of our uses - CMake will first call the `FindBoost.cmake` module which will try to find a CMake package for Boost. If it succeeds, it may print wrong status messages. This affects CMake up to `3.14` and [will be fixed](https://gitlab.kitware.com/cmake/cmake/issues/19186) in `3.15` (hopefully, merge pending).

Considering the above, I recommend to disable the CMake package temporarily (pass `--no-cmake-config` to bjam) for `1.70` and enable once we go for `1.71`. Next thing to look out for is how homebrew will decide here for `1.70` ...

**Comment by Barthelemy** [comment]
thanks a lot

**Comment by Barthelemy** [comment]
By the way, I have just tried cmake 3.15 on mac and fairroot does not build : 
```
DEBUG:QualityControl:FairRoot:0: -- Build CbmModule with Gdml support
DEBUG:QualityControl:FairRoot:0: CMake Error at MbsAPI/CMakeLists.txt:19 (CHECK_SYMBOL_EXISTS):
DEBUG:QualityControl:FairRoot:0:   Unknown CMake command "CHECK_SYMBOL_EXISTS".
```
Is it something you are aware of  ?

**Comment by dennisklein** [comment]
I was not, but a quick git bisect revealed FairRootGroup/FairRoot@7beb33524a7afe64a4a20534c9f7b38b4657924c.

**Comment by ktf** [comment]
Closing this as it's not really a bug. Thank you for the insight.
