### ISSUE TITLE
o2-dataflow defaults is broken

### ISSUE THREAD

**Issue by Barthelemy** [alisw/alidist#1618]
The commit 9eb2f1f2c80eb5a783dda52e0883ad57d1f3794f " Add AEGIS as a module required by O2 (#1593) " broke it. 

Error reads : 
```
bvonhall@nouveaumacbarth alice $ aliBuild build --defaults o2-dataflow O2Suite
ERROR: Specified default `o2-dataflow' is not compatible with the packages you want to build.
ERROR: Valid defaults:
ERROR: 
ERROR: - o2
```

**Comment by Barthelemy** [comment]
@teo @awegrzyn @shahor02 @dberzano

**Comment by awegrzyn** [comment]
Yup, I've been adding to all my recipes:
```
valid_defaults:
  - o2
  - o2-dataflow
```

**Comment by Barthelemy** [comment]
Adding it to aegis should be enough in the end : https://github.com/alisw/alidist/pull/1619

**Comment by awegrzyn** [comment]
Not sure if it's good idea as `AEGIS` requires `pythia6` which is disabled in `o2-dataflow`. 

What about disabling `AEGIS` in `o2-dataflow` defaults?
