### ISSUE TITLE
Control-Core build on macOS still failing

### ISSUE THREAD

**Issue by kostorr** [alisw/alidist#1621]
I am still having problem with building Control-Core for macOS.

1) The requirement `- "GCC-Toolchain:(?!osx)"` seems to go unnoticed.
2) Removing the conditional and forcing the dependency results in the following errors with and without the `--no-system` flag
[control-mac.log](https://github.com/alisw/alidist/files/3147516/control-mac.log)
[control-nosystem-mac.log](https://github.com/alisw/alidist/files/3147517/control-nosystem-mac.log)

**Comment by teo** [comment]
@kostorr none of these seem to fail in Control-Core itself.
@dberzano could you please provide some insight?

**Comment by dberzano** [comment]
I have found a problem in the gRPC recipe (where OpenSSL as dependency should actually be `OpenSSL:(?!osx)`. Apart from that, the requirements are absolutely correctly parsed on my system.

My command (this includes Control-Core as a dependency):

```
aliBuild build Control --defaults o2-dataflow --debug
```

Are you providing extra flags to the command? What Python version are you using?

**Comment by kostorr** [comment]
No extra flags. Ran once with the command you referenced and one with the`--no-system` flag. 

```
kalexopo@boreas alice $ python --version
Python 2.7.16
```

**Comment by kostorr** [comment]
Any suggestions on how to proceed with this?

**Comment by ktf** [comment]
Could you provide us the result of:

```
aliBuild doctor Control --defaults o2-dataflow
aliBuild deps Control --defaults o2-dataflow --outgraph deps.pdf
```

**Comment by kostorr** [comment]
[doctor.txt](https://github.com/alisw/alidist/files/3176923/doctor.txt)
[deps.pdf](https://github.com/alisw/alidist/files/3176924/deps.pdf)

**Comment by awegrzyn** [comment]
This is where it fails:
```
[ 68%] Linking CXX executable bin/infoLoggerD
/Users/awegrzyn/alice/sw/SOURCES/InfoLogger/v1.2.4/v1.2.4/src/infoLoggerJAVASCRIPT_wrap.cxx:1028:43: error: no matching member function for call to 'ToObject'
  v8::Handle<v8::Object> objRef = valRef->ToObject();
                                  ~~~~~~~~^~~~~~~~
...
```
So I guess this is connected with InfoLogger, calling @sy-c 

@teo Why `Control-Core` must depend on MySQL? Is it possible to use `libInfoLogger` instead?

**Comment by teo** [comment]
@awegrzyn Control-Core doesn't need MySQL at all. It is technically very feasible to depend on `libInfoLogger` instead, but infrastructure-admin prefers to keep the libInfoLogger package without a dependency on Go. Such a dependency is needed to generate the Go interface. We ended up keeping `libInfoLogger` C++ only, and `InfoLogger` built with all the language bindings. I can't say I'm happy about using `InfoLogger` rather than `libInfoLogger` but that's the current state of things.

**Comment by awegrzyn** [comment]
@teo After getting rid of InfoLogger problem `Control-Core` fails on:
```
-e \e[1;33mCGO_LDFLAGS=/Users/awegrzyn/alice/sw/BUILD/d8b33dfbeebf4831ab2c8b3cfbf965ae453d72ab/Control-Core/go/src/github.com/AliceO2Group/Control/vendor/infoLoggerForGo/infoLoggerForGo.a -static-libstdc++ -static-libgcc  go build\e[0m ./cmd/o2control-core  \e[1;33m==>\e[0m  \e[1;34m./bin/o2control-core\e[0m
# runtime/cgo
clang: error: unsupported option '-static-libgcc'
make: *** [o2control-core] Error 2
```

**Comment by kostorr** [comment]
Here is the clang error.

[control-mac-clang.log](https://github.com/alisw/alidist/files/3202382/control-mac-clang.log)

**Comment by kostorr** [comment]
> @teo After getting rid of InfoLogger problem `Control-Core` fails on:
> 
> ```
> -e \e[1;33mCGO_LDFLAGS=/Users/awegrzyn/alice/sw/BUILD/d8b33dfbeebf4831ab2c8b3cfbf965ae453d72ab/Control-Core/go/src/github.com/AliceO2Group/Control/vendor/infoLoggerForGo/infoLoggerForGo.a -static-libstdc++ -static-libgcc  go build\e[0m ./cmd/o2control-core  \e[1;33m==>\e[0m  \e[1;34m./bin/o2control-core\e[0m
> # runtime/cgo
> clang: error: unsupported option '-static-libgcc'
> make: *** [o2control-core] Error 2
> ```

Exactly...

**Comment by teo** [comment]
@kostorr @awegrzyn I guess we need to find the clang-equivalent of that parameter. This looks related https://reviews.llvm.org/D37726

**Comment by sy-c** [comment]
I don't think there is a similar option available for clang. See e.g. https://stackoverflow.com/questions/22622477/what-to-replace-static-libgcc-with-when-using-clang

**Comment by Barthelemy** [comment]
I can only confirm the problem.

**Comment by Barthelemy** [comment]
If I remove the options from the makefile it compiles.

**Comment by kostorr** [comment]
Yes, but then on execution, it will crash with a SIGABRT when InfoLogger is used.

**Comment by teo** [comment]
@kostorr Does this happen when executing with InfoLogger alienv-loaded?

**Comment by Barthelemy** [comment]
it happens using alibuild, i.e. without alienv as they are not "compatible". If you load the env then you can't run alibuild.

**Comment by kostorr** [comment]
@teo Yup, no change.

**Comment by ktf** [comment]
I assume this is fixed.
