### ISSUE TITLE
python-modules build failure on centos7 (matplotlib)

### ISSUE THREAD

**Issue by ironMann** [alisw/alidist#1628]
Hi, I have a build failure in python-modules while trying to build o2 with o2-dataflow defaults on a centos7 server. (manual alibuild without docker)

Logs [here](https://cernbox.cern.ch/index.php/s/6Hyx3F0stEUFreV)

This diff fixes it for me:
```diff
diff --git a/python-modules.sh b/python-modules.sh
index 13caefd..94262c5 100644
--- a/python-modules.sh
+++ b/python-modules.sh
@@ -59,6 +59,8 @@ env PYTHONUSERBASE="$INSTALLROOT" pip3 install --user -IU -r requirements.txt
 pushd "$INSTALLROOT"
   if [[ -d lib64 ]]; then
     ln -nfs lib64 lib  # creates lib pointing to lib64
+  else
+    ln -nfs lib lib64
   fi
   pushd lib
     ln -nfs python$PYVER python
```

**Comment by ktf** [comment]
I guess it makes sense. Can you open a PR with it? Could you also add a test making sure that lib itself exists?
