### ISSUE TITLE
Error compiling RooUnfold on SL6

### ISSUE THREAD

**Issue by marcovanleeuwen** [alisw/alidist#1654]
Dear Markus, all,

When compiling aliphysics on SL6, I get the following error message for RooUnfold:

make[2]: *** No rule to make target `/usr/lib64/lib64/libboost_unit_test_framework-mt.so.5', needed by `libRooUnfold.so'.  Stop.

It looks like there is a double 'lib64' in the directory name. I went a bit through the CMake files, but could not identify where this is done. Earlier in the log file, I see:

>-- Boost  found.
>-- Found Boost components:
>   unit_test_framework
>-- ** Boost Include path: /usr/include
>-- ** Boost Library path: /usr/lib64
>-- ** Boost Libraries: optimized;boost_unit_test_framework-mt-shared;debug;boost_unit_test_framework-mt-shared-debug

which looks fine; the only doubt I have is that it is apparently picking up the system-wide installed boost libraries instead of the boost libraries that are installed by aliBuild.

In CMakeCache.txt, I found:
> //The directory containing a CMake configuration file for Boost.
> Boost_DIR:PATH=/usr/lib64/boost
> ....
> //Dependencies for the target
> RooUnfold_LIB_DEPENDS:STATIC=optimized;boost_unit_test_framework-mt-shared;debug;boost_unit_test_framework-mt-shared-debug;general;/data1/software/alisoft/slc6_x86-64/ROOT/v6-10-08-2/lib/libCore.so;general;/data1/software/alisoft/slc6_x86-64/ROOT/v6-10-08-2/lib/libImt.so;general;/data1/software/alisoft/slc6_x86-64/ROOT/v6-10-08-2/lib/libRIO.so; .....

so there is no explicit path for the boost_unit_test_framework-mt-shared.

Any suggestions how to debug this further are welcome...

Best regards,

Marco.

**Comment by ktf** [comment]
I see that we are currently building ROOUnfold on slc6 and deploying on the grid, so I assume this was fixed at some point. Reopen if not the case.
