### ISSUE TITLE
Boost recipe using headers from brew boost on macOS

### ISSUE THREAD

**Issue by mfasDa** [alisw/alidist#1656]
Dear experts,

It turned out that

export CPLUS_INCLUDE_PATH="$CPLUS_INCLUDE_PATH:$(python3 -c 'import sysconfig; print(sysconfig.get_path("include"))')"

makes the boost build picking up boost headers from brew in case the python3 installation comes from brew as well. As on mac boost is anyhow not built with boost support can we put this line within a protection ("if [ $ARCHITECTURE == osx ] ...")?

Remove boost from brew is not a solution as users might have installed programs that rely on boost from brew.

Cheers

Markus

**Comment by mfasDa** [comment]
@dberzano @ktf Would you agree with this fix?

**Comment by ktf** [comment]
I agree this is an issue, I am not sure what you want to do, though. Could you open a PR?

**Comment by mfasDa** [comment]
Thanks for the reply! I will open a PR.

What I want to do is the following: The reason why this happens is that both the boost and the python headers are taken from /usr/local/include on macOS when python3 is installed via homebrew (which I assume is the standard case for mac), and by setting CPLUS_INCLUDE_PATH consequently the boost headers from homebrew are propagated. As the boost versions in brew and alidist are different this creates the compiler errors. As currently boost is anyhow configured on mac without python support (see a couple of lines above) setting the include path for python on mac is not really needed and this bypasses the problem for the moment. It is not really a solution as maybe at some point you want to add python support for boost also on mac. However I also think you cannot force the users to remove boost from homebrew as this might raise other issues (boost is pretty fundamental). So maybe for mac you will have to install a custom python3 ...

**Comment by ktf** [comment]
I understand the issue and I agree. Let's move the discussion to the PR.
