### ISSUE TITLE
Recipe for glfw

### ISSUE THREAD

**Issue by aphecetche** [alisw/alidist#1680]
(talking about dependencies on Mac...)

I'd like to be able to compile w/ or w/o glfw on my Mac, without having to brew install/remove it. 
If there was a glfw recipe that would be kind of easy, right ?

Or is there a reason of _not_ having such a recipe ?

(and yes, if we agree that'd be good to have, I'll make it ;-) )

**Comment by ktf** [comment]
The idea was that the GUI should not impose a requirement, especially in the beginning when I was not sure how it would have been welcome. Now that we give it a bit for granted, I guess we can have a proper recipe as well. That's my 2 cents, at least.

**Comment by Barthelemy** [comment]
The only risk I see is with alidock. If we install glfw automatically, the GUIs will be built and I am not sure what will happen when users will run a DPL workflow. Will it crash ?

**Comment by aphecetche** [comment]
Hi Barth,

Please see #1684 : I'm actually not proposing to install glfw automatically, just to have a recipe that makes it easy to install it. 

Use case here is mainly for Macs I would say :  on those, if you install glfw with brew, then you are somehow forced to use it in O2 builds. With a recipe, you have the option (emphasis on option here) to uninstall glfw from brew, install it with the recipe and then, depending on whether or not you use the resulting module in the terminal where you do alibuild, you'll get a build with or without glfw. In that respect, it's not change, but an optional addition only.

**Comment by Barthelemy** [comment]
Hi, 
Thank you for the clarification. It makes sense. Good.
See you

**Comment by ktf** [comment]
For the record. DPL should work just fine with the GUI compiled in but non-functional, e.g. because of missing display. Also notice that modules are not for compile time dependencies. At this point, where the GUI is largely accepted and actually missed if not there, why making it optional?

--
Ciao,
Giulio

**Comment by aphecetche** [comment]
The initial idea was to be able to easily test the cmake build with (what we usually have on Macs) and without glfw (what we usually(?) have on CC7 servers) on the same machine (either Mac or CC7). And as stated above, the mere existence of a glfw recipe makes that possible without changing anything to the current situation, which I guess is just a win-win deal.

I personally would not make glfw a required dependency altogether. We already have lots of dependencies. Each dependency adds some compilation time, some maintenance burden, and some risk(s) for the future (e.g if that deps is no longer actively developed). Given that glfw is not critical to have the final product working -while being very handy for dev, I certainly won't dispute that very true fact-, I would simply avoid turning it into a hard requirement. But ok, that's just me ;-)

**Comment by ktf** [comment]
GLFW is now included as a dependency of DebugGUI.
