### ISSUE TITLE
New AliGenerators build

### ISSUE THREAD

**Issue by qgp** [alisw/alidist#1702]
Hi @dberzano, @ktf, 

we would need a new build of the AliGenerators suite (with versions and code as in alidist already). Could you trigger this build, please? Or let us know in case of problems, of course.

Cheers,
   Jochen

FYI: @mfasDa

**Comment by dberzano** [comment]
Hi @qgp, I am trying to build it and I'll inform you on the status/problems.

**Comment by dberzano** [comment]
See #1714.
