### ISSUE TITLE
AliPhysics fails to compile in Cray Compiling Environment without -DCMAKE_Fortran_COMPILER=gfortran

### ISSUE THREAD

**Issue by yslai** [alisw/alidist#1731]
AliPhysics CMake configuration fails on Cray systems with Cray Compiling Environment with
```
DEBUG:AliPhysics:AliPhysics:ali-master: -- FastJet was compiled with CGAL
DEBUG:AliPhysics:AliPhysics:ali-master: CMake Error at cmake/FindFASTJET.cmake:115 (message):
DEBUG:AliPhysics:AliPhysics:ali-master:   CGAL not found under the given location
```
Tracing the `find_library()` function reveals that shared library support becomes deactivated after the Fortran compiler detection, when CMake finds the static-compilation-only `ftn` before `gfortran`:
```
-- CMAKE_FIND_LIBRARY_SUFFIXES=.so;.a
-- Cray Programming Environment 2.5.15 Fortran
-- Fortran compiler is /opt/cray/pe/craype/2.5.15/bin/ftn
-- CMAKE_FIND_LIBRARY_SUFFIXES=.a
```
Note that AliRoot does not suffer from this problem, since the `-DCMAKE_Fortran_COMPILER=gfortran` is explicitly supplied in its alidist script.

**Comment by ktf** [comment]
This was long ago, so I am closing. In case this is still needed, please open a PR with your fix to aliphysics.sh, since the fix seems legit.
