### ISSUE TITLE
'abrt-cli status' timed out

### ISSUE THREAD

**Issue by awegrzyn** [alisw/alidist#1743]
When using `aliswmod enter` to load a module installed by RPM I get an error:
```
'abrt-cli status' timed out
```

This is caused by:
```
abrt-cli: /opt/alisw/el7/lzma/v5.2.3-12/lib/liblzma.so.5: version `XZ_5.1.2alpha' not found (required by /lib64/librpmio.so.3)
```

**Comment by ktf** [comment]
What is `aliswmod`?

**Comment by awegrzyn** [comment]
Well, it's a tool that comes together with aliBuild RPMs.

**Comment by ktf** [comment]
Oh, well... Good to know... It's not part of `alibuild` itself though and I cannot find it right now (maybe in ali-bot?).

Anyways, I suspect what's happening is that such a script is invoking `rpm` and some recent centos7 update made `rpm` depend on a version of XZ incompatible with the one we ship in AliceO2. 

Can you strace it / run with `-x`?

**Comment by ktf** [comment]
Are you in a nested environment?

**Comment by awegrzyn** [comment]
> Are you in a nested environment?

It's a physical machine with CRU configured.

**Comment by ktf** [comment]
I meant if you did `aliswmod enter` twice.

**Comment by awegrzyn** [comment]
Nope, just once

**Comment by Barthelemy** [comment]
`aliswmod` = `alienv` for rpms

Instructions we are following : https://aliceo2group.github.io/quickstart/binaries.html

The oldest reference in my emails is from June 2018, if that helps. 

I see a few lines about it in `ali-bot/publish/pub-rpms-template.sh` : 
```
# Create aliswmod RPM
ALISWMOD_VERSION=2
ALISWMOD_RPM="alisw-aliswmod-$ALISWMOD_VERSION-1.%(arch)s.rpm"
if [[ ! -e "%(repodir)s/$ALISWMOD_RPM" ]]; then
  mkdir -p aliswmod/bin
  cat > aliswmod/bin/aliswmod <<EOF
#!/bin/bash -e
export MODULEPATH=$INSTALLPREFIX/$FLAVOUR/modulefiles:$INSTALLPREFIX/$FLAVOUR/etc/Modules/modulefiles:\$MODULEPATH
EOF
  cat >> aliswmod/bin/aliswmod <<\EOF
```

**Comment by ktf** [comment]
I assume this is fixed / not relevant anymore.
