### ISSUE TITLE
Binaries installed by aliBuild RPMs require glfw

### ISSUE THREAD

**Issue by awegrzyn** [alisw/alidist#1744]
RPMs generated today fail due to missing `glfw`:
```
Error: libglfw.so.3: cannot open shared object file: No such file or directory
```
This must be either reverted or `glfw` added to O2 spec file.

@dberzano @ktf @MichaelLettrich

**Comment by ktf** [comment]
Mmm... What is actually causing the error? Simply installing the rpm?

**Comment by ktf** [comment]
https://github.com/alisw/alidist/pull/1684 is still unmerged, and that's the only think I can think of which might have caused it. How was the RPM built?

**Comment by awegrzyn** [comment]
Installation works well.
I renamed the issue as it was not clear.
```
[root@adam ~]# aliswmod enter QualityControl/v0.15.2-5
[root@adam ~]# qcRunBasic 
qcRunBasic: error while loading shared libraries: libglfw.so.3: cannot open shared object file: No such file or directory
```

**Comment by ktf** [comment]
Ah, ok. I wonder if it's fallout from the CMake migration, forcing stricter dependencies. @davidrohr @aphecetche ? Maybe we should simply go ahead with #1684....

**Comment by davidrohr** [comment]
I think the problem might be that now the tracking builds automatically vs glfw if it is found on the system (Beforehand, a special CMake flag was required to build it vs glfw). Consequently, when we build an RPM on a system where glfw is available, the tracking will require it, so it will not run on a system without glfw. I think the same was true before for the DebugGUI, but that was probably not pulled in as a dependency for QC.

Where are the RPMs built? I think in general, the correct solution is to have all libraries available on the RPM build server also on the system where the RPM is deployed.

**Comment by awegrzyn** [comment]
Just additional info, last QC version that does not require `glfw` is `QualityControl/v0.15.2-1`.
`QualityControl/v0.15.2-2` already requires it.

**Comment by ktf** [comment]
The dependency on GLFW in the build machine is there since a almost a year https://github.com/alisw/docks/commit/93f763d3a2c77c6873e5ab671b707eff6c1cd301#diff-af65ad152a6a7488c2b8a6e2311926df . Maybe some CC7 implicit dependency has changed and it's not installed on target system anymore?

**Comment by awegrzyn** [comment]
@ktf In the `yum deplist` there's no GLFW even in old version.

**Comment by ktf** [comment]
Should be fixed now as we provide GLFW ourselves.
