### ISSUE TITLE
Is @alisw/pwgmm obsolete as a name?

### ISSUE THREAD

**Issue by ktf** [alisw/alidist#1762]
It looks like in CODEOWNERS we refer to a pwgmm group which AFAICT does not exist anymore. Did this change and we forgot to update CODEOWNERS?

https://github.com/alisw/alidist/blob/90c770fc183c60ba7e6ef78879297536024dd9af/CODEOWNERS#L26

**Comment by ktf** [comment]
@qgp @dberzano

**Comment by maireiphc** [comment]
The name seems to have changed indeed in the meantime for **alipwgmm** instead of pwgmm.
As you seem to have noticed or changed yourself.
By now, we can close this issue, I believe.
