### ISSUE TITLE
Python should be built before boost

### ISSUE THREAD

**Issue by awegrzyn** [alisw/alidist#1799]
I don't know when it actually happened but when building ReadoutCard (or any other package) `boost` is built before `python`. 
```
...
     - boost@v1.68.0
     - PDA@12.0.0
     - XRootD@v3.3.6-alice2
     - Common-O2@v1.4.6
     - libInfoLogger@v1.3.4
     - AliEn-Runtime@v2-19-le
     - Python@v3.6.8
     - Python-modules@1.0
     - ReadoutCard@v0.11.11
```

Due to that boost_python36 is not built:
```
DEBUG:ReadoutCard:boost:v0.11.11: Component configuration:
...
DEBUG:ReadoutCard:boost:v0.11.11:     - python                   : not building
```

And eventually ReadoutCard fails:
```
 Could not find the following Boost libraries:
      boost_python36
```

**Comment by awegrzyn** [comment]
@kostorr

**Comment by ktf** [comment]
Are you on mac? For some reason, since the python3 migration, boost does not depend on python there anymore:

https://github.com/alisw/alidist/blob/master/boost.sh#L7

Could you try removing such the (?!osx) constrain?

**Comment by ktf** [comment]
Even better, could you make the dependency of "Python" not "Python-modules".

**Comment by awegrzyn** [comment]
Hi @ktf, Nope, I'm on CC7.

**Comment by ktf** [comment]
Weird. Could you attach the result of:

```
alibuild/aliBuild deps ReadoutCard --defaults o2-dataflow --outgraph with-system.pdf
alibuild/aliBuild deps --no-system ReadoutCard --defaults o2-dataflow --outgraph without-system.pdf
```

(or whatever you are using as a recipe)?

**Comment by awegrzyn** [comment]
Wow, I didn't know we had such a nice visualisation.
So eventually the problem is that  I am not using any defaults.
[dataflow-defaults](https://github.com/alisw/alidist/files/3541053/with-system-dataflow.pdf)
[no-defaults](https://github.com/alisw/alidist/files/3541054/with-system.pdf)

**Comment by ktf** [comment]
Ah, yes, it might be that for Run2 we do not want the dependency of boost on python to avoid having fastjet depend on python... Maybe it should be discussed with the physics community to finally try to harmonise Run2 and Run3 configs...

**Comment by awegrzyn** [comment]
Ok, thanks !
