### ISSUE TITLE
Inexistent tag name in debuggui.sh 

### ISSUE THREAD

**Issue by ihrivnac** [alisw/alidist#1805]
There is no tag v0.1.0 in https://github.com/AliceO2Group/DebugGUI.
This causes an error when running a private scripts for evaluation of  total number of code lines in AliceO2Group SW packages.

**Comment by ktf** [comment]
I will fix it. Could you make the script public, please?

**Comment by ihrivnac** [comment]
Thank you. The script is not mine, so I have to check with the author if it can be published.
