### ISSUE TITLE
Tests are not executed during QC PRs

### ISSUE THREAD

**Issue by Barthelemy** [alisw/alidist#1830]

**Comment by ktf** [comment]
The problem is that in `qualitycontrol.sh` the incremental recipe does not actually do any tests, just the full rebuild. You should add the extra stuff also there.

**Comment by Barthelemy** [comment]
ahhhhh of course, I did not think of this. Thanks !

**Comment by Barthelemy** [comment]
https://github.com/alisw/alidist/pull/1833
