### ISSUE TITLE
Clang installation breaking on mac

### ISSUE THREAD

**Issue by mfasDa** [alisw/alidist#1840]
Clang installation (dependency of o2codechecker) is breaking on mac (10.14.6) with the following error:

DEBUG:o2codechecker:Clang:aliceo2: ++ chmod u+x /Users/markusfasel/alice/sw/INSTALLROOT/a648ad042743447e1e4818773d90be917e387d88/osx_x86-64/Clang/7.0.0-1/bin/git-clang-format
DEBUG:o2codechecker:Clang:aliceo2: ++ find /Users/markusfasel/alice/sw/SOURCES/Clang/7.0.0/v7.0.0-alice1/tools/clang/tools/scan-build -type f -perm /111 -exec cp '{}' /Users/markusfasel/alice/sw/INSTALLROOT/a648ad042743447e1e4818773d90be917e387d88/osx_x86-64/Clang/7.0.0-1/bin ';'
DEBUG:o2codechecker:Clang:aliceo2: find: -perm: /111: illegal mode string

**Comment by ktf** [comment]
I think this was fixed. Reopen if not the case.
