### ISSUE TITLE
gcc 7.3.1 (devtoolset-7) fails to compile arrow 0.14.1 (Centos7)

### ISSUE THREAD

**Issue by ironMann** [alisw/alidist#1845]
There seems to be a known internal compiler error in 7.3.1 series affecting compilation of the new arrow version. [Bugfix advisory ](https://access.redhat.com/errata/RHBA-2018:3562) suggest using devtoolset-8, see [Bug 1629813](https://bugzilla.redhat.com/show_bug.cgi?id=1629813)

What is the recommended solution here? 
Can O2 be built with devtoolset-8, which would match Centos8 version?

Here's the relevant error message: 
```
gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)

> aliBuild build O2 --debug  --always-prefer-system --defaults o2-dataflow

/home/##/alice/sw/SOURCES/arrow/v0.14.1/apache-arrow-0.14.1/cpp/src/arrow/result.h:89:7:   required from 'class arrow::Result<std::shared_ptr<arrow::Array> >'
/home/##/alice/sw/SOURCES/arrow/v0.14.1/apache-arrow-0.14.1/cpp/src/arrow/array.cc:504:39:   required from here
/home/##/alice/sw/SOURCES/arrow/v0.14.1/apache-arrow-0.14.1/cpp/src/arrow/vendored/variant.hpp:2243:9: internal compiler error: unexpected expression 'I' of kind template_parm_index
         typename T = lib::type_pack_element_t<I, Ts...>,
         ^~~~~~~~
```

**Comment by ktf** [comment]
I think the 8 is for GCC version, not for the centos one. Given devtoolset-7 is not installed anymore on lxplus at CERN, I would vote we simply drop support for it.

**Comment by davidrohr** [comment]
Didn't we want to switch to GCC 8 anyway? Perhaps we should test devtoolset 8?

**Comment by ironMann** [comment]
I meant Centos8 comes with gcc8.2. Using devtoolset-8 would make us closer to that.

**Comment by ktf** [comment]
@ironMann yes, correct.

@davidrohr there is some stuff to be done in order to be able to deploy GCC 8 on CVMFS, and I did not get around to do it yet.

**Comment by ktf** [comment]
That of course does not mean that we cannot simply support GCC 8 if one has it on the system, though.

**Comment by ironMann** [comment]
Closing this since the same build passes with devtoolset-8.
