### ISSUE TITLE
fastjet broken on mac

### ISSUE THREAD

**Issue by jolopezl** [alisw/alidist#1866]
After PR #1454 (@davidrohr), cgal builds(thanks! I had it hacked before), but fastjet compilation fails now.

See https://cernbox.cern.ch/index.php/s/ZQ7v95mLEeqOY7l for a complete log. I think the biggest problem is that `std::random_shuffle` in cgal, is not in c++17 anymore:

`error: no member named 'random_shuffle' in namespace 'std'; did you mean simply 'random_shuffle'?
        std::random_shuffle(begin,end,rng);`

Error appears after trying to build AliRoot with `--defaults o2`.

Do you think it is possible to work out a solution?

[fastjet-latest.log](https://github.com/alisw/alidist/files/3737296/fastjet-latest.log)

**Comment by davidrohr** [comment]
That is actually weird, the PR was particularly to make cgal/fastjet/AliRoot build with O2 defaults, and it worked few months ago when I opened the PR. So something must have gone wrong in the mean time. I'll have a look. It is definitely my goal to work out a solution. The aim is to be able to build AliRoot/AliPhysics with --defaults o2.

**Comment by jolopezl** [comment]
> The aim is to be able to build AliRoot/AliPhysics with --defaults o2

This is exactly what I need.

Before I had fixed cgal and it worked, but I just removed the register type to avoid the problems with c++17. The problem now seems to be that random_shuffle is gone, but I don't know what this didn't come up earlier.

**Comment by davidrohr** [comment]
Hi @mfasDa : I do not really understand what you mean? In the current cgal.sh recipe, it uses "." as CMake source dir? Could you explain more exactly what you mean or open a PR that fixes this?

**Comment by mfasDa** [comment]
Hi @davidrohr, sorry for the spam - my fault! Was a remanent of a hack I applied getting the more modern CGAL from the git for builds using o2 defaults. Sorry again! Cheers Markus
