### ISSUE TITLE
Handling of system library detection for aliBuild / alidist; compilation on arch

### ISSUE THREAD

**Issue by wiechula** [alisw/alidist#1968]
I'm trying to compile o2 on arch linux (I know it is not a supported platform).
For many required packages I have installed the libraries on the system. However, alibuild still compiles them. This is the list (might be more):
* protobuf
* vc
* double-conversion
* llvm
* openssl 1.0 (sitting in /usr/include/openssl-1.0/ /usr/lib/openssl-1.0)
* googletest
* fmt
* libtirpc
* bz2 (although there is not build recipe in bz2.sh, only system_requirement_check)

is this because there is no 'prefer_system_check' in the recipes? Then I could try to add them.

I could try to add basic arch support myself in alibuild, but I don't really know where to look at. The first thing I noticed is that I need a patch like:
```
--- a/alibuild_helpers/utilities.py
+++ b/alibuild_helpers/utilities.py
@@ -83,7 +83,7 @@ def doDetectArch(hasOsRelease, osReleaseLines, platformTuple, platformSystem, pl
   distribution, version, flavour = platformTuple
   # If platform.dist does not return something sensible,
   # let's try with /etc/os-release
-  if distribution not in ["Ubuntu", "redhat", "centos"] and hasOsRelease:
+  if distribution not in ["Ubuntu", "redhat", "centos", "arch"] and hasOsRelease:
     for x in osReleaseLines:
       if not "=" in x:
         continue
@@ -139,7 +139,7 @@ def detectArch():
     platformTuple = platform.dist()
     platformSystem = platform.system()
     platformProcessor = platform.processor()
-    if " " in platformProcessor:
+    if " " in platformProcessor or platformProcessor == "":
       platformProcessor = platform.machine()
     return doDetectArch(hasOsRelease, osReleas-I/usr/include/tirpceLines, platformTuple, platformSystem, platformProcessor)
   except:
```
 To get `arch_x86-64` as detected platform and then use `--force-unknown-architecture`.

There were a few more things I needed to do, but then I was able to compile.

Happy new year,
Jens

**Comment by davidrohr** [comment]
Hi Jens,

I am also using the force unknown architecture flag on Gentoo. That is not really a problem.

There is a couple of packages (you list several) which do not have a prefer system option, so they will always be built. I have added corresponding system options fory setup for many packages. You can do the same. However, this cannot be merged into alidist master because it might break the supported architectures. And usually, when we do not use the system package, there is a reason, e.g. it was misbehaving on one of the supported architectures.

**Comment by wiechula** [comment]
Hi David, thanks for the quick reply. Do you have your alidist somewhere that I can copy from what you did?
I'm not sure about the impact, but perhaps the second fix above:
```
-    if " " in platformProcessor:
+    if " " in platformProcessor or platformProcessor == "":
```
could be committed. Otherwise my platform is not detected for some reason. The first one is not really needed.

**Comment by davidrohr** [comment]
If you use the unknown architecture flag, it shouldn't matter whether it is detected.

I have the patches in my alidist fork. But i usually just force a system package without a proper check.

**Comment by wiechula** [comment]
Thanks for the hints!
