### ISSUE TITLE
rsync not required as system package

### ISSUE THREAD

**Issue by davidrohr** [alisw/alidist#2045]
Basic containers that don't have rsync installed failed in aliBuild, but this is not reported by aliDoctor

**Comment by ktf** [comment]
well rsync is only needed when you use the rsync backend for the repository. Moving to S3 will remove the need for it.

**Comment by davidrohr** [comment]
Well, but some of our alidist recipes use rsync. When you try to build O2 without rsync, the dependencies will fail.

**Comment by ktf** [comment]
ah, right. good point. Then we need to add a recipe for it and add a build_requires.

**Comment by ktf** [comment]
https://alice.its.cern.ch/jira/browse/O2-1110?filter=13341

**Comment by ktf** [comment]
I've added the recipe. We should now add it to places which use it.

**Comment by davidrohr** [comment]
Ok, I can do that later in order to share the work if you want.

**Comment by ktf** [comment]
Thanks. Probably we should do it as we change the recipes for other reasons, so that we do not trigger a rebuild just for this.

**Comment by davidrohr** [comment]
I thought about that as well, but then, will we always think of it? We can also do it once and let it rebuild over the weekend.
Or we create a dedicates pr for each package now, and then merge together when we merge something else.

**Comment by ktf** [comment]
Given I just merged lzma which was breaking FLP installations, we might as well do this? Actually I just realised that all the recipe with a module file require that because that's how we copy them in place, so we might want to do it for a few base packages (e.g. zlib, lzma, bzip2) and let the transitive closure do the rest...

**Comment by davidrohr** [comment]
+1

**Comment by ktf** [comment]
Will consider this done for now. We might add the `build_requires` in a few other place as we get to change low level packages.
