### ISSUE TITLE
DebugGUI build fails on macOS

### ISSUE THREAD

**Issue by miltalex** [alisw/alidist#2399]
The output:
```
$ aliBuild build QualityControl --defaults o2-dataflow
==> Building DebugGUI@v0.2.0
==> DebugGUI is being built (use --debug for full output): failed
```

Snapshot of the error:
```
../../src/imgui_freetype.cpp:28:10: fatal error: 'ft2build.h' file not found
#include <ft2build.h>
         ^~~~~~~~~~~~
1 error generated.
make[1]: *** [obj/debug/o/o/o/../../src/imgui_freetype.o] Error 1
make: *** [debug] Error 2
```

The full log can be found [here](https://cernbox.cern.ch/index.php/s/Fipt2pquzLfWNTs).
System Version: `macOS 10.14.6`

The files seem to be present:
```
$ locate ft2build.h
/Applications/Signal.app/Contents/Resources/app.asar.unpacked/node_modules/sharp/vendor/include/ft2build.h
/opt/X11/include/freetype2/ft2build.h
```

**Comment by ktf** [comment]
Are you installing the required externals with 

```
brew tap alisw/system-deps
brew install alisw/system-deps/o2-full-deps
```

as describe at https://alice-doc.github.io/alice-analysis-tutorial/building/prereq-macos.html#install-the-required-packages ?

**Comment by miltalex** [comment]
Yes, I installed the required externals. I even removed the previous version of `aliBuild` and re-installed as the documentation suggested. 

Version `19.6-1` of the`o2-full-deps`.

**Comment by miltalex** [comment]
Changing the path as you suggested fixed the issue.

> The error you have is because freetype seems to come from some old XQuartz installation rather than brew. Or maybe you have XQuartz in the path before brew?

Thanks.
