### ISSUE TITLE
alibuild failing on Python (Mac OS X)

### ISSUE THREAD

**Issue by aphecetche** [alisw/alidist#243]
Hi,

Trying to install on Mac OS X (Darwin 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64), I fail on Python. Attached the result of 

alibuild/aliBuild -d build O2

[failbuild.txt](https://github.com/alisw/alidist/files/169095/failbuild.txt)

and : 
> python -c 'import matplotlib; import numpy; import certifi ; import sys; sys.exit(1 if sys.version_info < (2, 7) else 0)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named certifi

using, as instructed : 

sudo pip install matplotlib
sudo pip install numpy
sudo pip install certifi

got me past those issues.

**Comment by ktf** [comment]
Can you please provide me the output of:

```
alibuild/aliBuild -d build O2
```

(notice the `-d`). What you attached is the output of 

```
13:46:51 laurent@nanpc420:~/o2/o2work> alibuild/aliBuild build O2
```

**Comment by aphecetche** [comment]
sorry. actually the attachment was with -d but with trailing lines of another try...
Here's the cleaned-up file hopefully : 
[fail.txt](https://github.com/alisw/alidist/files/169120/fail.txt)

**Comment by ktf** [comment]
Thanks. Mmm... The actual problem seems to be:

```
DEBUG:AliRoot:30093b03: Cloning into '/Users/laurent/o2/o2work/sw/SOURCES/Python/v2.7.10/1e8aa3eb11'...
DEBUG:AliRoot:30093b03: dyld: Symbol not found: __cg_png_create_info_struct
DEBUG:AliRoot:30093b03:   Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
DEBUG:AliRoot:30093b03:   Expected in: /Users/laurent/o2/o2work/sw/osx_x86-64/libpng/v1.6.18-1/lib/libPng.dylib
DEBUG:AliRoot:30093b03:  in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
DEBUG:AliRoot:30093b03:
ERROR:AliRoot:30093b03: Error while executing /Users/laurent/o2/o2work/sw/SPECS/osx_x86-64/Python/v2.7.10-1/build.sh
```

i.e. it gets confused between the `libpng` you have on the system and the one we ship to compile python. I guess the safest way there is to pick up `libpng` from the system when possible. Will try to fix that and discuss with @dberzano if he agrees.

**Comment by ktf** [comment]
I am closing this in favour of #305. Rather than trying to get an extra build of python on OSX, I think the right approach is making sure that the system python (which is guaranteed to be there) actually works fine and has all the required modules.
