### ISSUE TITLE
xjalienfs:: independent latest version

### ISSUE THREAD

**Issue by adriansev** [alisw/alidist#2478]
It would be really nice to be able to have an `latest` version that is automatically used by all users/packages.
This would ensure that everybody have the all latest ~~bugs~~features and bug fixes are available to everyone
and would increase the support capability.
ping @ktf @Atlantic777

**Comment by ktf** [comment]
This can be done, but you need to disentangle the dependency of AliRoot / O2 from JAlien-Root and handle that at AliEn / alienv level (i.e. by adding the dependency automatically).

**Comment by adriansev** [comment]
On Sep 15, 2020 10:27, Giulio Eulisse <notifications@github.com> wrote:
This can be done, but you need to disentangle the dependency of AliRoot / O2 from JAlien-Root erm, xjalienfs have no software or code relation to Jalien ROOT ...the single piece of software that can be used IF present (no matter the version) is the xrootd  python bindings (but if missing it"s fine, when trying to copy something will just warn that operation is not possible)and handle that at AliEn / alienv level (i.e. by adding the dependency automatically).

**Comment by Atlantic777** [comment]
@adriansev what do you mean by "links"?

cc @costing

**Comment by ktf** [comment]
xjalienfs is loaded as a dependency of Jalien ROOT as it's part of its modulefile. 

```bash
 49 module load BASE/1.0 ${GCC_TOOLCHAIN_REVISION:+GCC-Toolchain/$GCC_TOOLCHAIN_VERSION-$GCC_TOOLCHAIN_REVISION} \\
 50                      ROOT/${ROOT_VERSION}-${ROOT_REVISION}                                                  \\
 51                      ${XJALIENFS_REVISION:+xjalienfs/$XJALIENFS_VERSION-$XJALIENFS_REVISION}
```

If this is unneeded, you should remove the dependency and remove the bit above from the modulefile. For the record, my experience is that doing this kind of "build with one version, run with another" tricks has always side effects and it's a recipe for disaster as hidden dependencies are extremely hard to keep under control.

**Comment by adriansev** [comment]
Well, i'm complete stranger to alildist/alibuild/alienv mechanics (i'm not even sure if there are the same or have different source of information) but on matter most i was proposing to @Atlantic777 the following:

xjalienfs does not need requires of AliEn-Runtime XRootD and OpenSSL (i would assume that pyOpenSSL is part of python-modules) and XRootD is loaded by other mechanism at runtime (alienv modules? )

Jalien-ROOT for certain does not need requires of xjalienfs .. but it should require XRootD(??!!)
so i would say that alienv load xjalienfs just load alongside the xrootd (but without the hard dependency of alidist on xrootd)

and Jalien-ROOT depend of Xrootd unless xrootd is already required and component of ROOT, and at that point the xrootd should already be fully build end present including the python bindings... 

does it make sense? or given my lack of knowledge of alibuild/alidist/alienv mechanics, it is just rubbish?

**Comment by adriansev** [comment]
so, after a long and very informative discussion with @Atlantic777 i reached the conclusion that it cannot be done.

**Comment by Atlantic777** [comment]
To sum up:
  - JAliEn-ROOT doesn't have hard dependency on xjailenfs (compile time)
  - xjalienfs dependency in JAliEn-ROOT is there to trigger building of xjalienfs and auto-load the module
  - xjalienfs should be built, deployed and loaded as part of AliPhysics, AliRoot, O2 and JAliEn-ROOT dependencies and work as standalone package
  - alternative xjalienfs version can already be loaded with alienv together with other packages, i.e. by loading both AliPhysics and `xjalienfs/some-version`
  - at the moment user should know exact xjalienfs version, and this could be replaced and improved with `xjalienfs/latest`
  - there is open question how to declare an xjalienfs version as latest (automatically or manually)
  - another open question is where to create or re-link `xjalienfs/latest`, or where to inject it on auto-load, for instance in alidist recipes, alienv, alibot or manually in CVMFS
  - there is separate and maybe less relevant issue of what to do with the local builds and how to ensure recent xjalienfs version with an old version of AliPhysics locally built from an old alidist revision

I would be slightly more optimistic and say it can be done, especially if considering only limited subset of scenarios such as loading a package from CVMFS and ensuring that xjalienfs version is up to date. The question is of course how much work it requires, how to manage the tags and where is the best place for this modification from technical point of view.
