### ISSUE TITLE
AliBuild failing for FreeType on SLC6 when building AliceO2

### ISSUE THREAD

**Issue by Barthelemy** [alisw/alidist#250]
Error says : 

> libtool:   error: require no space between '-L' and '-lpng12'

Full log file : [log.txt](https://github.com/alisw/alidist/files/176367/log.txt)

**Comment by Barthelemy** [comment]
A bit more info. 

freetype.sh says 

> ./configure --prefix=$INSTALLROOT --with-zlib=$ZLIB_ROOT

First maybe it lacks a dependency on zlib ? 
Second the flag --with-zlib should say yes|no|auto according to ./configure. 
Finally, if I compile it manually it works.

**Comment by ktf** [comment]
yes. I forgot to say that I should have fixed this in  a49d0d01b1220897e57fae0be7b400aa6fdbc089. Can you pull ?

**Comment by Barthelemy** [comment]
It works !

**Comment by Barthelemy** [comment]
Sorry, I wrote too fast :(
Other things were compiled and I thought I already passed it. 
I actually have the same error. 

Should I maybe clean some directories ?

**Comment by ktf** [comment]
You mean it still fails in freetype?

**Comment by Barthelemy** [comment]
yes
