### ISSUE TITLE
Missing dependencies when building O2 on slc6

### ISSUE THREAD

**Issue by vascobarroso** [alisw/alidist#251]
While building O2 on slc6, I had to manually install the following RPMs:

- **texinfo** (missing makeinfo error while building MPFR)
- **perl-ExtUtils-Embed** (missing while building xalienfs)

**Comment by ktf** [comment]
Regarding `perl-ExtUtils-Embed`, I am afraid that we will simply have to install it by hand. I will check with @dberzano if there is any simple solution, but I doubt. Notice also that you can disable alien with `--disable AliEn-Runtime`.

Regarding `texinfo` in MPFR, #253 should take care of it.

**Comment by ktf** [comment]
BTW, why do you need MPFR? Because of GCC?

**Comment by dberzano** [comment]
Hello @ktf, our GCC is built using its own MPFR, not the external one.

**Comment by ktf** [comment]
That's what I meant. ;)

**Comment by vascobarroso** [comment]
I'm just blindly following Giulio's O2 tutorial ;)

**Comment by ktf** [comment]
Cool. :)

**Comment by ktf** [comment]
Closing this in favour of #256 .
