### ISSUE TITLE
root v6-20-02-alice7 compilation error on fedora 32/gcc10

### ISSUE THREAD

**Issue by adriansev** [alisw/alidist#2571]
Hi! It seems that root v6-20-02-alice7 is too old for gcc10 as per information from
https://root-forum.cern.ch/t/gcc10-compilation-error-std-uniq-ptr-data-root-ttaskgroup-std-default-delete-root-ttaskgroup/41860/3
is it possible to bump our version to recommended 6.20/08 ? 
full compilation logs can be found at https://cernbox.cern.ch/index.php/s/qiPJY675DTUxVkh

**Comment by ktf** [comment]
Just open a PR with the bump and we see...

**Comment by adriansev** [comment]
@ktf well, tried but https://alice.its.cern.ch/jira/browse/ALIROOT-8571  :(

**Comment by adriansev** [comment]
@ktf actually with a hint from my colleague Catalin, the compilation succeeded 
```
git diff
diff --git a/root.sh b/root.sh
index 53e11fe..42ef290 100644
--- a/root.sh
+++ b/root.sh
@@ -104,6 +104,7 @@ fi
 unset DYLD_LIBRARY_PATH
 # Standard ROOT build
 cmake $SOURCEDIR                                                                       \
+      -Dimt=OFF                                                                        \
       ${CMAKE_GENERATOR:+-G "$CMAKE_GENERATOR"}                                        \
       -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE                                             \
       -DCMAKE_INSTALL_PREFIX=$INSTALLROOT                                              \
```

maybe this could be added conditionally if gcc major version is > 10? OTOH this was solved in 6.20.08, so if aliroot compilation is fixed, the root version for user-next-root6 could be bumped to 6.20.08

**Comment by pzhristov** [comment]
Yes, this worked for me too on Ubuntu 20.04. I am not sure if we use the Root implicit multithreading in our software, may be @sawenzel and @ktf have some ideas.

**Comment by adriansev** [comment]
well, even is not used now, for sure it will be. moreover it will also be helpful for local usage as many parts make automatically use of if, see https://root.cern/manual/data_frame/#parallel-execution  .. so, i would think that is better to solve the aliroot problem than to permanently turn imt off

**Comment by pzhristov** [comment]
I think we can close this issue since now we have Root v6-20-08 in alidist/root.sh.
