### ISSUE TITLE
Cannot access alicache

### ISSUE THREAD

**Issue by ShiQiu1** [alisw/alidist#2575]
Hi experts,

it starts a few days ago that compiling aliphysics gives errors saying that it cannot access alicache. What is really the issue here and how to fix it?

`ERROR: GET https://alicache.cern.ch//TARS/slc7_x86-64/store/b2/b26492899c1e2d33f37764947e600564531ea2cb/ failed: HTTPSConnectionPool(host='alicache.cern.ch', port=443): Read timed out. (read timeout=15)`

`WARNING: defaults-release (b26492899c1e2d33f37764947e600564531ea2cb) not fetched: have you tried updating the recipes?`

`Using cached build for defaults-release`

`ERROR: GET https://alicache.cern.ch//TARS/slc7_x86-64/store/0a/0a8a547689857670a96f270b9d37691903f0c716/ failed: HTTPSConnectionPool(host='alicache.cern.ch', port=443): Read timed out. (read timeout=15)`

`WARNING: Python-modules-list (0a8a547689857670a96f270b9d37691903f0c716) not fetched: have you tried updating the recipes?`

`Using cached build for Python-modules-list`

`ERROR: GET https://alicache.cern.ch//TARS/slc7_x86-64/store/b8/b84ca4fe8f9d5d6d60e9c639f8b67afdbb12b837/ failed: HTTPSConnectionPool(host='alicache.cern.ch', port=443): Read timed out. (read timeout=15)`

I attach the log file down below
[log.txt](https://github.com/alisw/alidist/files/5464572/log.txt)

**Comment by ktf** [comment]
Should be fixed.
