### ISSUE TITLE
Use CMake 3.4.3 in O2 branch

### ISSUE THREAD

**Issue by Barthelemy** [alisw/alidist#280]
instead of 2.8

**Comment by ktf** [comment]
Initially I thought we should simply move to 3.5, however that would mean we cannot pick cmake from the system anymore on Centos 7. Maybe we should actually have a cmake3 recipe...

**Comment by dberzano** [comment]
I agree with @ktf.

**Comment by ktf** [comment]
So for this we actually decided we will use it only for the O2 branch in alidist. Which @Barthelemy do we have any "minimum" version? v3.5.1?

**Comment by Barthelemy** [comment]
I was planning on using v3.5.2. It is what I use to build aliceO2 (dev branch). I did not commit it yet.

**Comment by ktf** [comment]
3.5.2 is fine with me, but is that the minimal requirement? I mean, if someone has 3.2.x on the system (e.g. slc7, IIRC), do we still support it?

**Comment by Barthelemy** [comment]
Hmm, I don't think that we use features of 3.5 actually. I can check with 3.2.

**Comment by ktf** [comment]
Any final word on this?

**Comment by Barthelemy** [comment]
3.2 is good enough (for now) for O2.

**Comment by ktf** [comment]
Ok, I've adapted the title of the issue.

**Comment by ktf** [comment]
Actually we should reevaluate this. ROOT6 now requires CMake 3.4.3. I guess we should adapt to it accordingly.

**Comment by dberzano** [comment]
Yes, I confirm (this piece of information comes from the ROOT developers mailing list). We really have no choice and we must use 3.4.3.

**Comment by ktf** [comment]
For the record this should be fixed in by #493.
