### ISSUE TITLE
Texinfo needed to compile root on SLC6

### ISSUE THREAD

**Issue by Barthelemy** [alisw/alidist#282]
Building GCC-Toolchain@v4.9.3 it fails : 

> 
WARNING: `makeinfo' is missing on your system.  You should only need it if
         you modified a `.texi' or `.texinfo' file, or any other file
         indirectly affecting the aspect of the manual.  The spurious
         call might also be the consequence of using a buggy `make' (AIX,
         DU, IRIX).  You might want to install the `Texinfo' package or
         the `GNU make' package.  Grab either from any GNU archive site.
make[3]: *** [bfd.info] Error 1

It might be related to #251 where the same dependency was mentioned.

**Comment by ktf** [comment]
Can you attach the full log?

**Comment by Barthelemy** [comment]
> 
[log.txt](https://github.com/alisw/alidist/files/208442/log.txt)

**Comment by Barthelemy** [comment]
to test : eulisse@amorebuild1   
make sure that texinfo is not installed.

**Comment by Barthelemy** [comment]
still open

**Comment by ktf** [comment]
I managed to compile GCC using #303 on `aliamore01`. Closing this. Reopen if still problematic.
