### ISSUE TITLE
Create Jenkins build of AliceO2 for SLC6 and CC7

### ISSUE THREAD

**Issue by Barthelemy** [alisw/alidist#284]
With and without devtoolset. 

It would help converge to a working setup. 

Of course, also monitoring the builds on Ubuntu and Mac is important.

**Comment by ktf** [comment]
Yes, indeed. We have already something in build-any-ib, but it's obviously just a start. What would help a lot is if we can sit together and create a docker image which mimics exactly your configurations so that we can use that to reproduce issues.

**Comment by ktf** [comment]
Also I've just installed the [Pipeline plugin](https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Plugin), which should simplify sharing of build pipelines without stomping on each other. I am currently migrating what I've already there and will write "best practices" as I am done.

**Comment by ktf** [comment]
Initial documentation for Jenkins pipelines:

https://github.com/alisw/ali-bot/tree/master/jenkins/README

**Comment by Barthelemy** [comment]
- SLC6 bare
- SLC6 + devtoolset 3
- CC7 bare
- CC7 + devtoolset 4

**Comment by Barthelemy** [comment]
I forgot to mention that it should work for the "current" branch and the "next" branch.

**Comment by ktf** [comment]
We need more build machines... ;)

**Comment by ktf** [comment]
Blocked by alisw/docks#95 and alisw/docks#95.
