### ISSUE TITLE
random order of environment variable initialization in generated init.sh scripts

### ISSUE THREAD

**Issue by sawenzel** [alisw/alidist#288]
some `init.sh` scripts generated by AliBuild/AliDist have a random order for variable initialization.

I noticed for instance the following wrong order in GEANT4/.../init.sh :

```
export G4LEDATA="$G4INSTALL_DATA/data/G4EMLOW6.41"
export G4INSTALL_DATA="$GEANT4_ROOT/share/..."
```

**Comment by ktf** [comment]
Move to alisw/alibuild#210
