### ISSUE TITLE
wrong path for G4INSTALL_DATA

### ISSUE THREAD

**Issue by sawenzel** [alisw/alidist#289]
the location in G4INSTALL_DATA is invalid.

It should be "$GEANT4_ROOT/share/Geant4-10.1.**3**" instead if "$GEANT4_ROOT/share/Geant4-10.1.2"

**Comment by ktf** [comment]
This is fixed in `IB/v5-08/next`. One of the next releases will pick it up. Closing this.

For next time, please try to follow the guidelines at:

https://github.com/alisw/alidist/blob/IB/v5-08/prod/README.md#guidelines-for-commit-messages

for your commit messages.
