### ISSUE TITLE
Packages built because usage not allowed by policy

### ISSUE THREAD

**Issue by lbarnby** [alisw/alidist#2930]
I have a large number of packages for which aliDoctor says:
==> The following packages will be built by aliBuild because
     usage of a system version of it is not allowed or supported, by policy
[see list below]

It seems to me that something is wrong as e.g. Clang is built (with v11.0.0 instead of using v12 from Xcode)

I am using MacOS 10.15.7 (Catalina) with Xcode 12.3 and the command line tools installed
I have done : brew reinstall o2-full-deps 
after running a git command to make homebew 'unshallow' - I don't really know what this means but without it the reinstall took only a couple of seconds so I supposed it wasn't doing anything.

I believe that I have aliBuild up to date at 1.7.3
   

> ==> The following packages will be built by aliBuild because
     usage of a system version of it is not allowed or supported, by policy:
    
    - simulation 
    - GLFW 
    - lhapdf 
    - Monitoring 
    - Configuration 
    - capstone 
    - Clang 
    - FairRoot 
    - alibuild-recipe-tools 
    - defaults-release 
    - RapidJSON 
    - pythia6 
    - Common-O2 
    - googletest 
    - vgm 
    - Alice-GRID-Utils 
    - pythia 
    - UUID 
    - boost 
    - GEANT3 
    - XRootD 
    - protobuf 
    - curl 
    - Python-modules-list 
    - ApMon-CPP 
    - GMP 
    - Ppconsul 
    - MCStepLogger 
    - AliEn-Runtime 
    - GEANT4 
    - VecGeom 
    - O2-customization 
    - googlebenchmark 
    - HepMC3 
    - JAliEn-ROOT 
    - MPFR 
    - fmt 
    - DebugGUI 
    - json-c 
    - xjalienfs 
    - double-conversion 
    - arrow 
    - fastjet 
    - AliEn-CAs 
    - GEANT4_VMC 
    - FairLogger 
    - O2 
    - Python-modules 
    - libInfoLogger 
    - generators 
    - ROOT 
    - FairMQ 
    - ms_gsl 
    - KFParticle 
    - cgal 
    - re2 
    - libjalienO2 
    - asiofi 
    - Vc

**Comment by ktf** [comment]
Clang is correctly built, because the version coming with XCode does not ship with the development libraries. The rest look reasonable. They are all packages which are either ALICE specific, or they are not available from homebrew, or on which ALICE wants to have control on.
