### ISSUE TITLE
Compilation problem with FairRoot (when trying to build O2) on Mac OS 10.11.4

### ISSUE THREAD

**Issue by dstocco** [alisw/alidist#295]
Hi Giulio,
I'm trying to build O2 using:
IB/v5-08/next
and asking for a specific version of aliroot:
AliRoot@feature-muonhlt,O2

I build with command:
../../alibuild/aliBuild -z -w ../../sw --disable GEANT4,GEANT4_VMC,HepMC,simulation,fastjet,generators,DDS build O2

But, during the compilation of the dependencies, FairRoot crashes complaining about missing libHist.5.so (see attached log).

[log.txt](https://github.com/alisw/alidist/files/223762/log.txt)

Also, I noticed in the log that the GEANT3_DIR is not set by CMake...although I'm not disabling GEANT3 (at the beginning I disabled it...but thought that fairroot needed it since in the build.sh the GEANT3_DIR seems to be explicitly required, so I started again from scratch and did not disabled GEANT3 this time...).

My environment is:
Mac OS 10.11.4
with:
Xcode 7.3
clang: Apple LLVM version 7.3.0 (clang-703.0.29)
cmake 3.5.2

By the way, I disable simulation+generators first of all because in the end I only need the reconstruction part...but also because at some point I tried to enable generators, and this triggers the compilation of python which fails on Mac...

Thanks in advance,
ciao,
Diego

**Comment by ktf** [comment]
Can you try with:

```
  pushd alidist
  git fetch origin
  git checkout IB/v5-08/next
  popd
```

**Comment by dstocco** [comment]
Ciao Giulio,
I tried. It updated some software indeed, but it keeps failing at FairRoot compilation, though the error message changed (would seem like some writing permission issue):

[log.txt](https://github.com/alisw/alidist/files/244792/log.txt)

Thanks,
ciao,
Diego

**Comment by aphecetche** [comment]
Hi,

I get a similar issue : 


```
[  9%] Linking C shared library ../lib/libMbsAPI.so                                                                     │CMakeLists.txt      MbsAPI              datamatch           geane               templates
[  9%] Built target MbsAPI                                                                                              │CTestConfig.cmake   README.md           docs                generators          test
[  9%] Linking CXX shared library ../lib/libFairTools.so                                                                │CTestCustom.cmake   base                doxygen             geobase             trackbase
ld: file not found: @rpath/libCint.5.so for architecture x86_64                                                         │Dart.sh             build               eventdisplay        parbase
clang: error: linker command failed with exit code 1 (use -v to see invocation)                                         │Dart_Dispatcher.sh  cmake               examples            parmq
make[2]: *** [lib/libFairTools.15.11.0.so] Error 1                                                                      │FairBase_test.cmake config              fairmq              scripts
make[1]: *** [fairtools/CMakeFiles/FairTools.dir/all] Error 2                                                           │LICENSE             cuda                fairtools           tags
make: *** [all] Error 2
```

One thing I've noticed is that the FairRoot that's being built is "master" while I got the impression that the manual recipe for O2 was to use "dev" branch ? Do I miss something here ?

**Comment by ktf** [comment]
I moved FairRoot to use the dev branch now. Ideally we should have recipes using "master" and then if people want to develop, they should checkout the "dev" branch, but given master is so behind, at this point we should always use dev. Can you retry using the latest `IB/v5-08/next`.

**Comment by dstocco** [comment]
Ciao Giulio,
thanks, but it seems that the issue is not solved.

I first updated and built, getting this:
[log.txt](https://github.com/alisw/alidist/files/265885/log.txt)

Then I tried to force an update by removing sw/osx_x86-64/FairRoot/ and the corresponding BUILD directory, but this time got this:
[newLog.txt](https://github.com/alisw/alidist/files/265900/newLog.txt)

Any clue?
Thanks,
cheers,
Diego

**Comment by ktf** [comment]
Can you check you are actually using the latest `FairRoot`?

**Comment by dstocco** [comment]
Ciao Giulio,
actually I only have AliRoot and O2 as development packages. FairRoot is simply a dependency, so it should be handled correctly by alidist (which I updated).

Anyways, to be 100% sure I went into sw/SOURCES/FairRoot and performed git pull everywhere, but the error does not change.

Thanks,
ciao,
Diego

**Comment by ktf** [comment]
Sorry this was left behind. Do you still have the issue?

**Comment by dstocco** [comment]
Hi Giulio,
after updating the branch IB/v5-8/next, it seems that now the FairRoot compilation issue is solved.

Thanks!
Cheers,
Diego
