### ISSUE TITLE
VMC deprecation/removal

### ISSUE THREAD

**Issue by adriansev** [alisw/alidist#2974]
Hi! I noticed in https://root.cern/doc/v618/release-notes.html#deprecation-and-removal that vmc is going to be removed.
Is there any plan to add the standalone package? references:
https://github.com/vmc-project/vmc
https://vmc-project.github.io/
so, there would be a need of standalone package. If there are no plans, i can do it. what would be a good recipe to take as example?

**Comment by ihrivnac** [comment]
Hi @adriansev,
Indeed, there is agreement with the ROOT project that vmc will be removed, so we will need to switch to VMC stand-alone. 
You can follow the recipe of geant4_vmc.sh, as its cmake configuration files are defined in the same way as those in vmc, but remove the dependencies on GEANT4 and vgm (the only dependence of vmc is on ROOT). Then, you need to search for ENABLE_VMC: "ON" in the defaults recipes and change them to ENABLE_VMC: "OFF".

**Comment by adriansev** [comment]
this was already solved, so i will close this
