### ISSUE TITLE
PROOF does not compile on Ubuntu

### ISSUE THREAD

**Issue by ktf** [alisw/alidist#304]
Chiara's configuration fails with:

```
DEBUG:AliPhysics:0: stressProof.cxx:135:28: fatal error: proof/getProof.C: No such file or directory
DEBUG:AliPhysics:0:  #include "proof/getProof.C"
DEBUG:AliPhysics:0:                             ^
DEBUG:AliPhysics:0: compilation terminated.
DEBUG:AliPhysics:0: Makefile:830: recipe for target 'stressProof.o' failed
DEBUG:AliPhysics:0: make: *** [stressProof.o] Error 1
DEBUG:AliPhysics:0: make: *** Waiting for unfinished jobs....
DEBUG:AliPhysics:0:
ERROR:AliPhysics:0: Error while executing /data/alisw/sw/SPECS/ubuntu1504_x86-64/ROOT/v5-34-30-alice-1/build.sh
ERROR:AliPhysics:0: Log can be found in /data/alisw/sw/BUILD/ROOT-latest/log
```

waiting for her to provide the list of packages installed on her system.

**Comment by chiarabianchin** [comment]
Ciao Giulio,
I attach the list of packages installed in my computer.
Thanks for the help.
Chiara
[packages.txt](https://github.com/alisw/alidist/files/227316/packages.txt)

**Comment by ktf** [comment]
Ciao. The problem is most likely related to the old alien-env.sh in your `.bashrc`.
@dberzano will sent a explanatory email "urbi et orbi" soon.

**Comment by dberzano** [comment]
Hello @chiarabianchin, yes that's correct. Other than an email we are updating the documentation to this respect.

**Comment by chiarabianchin** [comment]
Ciao Giulio, Dario,
thanks for the feedback. I understood it was possible to keep both build systems in parallel. I'll wait for your detailed explanation!
Thank you,
Chiara

**Comment by dberzano** [comment]
Hello @chiarabianchin, it **is** possible, but in order to be able to "switch" between them you must not load `alice-env.sh` automatically in your `.bashrc`, as this is going to affect whatever uses `.bashrc`, including `aliBuild` itself.

Just remove the reference from `.bashrc` and load `alice-env.sh` manually when needed, and do not use `aliBuild` in the `alice-env.sh` environment.

**Comment by Barthelemy** [comment]
Hi, 

For me the issue arise when I call thisroot.sh script of an already installed ROOT. 
It is a common use case I think : you have ROOT installed manually somewhere and you call thisroot.sh in your bashrc. Later you use alibuild for something else. 

Maybe the environment should be cleaned before build ROOT in alibuild ? 

Cheers,
Barth

**Comment by ktf** [comment]
Agreed ROOT build should be more robust when building. For example we should unset ROOTSYS during the build phase (#338).

**Comment by chiarabianchin** [comment]
Hello,
my problem was solved, I successfully compiled all.
Thanks,
Chiara

**Comment by ktf** [comment]
#346 should properly fix the problem.
