### ISSUE TITLE
Add zeromq to AliRoot builds

### ISSUE THREAD

**Issue by ktf** [alisw/alidist#310]

**Comment by ktf** [comment]
Maybe this should actually be discussed as it will affect CVMFS deployments.

**Comment by ktf** [comment]
This we should probably discuss with the rest of offline, as it has implications with the Grid installations which would start to depend on FairMQ and another bunch of externals.

**Comment by dberzano** [comment]
@ktf: this was as a matter of fact discussed during one of the offline weekly meetings when you were away, and the decision was to not do it.
