### ISSUE TITLE
AliPhysics/etc/modulesfiles is missing when the build process is interrupted

### ISSUE THREAD

**Issue by hcab14** [alisw/alidist#342]
When the build process of AliPhysics is interrupted, etc/modulesfiles is missing and is not regenerated in the next build.

This can be fixed by removing AliPhysics/log, so it would be good to remove AliPhysics/log whenever AliPhysics is build.

Best regards
Christoph

**Comment by dberzano** [comment]
This issue pertains to alibuild and it was solved, see alisw/alibuild#174.
