### ISSUE TITLE
Create a recipe for AliDPG

### ISSUE THREAD

**Issue by ktf** [alisw/alidist#363]

**Comment by dberzano** [comment]
@chiarazampolli: the package is called AliDPG. On the Grid you will find something like:

```
VO_ALICE@AliDPG::v20160425-1
```

(versioning conventions need to be discussed.)

To have the package available, in your JDL you will have something like:

```
Packages = {
  "VO_ALICE@AliPhysics::v5-08-09-02-1",
  "VO_ALICE@AliDPG::v20160425-1"
}
```

The package does not contain any built software. Once the environment is loaded (both locally with `alienv` and as a Grid job) you will find all your macros under `$ALIDPG_ROOT`.

For instance you might do:

```
gROOT->LoadMacro("$ALIDPG_ROOT/MC/DetectorConfig.C");
```

or something like that. You will also find the following two variables which might be of some use:

* `ALIDPG_VERSION`: this contains the software version, _i.e._ the tag name without the build number. In the given package example that'd be `v20160425`.
* `ALIDPG_RELEASE`: software version _including_ the build number, _i.e._ `v20160425-1`.

**Comment by chiarazampolli** [comment]
Ciao @dberzano,

Many thanks, this is perfect (at least for now :) ).

Cheers,

Chiarar
