### ISSUE TITLE
Add checks for missing packages

### ISSUE THREAD

**Issue by dberzano** [alisw/alidist#367]
See [here](https://git.cta.if.ufrgs.br/snippets/6).

**Comment by ktf** [comment]
Notice that most of the work is actually already done in next. These should be implemented using the new `system_requirements` feature of alibuild. I also do not understand the comment on alidist/gsl. Obviously our copy of GSL should not depend on the system one, which is how i interpret the comment. What is the actual meaning?

**Comment by dberzano** [comment]
As a matter of fact I see that everything has been already taken care of by #239.

`libgsl0-dev` has to be verified, I think the user got that wrong somehow.... you should not need to install the system one.

**Comment by ktf** [comment]
Closing this one. Reopen if `libgsl0-dev` actually pops up somewhere as missing dependency.
