### ISSUE TITLE
installation of AliRoot test directory

### ISSUE THREAD

**Issue by qgp** [alisw/alidist#368]
At the moment $ALICE_ROOT/test is installed by an explicit rsync in the recipe, not through cmake. Why?

Consequently, test never gets updated when rebuilding in the build directory during local developments.

I am preparing to add the load_library testing also to AilRoot, and stumbled over this strange treatment of test/. Can we switch to install test properly using cmake?

**Comment by dberzano** [comment]
Agreed. Note that this requires changing the `aliroot.sh` build recipe too.

**Comment by qgp** [comment]
As discussed with @dberzano: @dberzano takes care of the recipe, I will take care of the cmake installation. However, we will need to validate that we install everything we need.

**Comment by qgp** [comment]
Ok, I now have a (stupid) cmake implementation to reproduce the installation of test/ as we have it now with rsync in the build recipe. @dberzano: let me know when the recipe is modified so that I can push this.

**Comment by qgp** [comment]
@dberzano: The new alidist release still contains the rsync for test. When do you expect that we can move ahead with the cmake installation of test?

In fact we could even do it with the rsync still in place, it would just add additional (useless) stuff but not do any harm. Or do you see any problem?

**Comment by qgp** [comment]
@dberzano: any news? shall I just commit the cmake installation?

**Comment by ktf** [comment]
What is the status on this? Was it fixed in the CMake installation in the end?

**Comment by qgp** [comment]
I was waiting for the ok to commit the fix because @dberzano said he first wanted to update the recipe to only do the rsync for test/ if the directory was not make-installed before. If you give me the green light, I can do the commit.

**Comment by ktf** [comment]
Ok, I'll let him to comment then.

**Comment by ktf** [comment]
Done.

```
  Packages = {
    "VO_ALICE@POWHEG::r3178-3"
  }

  Packages = {
    "VO_ALICE@lhapdf5::v5.9.1-5"
  }

```

**Comment by qgp** [comment]
I think this was the wrong issue (#368 instead of #386) ;-)

This one has not been solved and had nothing to do with POWHEG, can you reopen it, please?

**Comment by qgp** [comment]
ping @dberzano: we are waiting for your comment ...

if you give me green light I can go ahead and commit the installation of test/ and then also the library_loading check for AliRoot

**Comment by dberzano** [comment]
Hello @qgp, for the next AliRoot release (v5-08-14) I will update the build recipe and the CMake too. See [ALIROOT-6753](https://alice.its.cern.ch/jira/browse/ALIROOT-6753).

**Comment by dberzano** [comment]
For the record the issue has been solved on the AliRoot side (master). This makes the `rsync` in the recipe redundant. We'll make a PR to smooth it out.
