### ISSUE TITLE
capitalization errors in dependencies lead to inconsistent behaviour

### ISSUE THREAD

**Issue by qgp** [alisw/alidist#372]
A dependency listed in `require:` is pulled in correctly but the depending package does not get built. See e.g. the change required for pythia6 in #278.

**Comment by dberzano** [comment]
Hello @qgp, yes, we are aware of that. I am closing this issue, and have opened a new one in alibuild, where it pertains.

**Comment by qgp** [comment]
@dberzano: ok, I had put it here because there was at least the bug for pythia6. So, we should check the recipes.
