### ISSUE TITLE
Boost detection on OS X

### ISSUE THREAD

**Issue by raymondEhlers** [alisw/alidist#377]
Hi,

This is perhaps already know and intentional (in which case, please ignore), but the system copy of Boost is not being picked up on OS X, at least when it is installed via Homebrew. It seems this is caused by the system check explicitly looking for `boost_thread`, which is not built on OS X. Most other boost libraries are built with and without the -mt label, but `boost_thread` is not (ie only `boost_thread-mt` is built), for the reasons for which are not clear to me.

This information seems to be confirmed by https://stackoverflow.com/a/15040393 (the answer as well as in the comment) and https://stackoverflow.com/a/3031843 (although this is Ubuntu, it seems to be related. It seems that on Ubuntu these libraries are just symlinked).

It seems that checking for `boost_thread-mt` on OS X would resolve this, but I'm uncertain whether such a change would break other packages. Either way, I wanted to bring it to the attention of the developers in case they are not aware.

Best regards,
Raymond

**Comment by ktf** [comment]
This is indeed a known issue and the -mt is looked up on purpose due to an (old) bug in fairroot. Since I think fairroot got fixed we should probably adapt the test as well.

**Comment by raymondEhlers** [comment]
Okay, great - I'm glad to hear that this was known. If the bug is resolved, then it seems like adapting the test would be a good way to avoid extra building if it is not needed. Thanks for the explanation!

**Comment by ktf** [comment]
Should be fixed in #394. Closing this.

**Comment by ktf** [comment]
Notice that this is done in the `IB/v5-08/next` branch of alidist, so make sure you switch to it if you want to try it out.

**Comment by raymondEhlers** [comment]
Great, thank you!
