### ISSUE TITLE
aliphysics compilation error (db related?)

### ISSUE THREAD

**Issue by pkurash** [alisw/alidist#385]
hello, I encountered the following error on the terminal stage of compiling aliphysics (do I luck some prerequisites for the installation?):

```
            from /home/kurash/sw/BUILD/265ebcab1f9940c65fbb522a8a4db0021b8e31ff/ROOT/sql/pgsql/G__PgSQL.cxx:17:
```

/home/kurash/sw/BUILD/265ebcab1f9940c65fbb522a8a4db0021b8e31ff/ROOT/include/TPgSQLStatement.h:27:48: fatal error: pg_config.h: No such file or directory
 #include <pg_config.h> // to get PG_VERSION_NUM
                                                ^
compilation terminated.
sql/pgsql/CMakeFiles/RPgSQL.dir/build.make:74: recipe for target 'sql/pgsql/CMakeFiles/RPgSQL.dir/G__PgSQL.cxx.o' failed
make[2]: **\* [sql/pgsql/CMakeFiles/RPgSQL.dir/G__PgSQL.cxx.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
[ 49%] Generating G__SQLite.cxx, G__SQLite.h
[ 49%] Building CXX object sql/mysql/CMakeFiles/RMySQL.dir/src/TMySQLRow.cxx.o
Scanning dependencies of target RSQLite
[ 49%] Building CXX object sql/mysql/CMakeFiles/RMySQL.dir/src/TMySQLStatement.cxx.o
[ 49%] Building CXX object sql/sqlite/CMakeFiles/RSQLite.dir/G__SQLite.cxx.o
[ 49%] Building CXX object sql/sqlite/CMakeFiles/RSQLite.dir/src/TSQLiteRow.cxx.o
CMakeFiles/Makefile2:12787: recipe for target 'sql/pgsql/CMakeFiles/RPgSQL.dir/all' failed
make[1]: **\* [sql/pgsql/CMakeFiles/RPgSQL.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
[ 49%] Building CXX object sql/sqlite/CMakeFiles/RSQLite.dir/src/TSQLiteResult.cxx.o
[ 49%] Linking CXX shared library ../../lib/libRODBC.so
[ 49%] Building CXX object sql/mysql/CMakeFiles/RMySQL.dir/src/TMySQLServer.cxx.o
[ 49%] Built target RODBC
[ 49%] Building CXX object sql/mysql/CMakeFiles/RMySQL.dir/src/TMySQLResult.cxx.o
[ 49%] Building CXX object sql/sqlite/CMakeFiles/RSQLite.dir/src/TSQLiteServer.cxx.o
[ 49%] Building CXX object sql/sqlite/CMakeFiles/RSQLite.dir/src/TSQLiteStatement.cxx.o
[ 49%] Linking CXX shared library ../../lib/libRMySQL.so
[ 49%] Linking CXX shared library ../../lib/libRSQLite.so
[ 49%] Built target RMySQL
[ 49%] Built target RSQLite
[ 49%] Linking CXX shared library ../../lib/libProof.so
[ 49%] Built target Proof
Makefile:149: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by ktf** [comment]
Looks like you have postgres on your system and root fails to compile 
it. Can you confirm? Can you uninstall it?

**Comment by pkurash** [comment]
hello, yes, I have had postgres, other components (e.g. Geant 4) also were not installed, system just abandoned them and went to the next member of the package list.

 I removed it and started compillation again. This time it went a bit further but it again failed at Geant 4 stage:

DEBUG:AliPhysics:67438165: /home/kurash/sw/slc7_x86-64/GEANT4/v4.10.01.p03-2/lib/libG4clhep.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
DEBUG:AliPhysics:67438165: /home/kurash/sw/slc7_x86-64/GEANT4/v4.10.01.p03-2/lib/libG4clhep.so: undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::operator>><char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBCXX_3.4.21'
DEBUG:AliPhysics:67438165: /home/kurash/sw/slc7_x86-64/GEANT4/v4.10.01.p03-2/lib/libG4clhep.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const@GLIBCXX_3.4.21'
DEBUG:AliPhysics:67438165: /home/kurash/sw/slc7_x86-64/GEANT4/v4.10.01.p03-2/lib/libG4clhep.so: undefined reference to `vtable for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
DEBUG:AliPhysics:67438165: /home/kurash/sw/slc7_x86-64/GEANT4/v4.10.01.p03-2/lib/libG4clhep.so: undefined reference to `VTT for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
DEBUG:AliPhysics:67438165: /home/kurash/sw/slc7_x86-64/GEANT4/v4.10.01.p03-2/lib/libG4clhep.so: undefined reference to `std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_istringstream()@GLIBCXX_3.4.21'
DEBUG:AliPhysics:67438165: /home/kurash/sw/slc7_x86-64/GEANT4/v4.10.01.p03-2/lib/libG4clhep.so: undefined reference to `VTT for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
DEBUG:AliPhysics:67438165: /home/kurash/sw/slc7_x86-64/GEANT4/v4.10.01.p03-2/lib/libG4clhep.so: undefined reference to `vtable for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
DEBUG:AliPhysics:67438165: /home/kurash/sw/slc7_x86-64/GEANT4/v4.10.01.p03-2/lib/libG4clhep.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21'
DEBUG:AliPhysics:67438165: /home/kurash/sw/slc7_x86-64/GEANT4/v4.10.01.p03-2/lib/libG4clhep.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_sync(char*, unsigned long, unsigned long)@GLIBCXX_3.4.21'
DEBUG:AliPhysics:67438165: /home/kurash/sw/slc7_x86-64/GEANT4/v4.10.01.p03-2/lib/libG4clhep.so: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream()@GLIBCXX_3.4.21'
DEBUG:AliPhysics:67438165: /home/kurash/sw/slc7_x86-64/GEANT4/v4.10.01.p03-2/lib/libG4clhep.so: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
DEBUG:AliPhysics:67438165: collect2: error: ld returned 1 exit status
DEBUG:AliPhysics:67438165: examples/E04/CMakeFiles/exampleE04.dir/build.make:98: recipe for target 'examples/E04/exampleE04' failed
DEBUG:AliPhysics:67438165: make[2]: *** [examples/E04/exampleE04] Error 1
DEBUG:AliPhysics:67438165: CMakeFiles/Makefile2:619: recipe for target 'examples/E04/CMakeFiles/exampleE04.dir/all' failed
DEBUG:AliPhysics:67438165: make[1]: *** [examples/E04/CMakeFiles/exampleE04.dir/all] Error 2
DEBUG:AliPhysics:67438165: make[1]: *** Waiting for unfinished jobs....
DEBUG:AliPhysics:67438165: [ 83%] Linking CXX shared library libGeant4GM.so
DEBUG:AliPhysics:67438165: [ 83%] Built target Geant4GM
DEBUG:AliPhysics:67438165: Makefile:127: recipe for target 'all' failed
DEBUG:AliPhysics:67438165: make: *** [all] Error 2
DEBUG:AliPhysics:67438165: 
ERROR:AliPhysics:67438165: Error while executing /home/kurash/sw/SPECS/slc7_x86-64/vgm/4.3-1/build.sh
ERROR:AliPhysics:67438165: Log can be found in /home/kurash/sw/BUILD/vgm-latest/log

**Comment by ktf** [comment]
Do you have gcc 5 installed on your system? Can you get rid of it as 
well and use the default compiler on slc7?

**Comment by pkurash** [comment]
yes, I had gcc 5-3

have I switch to another version of gcc? I already tried 4.9.3 and 4.8.4 but there are still errors. Or have I to switch to clang?

p.s. my linux is not scientific, I try to build with -a slc7_x86-64 since the "unknown architecture" delivers error at earlier stage.

 the output of gcc-config -l is:

 [1] x86_64-pc-linux-gnu-4.7.3
 [2] x86_64-pc-linux-gnu-4.7.3-hardenednopie
 [3] x86_64-pc-linux-gnu-4.7.3-hardenednopiessp
 [4] x86_64-pc-linux-gnu-4.7.3-hardenednossp
 [5] x86_64-pc-linux-gnu-4.7.3-vanilla
 [6] x86_64-pc-linux-gnu-4.8.4
 [7] x86_64-pc-linux-gnu-4.8.4-hardenednopie
 [8] x86_64-pc-linux-gnu-4.8.4-hardenednopiessp
 [9] x86_64-pc-linux-gnu-4.8.4-hardenednossp
 [10] x86_64-pc-linux-gnu-4.8.4-vanilla
 [11] x86_64-pc-linux-gnu-4.9.3 *
 [12] x86_64-pc-linux-gnu-4.9.3-hardenednopie
 [13] x86_64-pc-linux-gnu-4.9.3-hardenednopiessp
 [14] x86_64-pc-linux-gnu-4.9.3-hardenednossp
 [15] x86_64-pc-linux-gnu-4.9.3-vanilla
 [16] x86_64-pc-linux-gnu-5.3.0
