### ISSUE TITLE
Rebuild POWHEG/LHAPDF

### ISSUE THREAD

**Issue by qgp** [alisw/alidist#387]
We would need a rebuild of POWHEG and LHAPDF.

For POWHEG, the sources have been updated in branch next/alice/r3178 (not yet in alice/r3178).

For LHAPDF, there is a pending PR #386 to add EPS09 NLO PDFs.

**Comment by qgp** [comment]
@alisw/pwgmm

**Comment by qgp** [comment]
Added two more patches by @dstocco (one bugfix, one feature extension) to next/alice/r3178.

@ktf, @dberzano: The request for rebuilding POWHEG/LHAPDF remains, now using the latest version of the code in next/alice/r3178.

**Comment by qgp** [comment]
any news on this?

**Comment by qgp** [comment]
@dberzano, @ktf: could someone please comment here?

Maybe we also need to keep track of these requests somewhere else?

**Comment by ktf** [comment]
Sorry, I missed this one. Will try to get to it ASAP.

**Comment by ktf** [comment]
Was this discussed and agreed in the offline planning meeting, by the way?

**Comment by qgp** [comment]
@ktf: No, since this is still under testing, we had not discussed it. Anyway, I had asked Predrag already about discussing PWG-MM related things in the computing board, I can bring it up on Monday.

In any case, we have to find a way how to keep track of these things, if it remains for ~30 days undiscovered on github, it's not good and we need to think of something else.

Thanks for taking it up now. Cheers,
   Jochen

**Comment by qgp** [comment]
NB: this still requires the changes from #386 to be merged from next to prod.

**Comment by ktf** [comment]
Done.

```
  Packages = {
    "VO_ALICE@POWHEG::r3178-3"
  }

  Packages = {
    "VO_ALICE@lhapdf5::v5.9.1-5"
  }
```
