### ISSUE TITLE
Check certificate expiration date

### ISSUE THREAD

**Issue by mpuccio** [alisw/alidist#395]
Ciao @dberzano,

`alice-env.sh` was checking the certificate expiration date giving useful alert messages.
Would it be possible to implement something similar, maybe directly in alien-token-init?

Thanks,
Max

**Comment by aaniin** [comment]
Hi @mpuccio !

You requested to check the validity of the grid certificate some time ago. I translated Dario's alice-env.sh check into tcl. Can you try out #808 please? 

Cheers,
Hans

**Comment by dberzano** [comment]
So, after what was said in #808: why not having it in `alien-token-init`, which is quite simply a shell script?

**Comment by aaniin** [comment]
Hi @dberzano , @mpuccio ,

I wonder whether one needs the check at all. I get enough emails from CERN about my certificate expiration. There's one at -30days, -7days, and -1day. 

Cheers,
Hans

**Comment by dberzano** [comment]
The reason why I put the check in the shell back in the old days was that updating the certificate also implies a step for having it converted to PEM and under `~/.globus`, possibly on multiple machines. Anyway I have added the check to `alien-token-init`.
