### ISSUE TITLE
Error building O2 on Mac : Python-modules

### ISSUE THREAD

**Issue by Barthelemy** [alisw/alidist#402]
>  ==> aliBuild can take the following packages from the system and will not build them:
>       CMake, Python, libxml2, zlib, ZeroMQ, boost
> 
> ==> The following packages cannot be taken from the system and will be built:
>       Python-modules, SWIG, autotools, GSL, yaml-cpp
> 
> ==> Packages will be built in the following order:
>      - defaults-release
>      - AliEn-CAs
>      - Python-modules
>      - autotools
>      - pythia6
>      - HepMC
>      - DDS
>      - yaml-cpp
>      - GEANT4
>      - UUID
>      - SWIG
>      - nanomsg
>      - gSOAP
>      - ApMon-CPP
>      - GSL
>      - lhapdf
>      - MonALISA-gSOAP-client
>      - pythia
>      - XRootD
>      - generators
>      - xalienfs
>      - AliEn-Runtime
>      - ROOT
>      - vgm
>      - GEANT3
>      - GEANT4_VMC
>      - AliRoot
>      - simulation
>      - FairRoot
>      - O2 (development package)
> 
> ==> Git status for development package O2
> On branch master
> Your branch is up-to-date with 'origin/master'.
> nothing to commit, working directory clean

**Comment by Barthelemy** [comment]
[log.txt](https://github.com/alisw/alidist/files/272103/log.txt)

**Comment by Barthelemy** [comment]
Python installed by system and brew. Python.h present : 

> $ locate Python.h
> /System/Library/Frameworks/Python.framework/Versions/2.6/include/python2.6/Python.h
> /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/Python.h
> /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/include/python2.7/Python.h
> /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7/Python.h
> /usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/include/python2.7/Python.h
> /usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/include/python2.7/Python.h

**Comment by ktf** [comment]
As discussed elsewhere, the problem is that brew python does not provide a standard path for Python.h, hence things fall apart. One workaround should be to uninstall the brew python, the other is to install numpy, matplotlib, certifi using pip from the system (either from brew or the official one).
