### ISSUE TITLE
Error building O2 on Mac : ROOT6 expects SSL

### ISSUE THREAD

**Issue by Barthelemy** [alisw/alidist#404]
ROOT6 does not build on my mac. 

During the configure, ssl is not found and then there is a test to make sure that root will be built with ssl. 

What is strange is that running "alibuild/aliBuild build openssl" correctly sees it (openssl of the system). 

Maybe some env variables could be set to force cmake to see it ?

**Comment by Barthelemy** [comment]
export OPENSSL_ROOT_DIR=/usr/local/opt/openssl/
did the trick

**Comment by ktf** [comment]
Isn't OPENSSL_ROOT_DIR supposed to be set by cmake once OPENSSL is correctly found?

**Comment by Barthelemy** [comment]
I would expect it, yes. It seems that the CMake script that looks for openssl is not very good.
