### ISSUE TITLE
Error building inside docker-ubuntu-16.04: test that g++ is installed

### ISSUE THREAD

**Issue by sbinet** [alisw/alidist#405]
trying to issue:

```sh
$> ./alibuild/aliBuild build AliRoot
```

in a fresh docker container `ubuntu:16.04` will return:
```
root@c9e650bf1416:/opt/alice# ./alibuild/aliBuild -d build AliRoot
DEBUG: Building for architecture ubuntu1604_x86-64
DEBUG: Number of parallel builds: 4
DEBUG: Using aliBuild from alibuild@27a9bb8ba985f6d8b4e353169a0c8288ebf54c46 recipes in alidist@17aab49f0373df33e6b3408fa3d05f2f00c550a4
ERROR: Please install libperl and perl-ExtUtils-Embed development package on your system
```

that's because the container is missing `g++` and `gcc`:
```sh
root@c9e650bf1416:/opt/alice# printf "#include <EXTERN.h>\n#include <perl.h>\n" | gcc -xc++ -I`perl -MConfig -e 'print $Config{archlib}'`/CORE - -c -o /dev/null && perl -MExtUtils::Embed -e 1
gcc: error trying to exec 'cc1plus': execvp: No such file or directory

```

one should first test that `gcc` and `g++` are indeed available before testing for `perl`.

**Comment by ktf** [comment]
This is actually a bit complicated, because we do not require gcc to be installed, since people might be downloading packages from a remote store, so forcing them to install gcc just to check perl is there is probably a bit too much. I've to think what is the best way of handing this.

**Comment by sbinet** [comment]
Ok. As a (relatively) newcomer, and as a side note, it was also a bit interesting to dig out the issue and error message was coming from alidist, and not from alibuild (which was the script I was running)
Well, just an FYI :)

**Comment by ktf** [comment]
I am not sure I understand your comment about the error message coming from alidist, rather than alibuild. What do you mean?

**Comment by sbinet** [comment]
the error message is being displayed by `alibuild` but the error is coming from `alidist`.
and, as a first time user with no (deep nor otherwise) understanding of all the moving pieces, it wasn't completely trivial to locate the original culprit (`git grep alibuild libperl` returned nothing.)

I know it is a delicate balance to reach between "too much info and overwhelm the user" and "too little info".

**Comment by ktf** [comment]
Yeah. Basically you have to remember that aliBuild is just a driver script, an all the external related logic comes from alidist. BTW, if you update to the master (or 1.3.0.rc3) you should have a much improved aliDoctor, which should have given you proper message.

Just do `aliDoctor AliRoot` (for example) and it should give you all the information you need debug these kind of problems. Let me know how that goes.

**Comment by ktf** [comment]
I assume you are happy. If not, please reopen.
