### ISSUE TITLE
Error building O2 on Mac : FairRoot and boost

### ISSUE THREAD

**Issue by Barthelemy** [alisw/alidist#407]
FairRoot fails to build : 

> [  9%] Linking CXX shared library ../../lib/libfairmq_logger.dylib
> ld: library not found for -lboost_thread
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [lib/libfairmq_logger.15.11.0.dylib] Error 1
> make[1]: *** [fairmq/logger/CMakeFiles/fairmq_logger.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....

I have boost installed in /usr/local/opt/boost (brew) where sits libboost_thread-mt.dylib. There is no libboost_thread.dylib (which kind of make sense). 

Workaround : symlink to have a non-mt library. (under test)

Fix : it should take the correct library

**Comment by ktf** [comment]
Looks like I did not update correctly FairRoot to pick up the dev branch (which has the fix already). #409 should have the fix. Reopen if still broken.
