### ISSUE TITLE
Build fails after incomplete tar ball write 

### ISSUE THREAD

**Issue by matthiasrichter** [alisw/alidist#424]
Root 6 needs lots of memory for the interpreter build. Somehow the tar file written to the store got corrupted because the disc was full. Build is now trying to unpack the tar ball. This fails and so does the build. Could only resolve the situation by deleting the file manually. I suggest to handle this condition silently or with a warning by deleting the corrupted tar ball and then compiling from scratch.

**Comment by dberzano** [comment]
Hi, could you please reopen the issue in alibuild? This does not pertain here :-)

**Comment by matthiasrichter** [comment]
correct ;-)
