### ISSUE TITLE
Cannot connect to proof from Mac

### ISSUE THREAD

**Issue by dstocco** [alisw/alidist#432]
Hi all,
since a while, I have problems connecting to a proof server from Mac.
If I do:
TProof::Open("dstocco@nansafmaster2")

I get the error message at the end of this mail.
On the other hand, everything works as expected under linux SL6.

Unfortunately I have no way to provide a reproducible example (access on the server is restricted)...however, my hope is that the first line of the error message (pointing to an issue with libXrdSec.so) is enough to ring you a bell....

If you have any hints/suggestions/tests proposals, they are more then welcome....
Thanks in advance,
Ciao,
Diego

Plugin dlopen(libXrdSec.so, 256): image not found (null) libXrdSec.so

 *** Break *** segmentation violation
 Generating stack trace...
 0x00000001116e3e16 in XrdProofConn::GetAccessToSrv(XrdClientPhyConnection*) (in libXrdProofd.5.so) + 918
 0x00000001116e0a5a in XrdProofConn::Connect(int) (in libXrdProofd.5.so) + 474
 0x00000001116e083c in XrdProofConn::Init(char const*, int) (in libXrdProofd.5.so) + 204
 0x00000001116e054e in XrdProofConn::XrdProofConn(char const*, char, int, char, XrdClientAbsUnsolMsgHandler*, char const*) (in libXrdProofd.5.so) + 366
 0x000000011156ffd0 in TXSocket::TXSocket(char const*, char, int, char, char const*, int, TXHandler*) (in libProofx.so) + 1104
 0x0000000111562352 in TXProofMgr::Init(int) (in libProofx.so) + 130
 0x0000000111562199 in GetTXProofMgr(char const*, int, char const*) (in libProofx.so) + 89
 0x00000001113daf0c in TProofMgr::Create(char const*, int, char const*, bool) (in libProof.so) + 844
 0x00000001113c382f in TProof::Open(char const*, char const*, char const*, int) (in libProof.so) + 1471
 0x000000011134883c in G__G__Proof_239_0_322(G__value*, char const*, G__param*, int) (in libProof.so) + 588
 0x000000010bb5681f in Cint::G__ExceptionWrapper(int (*)(G__value*, char const*, G__param*, int), G__value*, char*, G__param*, int) (in libCint.5.so) + 63
 0x000000010bbf147b in G__execute_call (in libCint.5.so) + 75
 0x000000010bbf18c2 in G__call_cppfunc (in libCint.5.so) + 818
 0x000000010bbc5d36 in G__interpret_func (in libCint.5.so) + 5142
 0x000000010bbb4103 in G__getfunction (in libCint.5.so) + 5763
 0x000000010bba8099 in G__getitem (in libCint.5.so) + 521
 0x000000010bba3a89 in G__getexpr (in libCint.5.so) + 30649
 0x000000010bc221cf in G__exec_statement (in libCint.5.so) + 23695
 0x000000010bb8a78c in G__exec_tempfile_core(char const*, __sFILE*) (in libCint.5.so) + 1100
 0x000000010bb8a336 in G__exec_tempfile_fp (in libCint.5.so) + 22
 0x000000010bc2d0b6 in G__process_cmd (in libCint.5.so) + 7254
 0x000000010b521f0c in TCint::ProcessLine(char const*, TInterpreter::EErrorCode*) (in libCore.5.so) + 876
 0x000000010b1c7a70 in TRint::HandleTermInput() (in libRint.5.so) + 656
 0x000000010b5595e7 in TUnixSystem::CheckDescriptors() (in libCore.5.so) + 327
 0x000000010b5621cb in TMacOSXSystem::DispatchOneEvent(bool) (in libCore.5.so) + 395
 0x000000010b5c9d6a in TSystem::InnerLoop() (in libCore.5.so) + 26
 0x000000010b5c9bbe in TSystem::Run() (in libCore.5.so) + 206
 0x000000010b56dc04 in TApplication::Run(bool) (in libCore.5.so) + 36
 0x000000010b1c73c2 in TRint::Run(bool) (in libRint.5.so) + 1442
 0x000000010ae9debf in main (in root.exe) + 79
 0x00007fff98f175ad in start (in libdyld.dylib) + 1
 0x0000000000000003 in <unknown function>

**Comment by dberzano** [comment]
Hello @dstocco, this problem does not pertain to alidist. Please contact the ROOT developers, or open a JIRA... closing.

**Comment by dstocco** [comment]
Dear @dberzano 
I installed root v5-34-30 using your good old script:
bash <(curl -fsSL http://alien.cern.ch/alice-installer) --root
I run the command:
TProof::Open("dstocco@nansafmaster2")
and it works perfectly.

Seems I have the problem only when installing root with the supported alibuild.
Can you please have a look?
Thanks,
ciao,
Diego
