### ISSUE TITLE
Version check for ZeroMQ

### ISSUE THREAD

**Issue by matthiasrichter** [alisw/alidist#439]
Just to not to forget about it: In FairRoot dev the required ZeroMQ version was set to 4.1.3
That should go into the recipe as well.

**Comment by ktf** [comment]
The problem I see is that ZeroMQ does not seem to tag their repository. Do you know which commit is this?

**Comment by matthiasrichter** [comment]
ok, I will try to find out. However, if we install from the repository it does not matter, we can simply install the latest which is probably > 4.1.3.
The more important check I was referring to is the version check for a ZMQ package found in the system. This can be implemented independently.

**Comment by ktf** [comment]
I've fixed the version to 4.1.5. To do so I actually had to import the sources from the tarball in our own repository https://github.com/alisw/zeromq/tree/v4.1.5 . Closing this. Reopen if not ok.
