### ISSUE TITLE
Fix ROOT for gcc 5.3 on Ubuntu 16.04

### ISSUE THREAD

**Issue by ktf** [alisw/alidist#442]
Looks like we need a few fixes. In particular I noticed we need to change `isnan` -> `std::isnan` and similar things. Boris also reported:

- https://root.cern.ch/phpBB3/viewtopic.php?t=21804
- https://root.cern.ch/phpBB3/viewtopic.php?f=3&t=21803

**Comment by dberzano** [comment]
Fixed.
