### ISSUE TITLE
AliRoot OCDB

### ISSUE THREAD

**Issue by mpuccio** [alisw/alidist#446]
Hi,

in the simulation macros for ITS Upgrade we rely on the OCDB to be installed in the `$ALICE_ROOT/OCDB` directory. It could be the case that also in other part of the framework the OCDB in the AliRoot Installation dir it is used.

I see that in the AliRoot recipe you support the Grid case (putting a placeholder), would it be possible to support the copy/linking of the OCDB?
Thanks!
Cheers,
Max

**Comment by dberzano** [comment]
Hello @mpuccio, @ktf: this might actually be a good use case for alisw/alibuild#304: having an `withocdb` default (in the `provides:` form) that applies only to AliRoot and compiling with `aliBuild build AliRoot --defaults withocdb` would address your issue.

**Comment by ktf** [comment]
The problem is that OCDB is large, so you might end up with a large package, that's why we have a placeholder and the OCDB-test.sh which copies it and builds it only when AliRoot-tests is built. How about we sit together next week and try to see what is the best solution to implement this?

**Comment by ktf** [comment]
This should not be a problem anymore, given the support for big files in the github migration, right? Can you close this?

**Comment by mpuccio** [comment]
True indeed, thanks a lot!
