### ISSUE TITLE
Error building O2 on Mac: boost

### ISSUE THREAD

**Issue by dstocco** [alisw/alidist#451]
Dear all,
I cannot build O2 on Mac.
Seems a problem with boost_thread (it picks up the system version, installed with boost):
[log.txt](https://github.com/alisw/alidist/files/323526/log.txt)

I see that a similar issue was affecting FairRoot and was solved [#407](https://github.com/alisw/alidist/issues/407) , but now it gets stuck at O2 compilation.

Could you please have a look?
I'm compiling with:
--disable GEANT4,GEANT4_VMC,HepMC,simulation,fastjet,generators,DDS

Thanks in advance,
best regards,
Diego

**Comment by dstocco** [comment]
Ciao Giulio,
No. I'm aware of the mail exchange on the subject, so I run the alibuild command in a new terminal (no alienv called...)
My path should be clear, so I'd say it should not be related.

Thanks,
Ciao,
Diego

**Comment by ktf** [comment]
reading it again, I think it's some hardcoded library name in FairRoot / O2. Are you building them locally?

**Comment by dstocco** [comment]
Ciao Giulio,
I'm not sure I understand your question, but yes, I build them locally on my laptop.
I install O2 with aliBuild init, so it is a "development package". FairRoot is installed by aliBuild as a dependency.

Ciao,
Diego

**Comment by dstocco** [comment]
Hi Giulio, all,
are there any news on this issue?
Or is there a linux distribution where O2 is supposed to work, so that I can start developing on it?

Thanks in advance,
best regards,
Diego

**Comment by ktf** [comment]
Catching a plane right now. Will be back later today.

**Comment by ktf** [comment]
Ciao. I finally managed to reproduce. Can you uninstall the system version of boost (brew uninstall boost, I guess) until it gets fixed? This is an actual issue in AliceO2 CmakeLists.txt.

**Comment by dstocco** [comment]
Ciao Giulio,
indeed, if I remove system boost, it is working: thanks!
Should I keep the ticket open as a memento for a fix in AliceO2?

Thanks!
ciao,
Diego

**Comment by ktf** [comment]
Yes, please.

**Comment by ktf** [comment]
We finally understood what is going on. Seems to be a change in behaviour of cmake which drops `-.*` from dependent libraries. We should have a proper fix soon.

**Comment by ktf** [comment]
FairRootGroup/FairRoot#405 is the required fix. Until it's merged, I suggest you use FairRoot as a development package and cherry-pick it.

**Comment by ktf** [comment]
Closing this as it got merged in upstream FairRoot. Reopen if still an issue.
