### ISSUE TITLE
Detect more hidden system dependencies

### ISSUE THREAD

**Issue by ktf** [alisw/alidist#466]
ROOT fails to compile if the following system packages are not found:

- [ ] libXpm
- [ ] libXft

**Comment by ktf** [comment]
@dberzano since you are fixing freetype, can you look at these as well?

**Comment by dberzano** [comment]
@ktf ok

**Comment by dberzano** [comment]
See #501.

**Comment by dberzano** [comment]
Let's continue in #460 (duplicated).
