### ISSUE TITLE
gSOAP depends on system SSL to be installed.

### ISSUE THREAD

**Issue by ktf** [alisw/alidist#467]
Apparently gSOAP on ubuntu 16.04 is compiled against system SSL, despite the fact we pass it as a dependency.

**Comment by aaniin** [comment]
Hello ktf, 

I just created https://github.com/alisw/alidist/pull/661 which is also about openssl system checks. The check to use the system's openssl right now is "exit 0" on anything else than mac OS, i.e. the system's openssl is always used.

Cheers,
Hans

**Comment by ktf** [comment]
Can we close this? I understand that #728 takes care of it, right? If not, please reopen.
