### ISSUE TITLE
Cannot compile AliRoot on SLC7 with IB/v5-08/prod : /usr/bin/ld: cannot find -lGenerators

### ISSUE THREAD

**Issue by aphecetche** [alisw/alidist#539]
Hi,

Using : 

aliBuild --defaults o2 build O2

(aliBuild version: 1.4.0.rc1 on a SLC7-like (container))

fails with :  

/usr/bin/ld: cannot find -lGenerators

log of the build is attached, together with the output of "aliDoctor O2"

[log.txt](https://github.com/alisw/alidist/files/502839/log.txt)

My O2 checkout is at commit 8609f4c, i.e. latest as far as I can tell.

**Comment by aphecetche** [comment]
Hi,

As far as I can tell the issue is still present. Should I post it on https://github.com/AliceO2Group/AliceO2 instead of here ?

**Comment by ktf** [comment]
Yes, I think this is an issue with O2, not alidist itself. Closing this, reopen if they bounce you here.

**Comment by ktf** [comment]
I think AliceO2Group/AliceO2#180 fixes the issue.
