### ISSUE TITLE
modulefiles should be generated on the fly from the metadata provided at the top of the package

### ISSUE THREAD

**Issue by sawenzel** [alisw/alidist#570]
A suggestion for improvement:

Currently it seems to be necessary to restate the dependencies of packages in the module-file part of recipes. If would be nice if this could be generated/built automatically.

**Comment by ktf** [comment]
Yes, modulefiles should be generated on the fly from the metadata provided at the top of the package. Adapting text of this issue.

**Comment by Barthelemy** [comment]
+1

**Comment by ktf** [comment]
@brinick

**Comment by ktf** [comment]
#2327 shows how this could be done. Closing this, please open more specific issues with the proposed approach, if any.
