### ISSUE TITLE
Hardwired reduction of parallel compilation for DDS and FairRoot

### ISSUE THREAD

**Issue by matthiasrichter** [alisw/alidist#582]
The number of processes for parallel builds of DDS and FairRoot is currently limited using a hardwired number, e.g. `make ${JOBS:+-j 2}`

`JOBS` variable is always set, either from the command line or as default from `detectJobs`, so there is no way to propagate a value from the command line to the make command. The default behavior could be to use reduced number of jobs if nothing is given on command line, but use the specified number of jobs also for DDS and FairRoot when specified on command line.

With currently only one variable `JOBS` one can not tell whether its the default or explicitly specified. How about introducing `DEFAULT_JOBS` set from `detectJobs` and empty default in `JOBS` in https://github.com/alisw/alibuild

Then in the recipes one can use
`${JOBS:+-j} ${JOBS:--j $DEFAULT_JOBS}`
and for reduced number of jobs
`${JOBS:+-j} ${JOBS:--j 2}`

**Comment by ktf** [comment]
As discussed privately, this is really a hack done to avoid DDS / FairRoot taking down a machine while building, due to excessive memory usage. I'd rather fix the problem before this is removed.

**Comment by dennisklein** [comment]
@ktf Can you elaborate on the memory problem with DDS/FairRoot? What fix do you have in mind? Is anyone working on this issue already?

**Comment by dennisklein** [comment]
I have looked into this issue and identified Boost.Log headers as significant contributors to compile time memory usage (~600MB for g++ 4.9.2 and ~350MB for clang++ 3.5.0) for the translation units with the most memory usage in the FairRoot `dev` branch and build profile `RELWITHDEBINFO`.

@ktf What compile time memory footprint would be acceptable per translation unit?

**Comment by ktf** [comment]
We usually compile -j 16 on a machine with 8gb of ram. So if you can stay
in 4GB (250mb per compilation unit) that would be great as the rest might
be needed for other stuff.

**Comment by dennisklein** [comment]
I discussed this with @AnarManafov and for DDS at least it is no option to waive the dependency to something like Boost.Log.

250 MB per compilation unit seems too low for modern C++ programs, just for comparison some statistics of memory consumption per translation unit on GCC 4.9.2 (in MB):
```
Project       | Min.  1st Qu.  Median    Mean  3rd Qu.    Max. 
DDS 1.5       |  2.5     27.7   236.0   387.2    564.9  1292.0
FairRoot dev  |  2.6     49.6   181.3   319.4    291.6  1232.0
Root 6-06-04  | 12.5    163.9   196.0   217.0    258.8  1254.0
```

Given the numbers above, on a single machine `$JOBS` should be the `min(GB RAM, #cpus) + 2` or so at maximum (much more jobs than cpus will not give a speedup neither). However, it very much depends on the compilation order how the aggregate memory footprint will look like.

I personally prefer more of a manual solution. Some of us compile on distcc/icecream clusters and have much higher `$JOBS` settings. Recipes that limit these settings based on hardwired values or the resources of the submission host would break this usecase.

**Comment by sawenzel** [comment]
I support the request to being able to configure $JOBS from the outside.

**Comment by matthiasrichter** [comment]
I'm closing the issue. There has been some adjustment in #834 and #700 quite a while ago.

@ktf, @dennisklein feel free to open another issue if some other problems need to be fixed in DDS or FairRoot.
