### ISSUE TITLE
AliEn-Runtime package: lib/libuuid.so and lib/libuuid.so.1 should be symlinks to lib/libuuid.so.1.3.0

### ISSUE THREAD

**Issue by BerserkerTroll** [alisw/alidist#608]
Currently they are identical ordinary files.

When I add `/path/to/AliEn-Runtime/lib` to `/etc/ld.so.conf.d/something.conf`, `ldconfig` complain that `libuuid.so` and `libuuid.so.1` aren't symlinks. Making them symlinks satisfies `ldconfig`. So `libuuid`, like any other shared library, should follow the convention.

**Comment by aaniin** [comment]
Hi @BerserkerTroll ,

Can you look at #809 and test the solution from there?

Cheers,
Hans

**Comment by ktf** [comment]
Closing this in favour of #809.
