### ISSUE TITLE
Loose system compiler constraints for O2

### ISSUE THREAD

**Issue by ktf** [alisw/alidist#640]
We should really allow 6.X compilers there.

**Comment by ktf** [comment]
@dberzano was there any reason for not doing so?
@dest1

**Comment by dberzano** [comment]
In my opinion there is no reason. But we should discuss it on Friday as foreseen, especially now that [devtoolset-6](https://linux.web.cern.ch/linux/centos7/docs/softwarecollections.shtml) is out.

**Comment by ktf** [comment]
O2 now requires gcc 6.x due to C++14 requirement. We can close this.
