### ISSUE TITLE
Add support for boost_python

### ISSUE THREAD

**Issue by Barthelemy** [alisw/alidist#642]
In recipe for boost, python_boost should be enabled (needed for flp prototype).

**Comment by Barthelemy** [comment]
I am preparing a PR for this. Could @ktf or @dberzano tell me why the recipe for python depends on AliEn-Runtime ? that does not seem to make sense.

**Comment by ktf** [comment]
I agree we should reevaluate this.

**Comment by ktf** [comment]
Because we package a few alien specific dependencies like openssl inside
alien itself. Indeed it makes no much sense but it was done to minimize the
number of externals we publish for AliRoot on CVMFS.

**Comment by Barthelemy** [comment]
ok thank you for your explanation. It is not a problem for me, I was just curious.

**Comment by ktf** [comment]
Comments arrived in the wrong order, by the way... ;-)

**Comment by Barthelemy** [comment]
I noticed :) but I deciphered your messages nonetheless

**Comment by Barthelemy** [comment]
@dberzano I think that this is already fixed. Can you confirm ?
