### ISSUE TITLE
add -fno-omit-frame-pointer to debug mode cflags

### ISSUE THREAD

**Issue by mkrzewic** [alisw/alidist#652]
Could you add -fno-omit-frame-pointer to the compiler flags in debug mode? some perf tools (perf) do not like to work without this.

**Comment by sawenzel** [comment]
@mkrzewic : For now, I believe you can do this yourself by just defining your own default. On the other hand, I don't quite see why you would want to study performance (perf) in debug mode (aka -O0)? Or is this not performance related?

**Comment by mkrzewic** [comment]
Hi, i do define my own default, but it seems hackish... You are right that with -O0 strictly speaking we're not looking at the most performant code :) But it does let you (well, me) at least see the hotspots in the algorithm, which in most cases is the bottleneck anyway...
Maybe something smarter could be done? Like a performance-debug mode?

**Comment by ktf** [comment]
Closing this. Reopen if needed.
