### ISSUE TITLE
Question about best usage of a new recipe

### ISSUE THREAD

**Issue by aphecetche** [alisw/alidist#669]
Hi,

Some background :

In the MRRTF (Muon Run3 Reconstruction Task Force), we had (and still have, as it's still there) a `feature-muonhlt` branch in `git.cern.ch` AliRoot repository. We did not use this branch heavily but had a couple of custom HLT components to be used with O2's `aliceHLTWrapperApp`. 
Now that we've moved AliRoot to github, instead of having such a giant dev. branch to be kept in sync, etc..., I created a standalone repo (https://github.com/mrrtf/alo) that depends on both AliRoot and O2 (well, actually only AliRoot, but the intent is to possibly depends on both for some time, and then disintegrate the repo altogether once everything is moved to O2), where I've moved our custom HLT dev components. 

Now that I'm used to alibuild, I of course would like to integrate the `alo` package as a recipe (and some defaults). I've done that in (a branch of) https://github.com/mrrtf/alidist. And it even seems to work (when I don't remove the MODULES directory, that is ;-) )

Here's (finally...) the question : 

Does this sound like a workable plan or should the recipe (and the defaults) be integrated to `alisw/alidist` ? The way I see it : having the recipe is `mrrtf/alidist` puts some maintenance burden on me (I have to keep it in sync with `alisw/alidist`). On the other hand, maybe the central `alisw/alidist` is not the right place for a subproject ? Or is it ?

@tkf, please let me know your take on this. Thanks and sorry for the long story.

**Comment by ktf** [comment]
I think it's fine to have it in alidist, especially if it's simply a default and some package. We have a few recipes which follow in the same category already.

**Comment by ktf** [comment]
I am @ktf, by the way...

**Comment by ktf** [comment]
I hope this is clarified. Reopen if not.

**Comment by aphecetche** [comment]
ok, will prepare a PR then.
and sorry for the misspelled mention ;-)
