### ISSUE TITLE
gtest-devel is necessary for FairRoot build but has no recipe

### ISSUE THREAD

**Issue by Barthelemy** [alisw/alidist#683]
On CC7 if gtest-devel is not installed the configuration of FairRoot fails. Shouldn't there be a recipe for gtest-devel and FairRoot depend on it ?

**Comment by sawenzel** [comment]
Actually, the fairroot.sh recipe mentions:

```
build_requires:
  - googletest
```

and in my case it builds googletest = gtest automatically.

**Comment by Barthelemy** [comment]
interesting
on CC7 ?

**Comment by sawenzel** [comment]
@Barthelemy : Can you check whether googletest is built/listed by alibuild? I suspect this might be a problem on the CMake level.

**Comment by Barthelemy** [comment]
@sawenzel How do I force alibuild to rebuild fairroot ? I installed gtest-devel meanwhile and compiled it successfully. In order to reproduce the problem I would need to force a rebuild of FairRoot.

**Comment by sawenzel** [comment]
The way I usually do this is to checkout FairRoot as development package and do a little trivial mod in one of the files. Maybe @dberzano or @ktf can comment on other methods.

**Comment by Barthelemy** [comment]
Ok, Dario clarified that it should be fixed in the `master`.

**Comment by dberzano** [comment]
Hi, I usually force-rebuild by doing the same as @sawenzel - also adding dummy files works.

@Barthelemy: last week the FairRoot guys did loads of modifications to the code. @ktf has added a recipe for gtest. If you use the latest `alisw/alidist:master` it will work.
