### ISSUE TITLE
cmake version not sufficient/compatible with FairRoot

### ISSUE THREAD

**Issue by sawenzel** [alisw/alidist#684]
the cmake recipe in master builds 3.5 and is not enough to build FairRoot (which requires 3.6.)

**Comment by KlewinS** [comment]
#667 refers to the same issue

**Comment by ktf** [comment]
This should be fixed now when using `--defaults o2 / o2-daq`. Can you confirm?

**Comment by sawenzel** [comment]
This is ok. Closing.
