### ISSUE TITLE
Error when compiling DDS

### ISSUE THREAD

**Issue by awegrzyn** [alisw/alidist#703]
I have an issue while compiling DDS:
```
[100%] Generate WN binary package
cp: cannot stat 'not': No such file or directory
ERROR (Step code #5): Can not build DDS worker package. Missing dependency.
CMakeFiles/wn_bin.dir/build.make:57: recipe for target 'CMakeFiles/wn_bin' failed
make[3]: *** [CMakeFiles/wn_bin] Error 1
CMakeFiles/Makefile2:167: recipe for target 'CMakeFiles/wn_bin.dir/all' failed
make[2]: *** [CMakeFiles/wn_bin.dir/all] Error 2
CMakeFiles/Makefile2:174: recipe for target 'CMakeFiles/wn_bin.dir/rule' failed
make[1]: *** [CMakeFiles/wn_bin.dir/rule] Error 2
Makefile:223: recipe for target 'wn_bin' failed
make: *** [wn_bin] Error 2
```
I asked DDS for help, but apparentely they provide support and fixes to the latest tag (1.7) only and aliBuild uses 1.4.
1.7 requires boost 1.61 and atm it's not supported by aliBuild.

**Comment by ktf** [comment]
Have you tried bumping boost to 1.61 in the O2 default?

**Comment by awegrzyn** [comment]
I tried but then I get follwing error:
Boost include path:
```
  /home/awegrzyn/alice/sw/slc7_x86-64/boost/v1.62.0_O2_DAQ-1/include

  Detected version of Boost is too old.  Requested version was 1.61 (or
  newer).
```
It's either DDS CMake issue or something wrong in aliBuild

**Comment by ktf** [comment]
I fixed a problem in #812 which relates to boost and DDS. Can you check again?

**Comment by ktf** [comment]
#813 also moves to DDS 1.6 which fixes a problem which @MohammadAlTurany reported.

**Comment by ktf** [comment]
Ping? Does the new alidist work for you?
