### ISSUE TITLE
Build fails building pythia6 on MacOS X

### ISSUE THREAD

**Issue by KlewinS** [alisw/alidist#705]
build (aliBuild --defaults o2 build O2) fails with

> ...
[100%] Linking Fortran shared library libpythia6.dylib
Undefined symbols for architecture x86_64:
  "__gfortran_compare_string", referenced from:
      _pyslha_ in pythia-6.4.28.f.o
...
 ld: symbol(s) not found for architecture x86_64

whole log is here
[log.txt](https://github.com/alisw/alidist/files/972970/log.txt)

**Comment by aaniin** [comment]
Hi @KlewinS ,

Do you still have the problem with building pythia6 on your mac reported in May?

One check you could make is to look at the architecture of your libgfortran.a
```bash
gfortran --version
gfortran --print-file-name libgfortran.a
lipo -info $(gfortran --print-file-name libgfortran.a)
```

On my mac, this gives
```bash
Hanss-MacBook:~ hbeck$ gfortran --version
GNU Fortran (GCC) 6.3.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Hanss-MacBook:~ hbeck$ gfortran --print-file-name libgfortran.a
/usr/local/gfortran/lib/gcc/x86_64-apple-darwin16/6.3.0/../../../libgfortran.a
Hanss-MacBook:~ hbeck$ lipo -info $(gfortran --print-file-name libgfortran.a)
input file /usr/local/gfortran/lib/gcc/x86_64-apple-darwin16/6.3.0/../../../libgfortran.a is not a fat file
Non-fat file: /usr/local/gfortran/lib/gcc/x86_64-apple-darwin16/6.3.0/../../../libgfortran.a is architecture: x86_64
```

Cheers,
Hans

**Comment by KlewinS** [comment]
Hi Hans,

I haven't tried it for a long time. But even though my fortran compiler version is smaller 

`alice-klewin:alice Sebastian$ gfortran --version `
`GNU Fortran (GCC) 5.2.0`

the compilation was fine today.
