### ISSUE TITLE
Python check issues

### ISSUE THREAD

**Issue by dstocco** [alisw/alidist#708]
Dear @dberzano ,
I'm using Mac 10.12.4 with python 2.7.10 (and pip) installed.

After your commit:
69b8fe7dda0a6bb4dc6b0b8f9d1e64c8ca1c52d6
python is not found from the system and installed (or better, it tries to install it since an error occur).
Here's what aliDoctor says:
```
WARNING: Package Python cannot be picked up from the system and will be built by aliBuild.
WARNING: This is due to the fact the following script fails:
WARNING: 
WARNING: python -c 'import sys; import sqlite3; sys.exit(1 if sys.version_info < (2, 7) else 0)' && pip --help > /dev/null && printf '#include \"pyconfig.h"' | gcc -c -I$(python-config --cflags) -xc -o /dev/null -
WARNING: 
WARNING: with the following output:
WARNING: 
WARNING: Python: fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't create temporary output file: /dev/null.lipo (Permission denied)
WARNING: Python: clang: error: lipo command failed with exit code 1 (use -v to see invocation)
WARNING: Python: 
WARNING: 
```

Looks like the option -o /dev/null causes some issues.
Not sure how to fix this. Anyways, if I remove the check the system python is used...but I have then some issues when compiling Python-modules:
`
error: six 1.4.1 is installed but six>=1.9 is required by set(['mock'])
`

Thanks in advance,
best regards,
Diego

**Comment by dberzano** [comment]
Hi Diego, I cannot reproduce it on my Mac (of course I have tested it before committing).

What happens if you paste this line alone on your prompt (without aliBuild)?

```
python -c 'import sys; import sqlite3; sys.exit(1 if sys.version_info < (2, 7) else 0)' && pip --help > /dev/null && printf '#include \"pyconfig.h"' | gcc -c -I$(python-config --cflags) -xc -o /dev/null -
```

Did you do the usual things (update Xcode, update the command-line tools...)?

**Comment by dstocco** [comment]
Ciao Dario,
you're fast ;)
Here is what I get:
```
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't create temporary output file: /dev/null.lipo (Permission denied)
clang: error: lipo command failed with exit code 1 (use -v to see invocation)
```
I had already tested it command line. The issue is in the last test:
`printf '#include \"pyconfig.h"' | gcc -c -I$(python-config --cflags) -xc -o /dev/null -`
For some reasons, gcc wants to create the file /dev/null.lipo, and of course it does not have the correct permissions....
If I do
`printf '#include \"pyconfig.h"' | gcc -c -I$(python-config --cflags) -xc -o /tmp/a.out -`
it works fine...but not sure if it is ok.

Ciao,
Diego

**Comment by dberzano** [comment]
Hi, the solution is not OK as `/dev/null` should work, and the temporary file name you are using is not safe. As said, `/dev/null` is a perfectly legit output file name, and `lipo` is used only to create fat binaries. If you claim to be using the correct macOS version, then this should simply not be happening.

Can you tell me more about your gcc? Did you update the command-line tools properly?

```
which gcc
gcc -v
```

**Comment by dstocco** [comment]
Ciao Dario,
I performed some further check.
So, here is the output go my python-config -cflags:
```
-I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE
```
Now, googling around it looks like the non-fat files are:
```
lipo -info $(which lipo)
Non-fat file: /usr/bin/lipo is architecture: x86_64
```
The problem is that in the python-config -cflags there is:
`-arch i386 -arch x86_64`
If, instead of using $(python-config -cflags), I copy-paste its output and remove -arch i386, it works like charm.

So I have the impression that my issue is not Xcode or the command line tools: it's python.
Do you have python 3 installed or do you use the system python?

Thanks,
ciao,
Diego

**Comment by dberzano** [comment]
Indeed, I came to the same conclusion some minutes ago! So, you are actually using system's python:

```
-I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE
```

whereas Homebrew's Python (which I have) gives:

```
-I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes
```

However the fix must come on our side, but now at least I know what to do :-)

Thanks!

**Comment by dstocco** [comment]
Cool thanks!

By the way, apart from the fix: would you suggest to move to brew python or to stick with the (pretty old) system one?
Anyways, the system python has some old packages (such as six 1.4), so in any case I cannot compile the Python-modules (which require six >= 1.9)

Thanks,
ciao,
Diego

**Comment by dberzano** [comment]
Hi Diego, so - for our use case it does not matter if you stick to the system-provided one. If you install with `pip` all the missing modules from your system, aliBuild will skip the compilation of `Python-modules` package, which is really meant for the Grid only. Just run:

```
aliDoctor Python-modules
```

and according to the errors keep installing the missing packages with `pip` (there's three or four of them).

**Comment by dstocco** [comment]
Ciao Dario,
ok, will do it

Thanks a lot!
Ciao,
Diego

**Comment by dberzano** [comment]
I have merged the fix to alidist master, can you check if it works for you please? Thanks!

**Comment by dstocco** [comment]
Ciao Dario,
yes, it works!
Thanks a lot!
Ciao,
Diego
