### ISSUE TITLE
ROOT fails when linking pythia8

### ISSUE THREAD

**Issue by matthiasrichter** [alisw/alidist#730]
Installing `aliBuild --defaults o2 --disable Python --disable Python-modules build o2` on the hltdev cluster

```bash
==> Packages will be built in the following order:
     - defaults-o2@v1
     - hijing@v1.36
     - autotools@v1.5.0
     - nanomsg@1.0.0
     - GCC-Toolchain@v6.2.0-alice1
     - Vc@1.3.2
     - protobuf@v3.0.2
     - pythia6@alice/428
     - HepMC@alice/v2.06.09
     - googletest@release-1.8.0
     - ZeroMQ@v4.1.5
     - GEANT4@v4.10.01.p03
     - boost@v1.59.0
     - GSL@release-1-16
     - DDS@1.4
     - yaml-cpp@release-0.5.2
     - ROOT@v6-08-02
     - lhapdf@alice/v6.1.5
     - vgm@4.3-alice1
     - GEANT3@v2-3
     - pythia@alice/v8211pre
     - GEANT4_VMC@v3-2-p1-alice1
     - generators@v1.0
     - simulation@v1.0
     - FairRoot (development package)
     - O2 (development package)
```

It turns out that pythia8 is installed in the system and ROOT picks it up from there, however then the linking fails. The actual pythia recipe is build later

- [ ] is the system/version check in the pythia recipe correct?
- [ ] what is wrong with the ROOT cmake setup?
- [ ] do we need to change to sequence so that pythia is built before ROOT?

**Comment by matthiasrichter** [comment]
follow up: this issue probably also related to the move to gcc6. The Pythia8 installation is compiled with a different version. Making pythia a dependency of the ROOT recipe does not help, looks like that the local pythia installation is not propagated to the ROOT build.

**Comment by matthiasrichter** [comment]
@dberzano as just agreed in our discussion the `pythia.sh` recipe should make sure to never pick up pythia8 from the system. Maybe it's not even a problem of the pythia recipe but the root recipe.

Another thing to be checked is the fact that ROOT is build with pythia but there is no requirement in the recipe.

**Comment by KlewinS** [comment]
is there already a fix? I have the same problem.

**Comment by matthiasrichter** [comment]
@dberzano, should we close this?

**Comment by ktf** [comment]
I think this is not an issue anymore. Reopen if it's the case.
