### ISSUE TITLE
ROOT fails to build on Ubuntu 16.04 with alidist 26fbafc221cf59e80671a305182

### ISSUE THREAD

**Issue by sawenzel** [alisw/alidist#741]
calling `alibuild build O2 --defaults=o2`, I get during compilation of  ROOT:

DEBUG:O2:f4ddebc4: Running /home/sandro/alisw_new/sw/SOURCES/ROOT/v6-08-02_O2/v6-08-02/build/unix/compiledata.sh
DEBUG:O2:f4ddebc4: Making include/compiledata.h
DEBUG:O2:f4ddebc4: -- Configuring done
DEBUG:O2:f4ddebc4: -- Generating done
DEBUG:O2:f4ddebc4: -- Build files have been written to: /home/sandro/alisw_new/sw/BUILD/d1fa5dfa39e25f3ad2bbfeb43bf187adc7048e3c/ROOT
DEBUG:O2:f4ddebc4: + FEATURES='builtin_pcre mathmore xml ssl opengl minuit2
DEBUG:O2:f4ddebc4:             pythia6 roofit soversion vdt  cxx14 
DEBUG:O2:f4ddebc4:             
DEBUG:O2:f4ddebc4:             '
DEBUG:O2:f4ddebc4: + NO_FEATURES=
DEBUG:O2:f4ddebc4: + bin/root-config --features
DEBUG:O2:f4ddebc4: asimage astiff builtin_afterimage builtin_ftgl builtin_gl2ps builtin_glew builtin_pcre builtin_unuran builtin_lzma builtin_llvm cxx14 cling exceptions explicitlink fortran genvector http mathmore memstat minuit2 opengl pch pythia6 pythia6_nolink python roofit root7 shared soversion thread tmva vdt xft xml x11
DEBUG:O2:f4ddebc4: + for FEATURE in '$FEATURES'
DEBUG:O2:f4ddebc4: + bin/root-config --has-builtin_pcre
DEBUG:O2:f4ddebc4: + grep -q yes
DEBUG:O2:f4ddebc4: + for FEATURE in '$FEATURES'
DEBUG:O2:f4ddebc4: + bin/root-config --has-mathmore
DEBUG:O2:f4ddebc4: + grep -q yes
DEBUG:O2:f4ddebc4: + for FEATURE in '$FEATURES'
DEBUG:O2:f4ddebc4: + bin/root-config --has-xml
DEBUG:O2:f4ddebc4: + grep -q yes
DEBUG:O2:f4ddebc4: + for FEATURE in '$FEATURES'
DEBUG:O2:f4ddebc4: + bin/root-config --has-ssl
DEBUG:O2:f4ddebc4: + grep -q yes
DEBUG:O2:f4ddebc4: 
ERROR:O2:f4ddebc4: Error while executing /home/sandro/alisw_new/sw/SPECS/ubuntu1604_x86-64/ROOT/v6-08-02_O2-1/build.sh on `pcalice121'.
ERROR:O2:f4ddebc4: Log can be found in /home/sandro/alisw_new/sw/BUILD/ROOT-latest/log.
ERROR:O2:f4ddebc4: Please attach this file if you intend to request support.
ERROR:O2:f4ddebc4: Build directory is /home/sandro/alisw_new/sw/BUILD/ROOT-latest/ROOT.

**Comment by sawenzel** [comment]
One thing that I notice is that ROOT tries to compile against my gcc 5.4 ... although alibuild has explicitely built gcc 6.2 just one step before:

+ [[ -n '' ]]
+ cmake /home/sandro/alisw_new/sw/SOURCES/ROOT/v6-08-02_O2/v6-08-02 -DCMAKE_BUILD_TYPE=RELWITHDEBINFO -DCMAKE_INSTALL_PREFIX=/home/sandro/alisw_new/sw/INSTALLROOT/d1fa5dfa39e25f3ad2bbfeb43bf187adc7048e3c/ubuntu1604_x86-64/ROOT/v6-08-02_O2-1 -Dcxx14=ON -Dfreetype=ON -Dbuiltin_freetype=OFF -Dpcre=OFF -Dbuiltin_pcre=ON -DCMAKE_CXX_COMPILER=c++ -DCMAKE_C_COMPILER=cc -DCMAKE_LINKER=c++ -Dpgsql=OFF -Dminuit2=ON -Dpythia6_nolink=ON -Droofit=ON -Dhttp=ON -Dsoversion=ON -Dshadowpw=OFF -Dvdt=ON '-DCMAKE_PREFIX_PATH=;;;;;'
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works

**Comment by ktf** [comment]
@sawenzel I assume this can be closed, correct?
