### ISSUE TITLE
Building ROOT with O2 (defaults-o2) fails on CC7 when libxml2-devel is not installed

### ISSUE THREAD

**Issue by omasanori** [alisw/alidist#760]
ROOT depends on libxml2 and the dependency is satisfied via AliEn-Runtime which depends on libxml2 explicitly. When I execute `alibuild --defaults o2 build O2`, however, libxml2 is not in packages to be built. Thus, the build fails if the development package for libxml2 is not installed into the system. I encountered with the problem on CC7 (7.3.1611), x86_64.

Steps to reproduce (assumes all mandatory deps have been installed into the system):
```shell
$ sudo yum remove libxml2-devel # ensure there is no devel package of libxml2
$ mkdir -p $HOME/testenv
$ cd $HOME/testenv
$ aliBuild init O2@dev
$ aliBuild --defaults o2 build O2
```
Workaround: Install libxml2-devel (or libxml2-dev on Ubuntu, I guess.)

Additional log(s): https://gist.github.com/omasanori/4b7b6d199196c150a45df514e30535db

**Comment by ktf** [comment]
Indeed, this is a real issue. @dberzano can you look into it?

**Comment by omasanori** [comment]
https://github.com/alisw/alidist/pull/1210 will fix this issue. I will check after it is merged.

**Comment by dberzano** [comment]
Hi @omasanori, the PR has been merged and the issue should have been fixed. Let me remind you that - given that this was an actual problem - it wouldn't have occurred if you followed the [build instructions](https://alice-doc.github.io/alice-analysis-tutorial/building/).

Please close if your issue is fixed.

**Comment by omasanori** [comment]
@dberzano OK, I confirmed that the issue is fixed now. Thank you!
And, yes, we should always follow the official instructions.
