### ISSUE TITLE
usage of valid_defaults ?

### ISSUE THREAD

**Issue by aphecetche** [alisw/alidist#761]
Hi,

What is valid_defaults meant for ? 

The only recipe it's used seems to be o2.sh. If I depend on O2, should I use it as well ? How ?

Asking because I'm having, since this morning, a problem with my alo package : when I ask to build it, it gets built, but I'm no longer offered the advice to do `alienv enter alo/latest` but `alienv enter O2/latest` ... So I'm (quite blindly I must confess) trying to find out why...

```
==> Building ROOT@v6-08-02_ALO
==> ROOT is being built (use --debug for full output): ok
Using cached build for ROOT
Cloning into bare repository '/Users/laurent/alice/sw2/MIRROR/aliroot'...
remote: Counting objects: 466238, done.
remote: Compressing objects: 100% (56/56), done.
remote: Total 466238 (delta 60), reused 76 (delta 50), pack-reused 466132
Receiving objects: 100% (466238/466238), 515.91 MiB | 588.00 KiB/s, done.
Resolving deltas: 100% (338443/338443), done.

==> Building AliRoot@v5-09-03_ALO
==> AliRoot is being built (use --debug for full output): ok
Using cached build for AliRoot
Cloning into bare repository '/Users/laurent/alice/sw2/MIRROR/fairroot'...
remote: Counting objects: 53989, done.
remote: Total 53989 (delta 0), reused 0 (delta 0), pack-reused 53989
Receiving objects: 100% (53989/53989), 165.47 MiB | 1.50 MiB/s, done.
Resolving deltas: 100% (38829/38829), done.

==> Building FairRoot@alice-dev-20170524
==> FairRoot is being built (use --debug for full output): ok
Using cached build for FairRoot
Cloning into bare repository '/Users/laurent/alice/sw2/MIRROR/o2'...
done.

==> Building O2@0_ALO
==> O2 is being built (use --debug for full output): ok
Cloning into bare repository '/Users/laurent/alice/sw2/MIRROR/alo'...
done.

==> Building alo@0_ALO
==> alo is being built (use --debug for full output): ok

==> Build of O2 successfully completed on `nanpc420.in2p3.fr'.
    Your software installation is at:

      /Users/laurent/alice/sw2/osx_x86-64

    You can use this package by loading the environment:

      alienv enter O2/latest

==> Build directory for devel package O2:
    /Users/laurent/alice/sw2/BUILD/O2-latest/O2

==> Build directory for devel package alo:
    /Users/laurent/alice/sw2/BUILD/alo-latest/alo
 ```

**Comment by aphecetche** [comment]
Hi,

OK, I guess I will close this one. 

1 - about valid_defaults, it's actually documented (https://alisw.github.io/alibuild/reference.html)... RTFM !

2 - the message I see (Build of O2 success... while I was asking for alo), while confusing, looks more than a feature than a bug. Looking at alibuild source I see that indeed if one of AliRoot,AliPhysics or O2 is in the build chain, it is then taken as the main package, instead of the last one. 
Thing is that I was certain that I've seen before alibuild happily reporting "alienv enter alo/latest" instead of "alienv enter O2/latest". Must have dreamt it or my neurons are getting old (no, I don't want to know which one you think it is ;-) )

Sorry for the noise,

**Comment by ktf** [comment]
Sorry for the late reply.

Regardind 1. yes, RTFM ;-), regarding 2. indeed it's a feature, but a confusing one and we plan to get rid of it "soon".
