### ISSUE TITLE
DDS fails to configure when boost is not installed in the system

### ISSUE THREAD

**Issue by jniedzie** [alisw/alidist#764]
I try to build O2 using aliBuild on macOS 10.12.5, with master version of alidist, using the following command:

`aliBuild -j8 --defaults o2-daq build O2`

Boost is not installed in the system, here is the output of aliDoctor:

```
The following packages will be picked up from the system:
    - Python-modules
    - CMake
    - protobuf
    - libxml2
    - SWIG
    - zlib
    - nanomsg
    - ZeroMQ
    - autotools
    - GSL

    If this is not you want, you have to uninstall / unload them.

The following packages will be build by aliBuild because they couldn't be picked up from the system:
    - boost
    - yaml-cpp
````

The build breaks on DDS@master-1.4, from the log it seems that CMake sets the location of boost to where it would be installed by brew, but the library is not there. This probably comes from the recipe where "brew --prefix" is used to locate boost, which according to documentation:

> Display the location in the cellar where formula is or would be installed.

I attach the full log file. This issue prevents me from compiling O2 framework and thus blocks my development - thanks in advance for your help.

[log.txt](https://github.com/alisw/alidist/files/1080266/log.txt)

**Comment by ktf** [comment]
Do you actually have boost in:

```bash
/usr/local/Cellar/boost/1.64.0_1/
```

I have seen cases where brew reports old empty cellars. I would do:

```bash
brew cleanup boost
brew upgrade boost
brew cleanup boost
```
