### ISSUE TITLE
FairRoot fails to configure with boost from brew

### ISSUE THREAD

**Issue by jniedzie** [alisw/alidist#765]
Trying to compile O2 with aliBuild on macOS 10.12.5 (alidist from master), FairRoot@alice-dev-20170524 fails to configure when boost is taken from the system (ver. 1.64). Output from aliDoctor:

````
The following packages will be picked up from the system:

    - Python-modules
    - CMake
    - protobuf
    - libxml2
    - SWIG
    - zlib
    - yaml-cpp
    - nanomsg
    - ZeroMQ
    - autotools
    - boost
    - GSL
````

In the cmake log I get plenty of errors like this one:

> CMake Error at fairmq/CMakeLists.txt:242 (add_executable):
>   Target "runConfigExample" links to target "Boost::log" but the target was
>   not found.  Perhaps a find_package() call is missing for an IMPORTED
>   target, or an ALIAS target is missing?

Full log file in the attachment. I would be very grateful for you help, as this issue blocks my work.

[log.txt](https://github.com/alisw/alidist/files/1080301/log.txt)

**Comment by dennisklein** [comment]
Please update your CMake version to 3.8+

**Comment by dennisklein** [comment]
Which CMake version you need depends among other things on the Boost version you want to use:

| Boost version | CMake version |
| --- | --- |
| 1.61 and lower | 3.6.2+ |
| 1.63 and lower | 3.7.2+ |
| 1.64 and lower | 3.8.2+ |

This is, because we currently rely on imported targets from the [FindBoost.cmake](https://github.com/Kitware/CMake/commits/master/Modules/FindBoost.cmake) module shipped officialliy with CMake. This module needs to be updated for each new Boost release.

**Comment by jniedzie** [comment]
Thank you @dennisklein, this solved the issue. Shouldn't then the version of CMake be verified before building and updated automatically if needed?

**Comment by ktf** [comment]
@jniedzie in principle alidist should check for the right cmake. Can you tell us your alidist hash?

**Comment by jniedzie** [comment]
Here it is: abc842308a5edb8cde5565db9299626a130e54b4

**Comment by ktf** [comment]
Can you tell me what:

```bash
which cmake && cmake --version | sed -e 's/.* //' | cut -d. -f1,2,3 | head -n1
```

tells you?

**Comment by jniedzie** [comment]
Now it's:

> /usr/local/bin/cmake
> 3.8.2

but I already upgraded it. Before it was 3.6.x

**Comment by ktf** [comment]
Mmm... The check if for CMake > 3.5, not for the complex set of cases @dennisklein reported. @dberzano we should probably update the check to require 3.8.2 to be on the safe side.

**Comment by dennisklein** [comment]
@ktf I also didn't see an easy way to express these constraints in the alibuild recipe. If people are not happy to enforce always the newest CMake version for everyone, it could be solved by copying the FindBoost module into the project repo and not use it from the CMake installation. This shifts maintenance work partly to the repo authors of course (FairRoot in this case, AliceO2 also uses the imported boost targets, but it reuses FairRoot cmake modules I believe).

**Comment by ktf** [comment]
I think using the new CMake, at least for O2, is not really an issue. Let's discuss it for the next WP3 meeting.

**Comment by dennisklein** [comment]
There is also the edge case, when boost releases 1.65 and brew updates its formulas and there is no CMake release yet. In this case we would need to forbid 1.65 via system check for a while or we ship the master version of FindBoost (which will probably be updated pretty fast on Boost releases) in FairRoot.

**Comment by ktf** [comment]
Reopen if still the case.
