### ISSUE TITLE
Developing package from Mercurial repository

### ISSUE THREAD

**Issue by pkarczma** [alisw/alidist#771]
I am working on Mercurial upstream repositories of Rivet and YODA which I wanted to install using aliBuild. In order to do that I had to initialize new git repository inside these Mercurial repositories and make an initial commit, because aliBuild required me to do that. Is there a possibility to not to use any git repository at all instead of creating an unnecessary one in case when I am using Mercurial repository?

**Comment by ktf** [comment]
No, and supporting this is not on the plan. This case falls in the third bullet here:

https://github.com/alisw/alidist#guidelines-for-handling-externals-sources

and I think it's a good idea we stick to it. If you really need to track rivet and yoda developments, on a commit by commit basis, I would suggest you have some automated conversion from mercurial to git and apply your patches on top of the git mirror. At @dberzano the last word.

**Comment by dberzano** [comment]
I fully agree with @ktf. The whole system we have relies on Git. An automatic conversion would be the best solution IMHO. Can we close this?

**Comment by pkarczma** [comment]
Ok, I understand. Thanks for the information and for the link, I will follow you suggestion.
