### ISSUE TITLE
Building Configuration with flpproto (defaults-o2-daq) fails on CC7 when libcurl-devel is not installed

### ISSUE THREAD

**Issue by omasanori** [alisw/alidist#788]
Even though [Configuration recipe explicitly depends on cURL](https://github.com/alisw/alidist/blob/3ca7eeaf52f7af64ec1c3cd86ab87602b85620b3/configuration.sh#L3), neither aliDoctor nor aliBuild consider the dependency, resulting in build failure unless development package of libcurl (`libcurl-devel` on CC7 and other RHEL-derived distros) has been installed on the system.

Steps to reproduce:
```shell
$ sudo yum remove libcurl-devel # ensure there is no devel package of libcurl
$ mkdir -p $HOME/testenv
$ cd $HOME/testenv
$ aliBuild init flpproto
$ aliBuild --defaults o2-daq flpproto
```
Workaround: Install libcurl-devel (or libcurl-dev on Ubuntu, I guess)

Additional logs: https://gist.github.com/omasanori/101f79c2dfe574f654893c9e18c3ef6d

**Comment by ktf** [comment]
The curl recipe simply checks that the curl client is there, not that the development package is available, hence the problem. @Barthelemy I suspect you want to have the full blown curl installation, right?

**Comment by omasanori** [comment]
I see.
(It seems strange that curl is found by aliDoctor (according to the "SUCCESS: Required package curl will be picked up from the system." line) but it is not listed in "The following packages will be picked up from the system:" section, though.)

**Comment by ktf** [comment]
Because we have two kind of system packages:

- system requirements: these cannot be built by alibuild and are a prerequisite for the build. This is what happens for curl.
- preferred system: these can be built by alibuild but can also be reused from the system, if compatible. This is what happens for boost.

for the former kind, we silently check for them, without mentioning at build time. We need to change curl from the first to the second kind.

**Comment by Barthelemy** [comment]
@ktf This is for the Configuration. @PascalBoeschoten should be able to tell more about that requirement. He should be back on Wednesday.

**Comment by omasanori** [comment]
@ktf OK, now I understood the distinction. Thank you!

**Comment by ktf** [comment]
I assume this is not an issue anymore. Closing. Reopen if still needed.
