### ISSUE TITLE
Enable pythia8 while building root

### ISSUE THREAD

**Issue by preghenella** [alisw/alidist#803]
Dear alidist,

When building O2 I have Pythia8 package installed, although it does not seem that ROOT is built with pythia8 enabled?
Would it be possible to enable pythia8 support in ROOT?
That would be useful to have the possibility to use the TPythia8 interface which is already there in ROOT.

Thanks,
Roberto

**Comment by preghenella** [comment]
perhaps this is related to #730. Apologies for the duplication in case.

**Comment by ktf** [comment]
I assume this was fixed. Reopen if not the case.
