### ISSUE TITLE
Put DPMJET under github.com/alisw/ and refer to it from alidist

### ISSUE THREAD

**Issue by omasanori** [alisw/alidist#833]
(I am not sure whether here is the right place to discuss this, though...)
Now AliRoot depends on external DPMJET previously bundled in, and alidist refers to [https://gitlab.cern.ch/ALICEPrivateExternals/DPMJET](https://gitlab.cern.ch/ALICEPrivateExternals/DPMJET), which requires to input login information to the terminal for building AliRoot. It is annoying a bit and I don't see any reason why the previously-published component shall be private now.

It would be great if DPMJET is managed in alisw GitHub organization just like some other software has already been.

**Comment by aaniin** [comment]
Hi @omasanori ,

This is a license problem, DPMJet is not public. You can write the DPMJet author and ask to make it public: Stefan.Roesler@cern.ch 
ALICE can do nothing here, I suggest to close this issue. 

Cheers,
Hans

**Comment by omasanori** [comment]
Thank you for explanation, @aaniin !
Now I've confirmed that DPMJET is not publicly distriuted on [the author's web site](http://sroesler.web.cern.ch/sroesler/dpmjet3.html) but a request is required. Closing.
