### ISSUE TITLE
cern-get-sso-cookie not compiling on Mac OS X

### ISSUE THREAD

**Issue by dstocco** [alisw/alidist#838]
Dear all,
I see that there is a receipt for cern-get-sso-cookie.
I'd like to install it on Mac OS X, but the compilation fails.
The build log is attached.

Any idea of what's wrong?
Thanks in advance,
best regards,
Diego
[build.txt](https://github.com/alisw/alidist/files/1270766/build.txt)

**Comment by ktf** [comment]
They changed the way SSO works, so in any case this requires more massaging, even if it compiles.

**Comment by dstocco** [comment]
Ciao Giulio,
ok thanks for the info!
In that case I'll try to find another way to access the ALICE webpages command-line from Mac.

Ciao,
Diego
