### ISSUE TITLE
yaml-cpp uses system boost on mac

### ISSUE THREAD

**Issue by mpuccio** [alisw/alidist#841]
Hello,

yaml-cpp installed by brew depends on boost. On the other hand in the latest recipes to build o2 boost is never taken from the system. I am not sure if this will really matters in the end, but maybe it would be better to always build yaml-cpp with the boost library built for the o2.

Cheers!
Max

**Comment by dberzano** [comment]
Thanks for reporting. I guess the better solution would be to always pick our own yaml-cpp instead of preferring the system's.

**Comment by ktf** [comment]
Most likely fixed long time ago. Closing.
