### ISSUE TITLE
FairRoot's CMake doesn't pick up ZeroMQ

### ISSUE THREAD

**Issue by teo** [alisw/alidist#846]
This happens when running `aliBuild --defaults o2-daq build FairRoot --force-unknown-architecture` on current Arch Linux. Boost is at version 1.64 and otherwise working. Same behavior with ZeroMQ versions 4.1.3 or 4.2.2.
Forcing `ZEROMQ_ROOT=/usr` in `fairroot.sh` works around this issue. It seems that FairRoot's `FindZeroMQ.cmake` doesn't look in system paths at all, unless forced to do so with `ZEROMQ_ROOT`.

**Comment by ktf** [comment]
Do you still have this problem? Can we close this? IIRC this was fixed in FairRoot.

**Comment by teo** [comment]
I'm not sure, I haven't tried in a while. I guess we can close it, I'll reopen if I encounter it again.
