### ISSUE TITLE
Move to latest FairRoot #e6042fb30ae

### ISSUE THREAD

**Issue by sawenzel** [alisw/alidist#871]
We need to upgrade FairRoot to the latest commit e6042fb30ae.

**Comment by sawenzel** [comment]
@dberzano , @ktf: Can this please be done asap, since 
a) the new version contains import new features
b) we need to regain a completely green PR state in O2

**Comment by sawenzel** [comment]
An preliminary updated version of the recipe has been merged.

**Comment by dberzano** [comment]
Yes the PR #610 does not respect at all the convention. If the hashed version works for you, let me fix it in an appropriate way. Can you confirm it does the job?

**Comment by sawenzel** [comment]
We are still waiting for confirmation from here https://github.com/AliceO2Group/AliceO2/pull/606

**Comment by sawenzel** [comment]
It does the job. Confirmed.

**Comment by dberzano** [comment]
Many thanks!
