### ISSUE TITLE
Make autotools a system requirement in mac os

### ISSUE THREAD

**Issue by matthiasrichter** [alisw/alidist#895]
autotools build by aliBuild creates a conflicting `libtool` version on mac os. This makes compilation of ROOT fail, because the `libtool` version with different options is picked up from the `alisw` installation instead of the system.

```
Linking CXX static library ../libLLVMSupport.a
Usage: /Users/richterm/src/alisw/sw/osx_x86-64/autotools/v1.5.0-2/bin/libtool [OPTION]... [MODE-ARG]...
Try 'libtool --help' for more information.
libtool:   error: unrecognised option: '-static'
make[2]: *** [interpreter/llvm/src/lib/libLLVMSupport.a] Error 1
```
 As a consequence, `autotools` needs to be a strict system requirement.

**Comment by ktf** [comment]
Yes, agreed. Either that or we make sure we can compile with any of the two.

**Comment by matthiasrichter** [comment]
This doesn't seem to be a problem any more, can not reproduce with latest alibuild/alidist, closing ...
