### ISSUE TITLE
Boost FairRoot version

### ISSUE THREAD

**Issue by sawenzel** [alisw/alidist#912]
Move the FairRoot version to at least the following hash:

c5f74833aff05a0fbc9426accbb817db42338cad

This should (hopefully) fix the problems with failing tests in our AliceO2 CI.

**Comment by sawenzel** [comment]
@dberzano : Can you please look into this? 

(As a side note, I think we should think about an easier way to bump these versions ... one that takes less work and is more agile; something like a branch name "stable" on our fork where a bigger group of people can push to)

**Comment by dberzano** [comment]
I will probably have no time to look at this today (I am home on sick leave and preparing the lessons for next week's tutorial), so I'll coordinate with @brinick (assigned).

@brinick: let me know on Slack if you can do this and if you have any doubts!

**Comment by brinick** [comment]
Done in #913 
Closing
