### ISSUE TITLE
Use different defaults on user's laptop and centralized builds

### ISSUE THREAD

**Issue by dberzano** [alisw/alidist#921]
Since aliBuild 1.5.0 we have the ability to share builds done with different defaults (as the `defaults-whatever` package is no longer added as a dependency).

This opens the ability to disable, by default, many packages normally unused on user laptops (short for "personal installations") resulting in an installation speedup, 

The proposal is to:

* Move current `defaults-release.sh` to `defaults-prod.sh` and use it on centralized builds (our build servers) by explicitly building with `--defaults prod`
* Use `defaults-release.sh` for laptop installations and disable `DPMJET`, `GEANT3`, `GEANT4`, and `GEANT4_VMC`

Among other things, this would also allow us to do things such as disabling our custom and very outdated `OpenSSL` on user laptops (unfortunately we need to keep it) and always get it from the system.

This issue is meant to discuss that. What do you think?

cc: @brinick @ktf @rbertens

**Comment by ktf** [comment]
adding also @sawenzel . While things like DPMJET can be removed and for sure OpenSSL we can pick from the system in most cases, I am not sure we should go as far as removing Geant3 / Geant4 by default. That said, why not starting by drafting a "defaults-user` which is optimised for the laptop case and advertise that as the "preferred default for laptops"?

**Comment by ktf** [comment]
We could also use ROOT6, rather than ROOT5 and try to make sure that the same default can be used for AliPhysics and O2.

**Comment by rbertens** [comment]
Hi @dberzano ,  I support this proposal as by also providing a --defaults prod, users do not lose any functionality, we just have to make them aware of this. It would be good to do a very quick investigation to see how many use cases there are for DPMJET (likely a very small number) 

@ktf  I _think_ the same holds for Geant3/Geant4, where the use case for personal builds is probably limited to some small scale testing which is usually not carried out by beginners (and Geant* takes up a lot of disk space) 

For root6 one has to keep the daily use of interpreted and not CLING ready macros in mind - changing  that default would need some proper instructions to users of which changes they need to make to their macros

**Comment by dberzano** [comment]
@ktf what we've observed during our tutorial week is that users forget to type options. So if they run `aliBuild build AliPhysics --defaults user`, next time they'll forget. I would use a sensible default working with no options passed.

@rbertens is right when saying that nobody runs GEANT* code on laptops, except a bunch of experts that can be easily instructed to build otherwise (`--defaults prod`). Say, the number of users to notify is reduced with my proposal. GEANT code is run exclusively with central MC productions. Again, it's really a few people testing it locally.

Besides: users will just ignore any notification as they always do (send attachments with cernbox, read doc first, this doc is outdated, please update, etc.), but they will trigger as soon as they realize GEANT is not there - I know that "breaking" the user space is not really a good notification method, but we're actually "fixing" the user space for the majority (DPMJET requiring pwd, GEANT4 failing on slow connections, disk space use exploding because of GEANT4 data), and adding a simple `--defaults prod` will immediately fix the new problem for the rest.

@ktf @rbertens I would be in favor of pushing as much as possible for ROOT 6 on laptops (not only Macs). This has to be discussed though and I would keep it separate for the moment (this would really break the user space if not advertised in due time). If users run their analysis with trains, a test will be run first with the production system in any case.

**Comment by ktf** [comment]
@dberzano agreed about options. I was just suggesting to do it in steps, introduce a `--defaults user` and only when you are happy with it and with good advertising you change release from "prod" to "user".

@rbertens my impression is that no one ever complained about GEANT3 / GEANT4 being there, so I am not sure that's particularly high priority especially because those who do use GEANT4 will complain (and while they might be experts, they are also extremely productive users we do not want to slow down).

**Comment by ktf** [comment]
Can we close this?

**Comment by dberzano** [comment]
Yes, it has indeed been addressed.
