### ISSUE TITLE
New AliGenerators release

### ISSUE THREAD

**Issue by qgp** [alisw/alidist#947]

**Comment by qgp** [comment]
Hi @dberzano, @ktf,

we would need a new release of AliGenerators in order to get Pythia 8.230 (already in alidist) and Therminator2 (pending PR #946) deployed. Could you please tag and deploy AliGenerators as soon as the pending PR for Therminator2 is merged?

Cheers,
    Jochen

FYI: @rbertens, @maciekniewielki

**Comment by rbertens** [comment]
Hi all,
Has the new tag of AliGenerators already been deployed? I don't see it, but maybe I overlook it. 
Thanks,
Redmer

**Comment by dberzano** [comment]
Doing it now.

**Comment by dberzano** [comment]
For the record I had to do alisw/alidist#964 in order to build it (nothing of your concern, just a minor problem with curl+OpenSSL on our ancient build platform).

**Comment by rbertens** [comment]
Thanks @dberzano !

**Comment by dberzano** [comment]
`VO_ALICE@AliGenerators::v20171212-1` is on the Grid, closing!
