### ISSUE TITLE
configuration fails to detect system protobuf

### ISSUE THREAD

**Issue by davidrohr** [alisw/alidist#950]
The configuration.sh script assumes ${PROTOBUF_ROOT} to be set.
If one uses system protobuf, it tries to access headers in /include/protobuf and libraries in /lib/..., but not in /usr/....
This is the same problem that was there with O2 and with FAIRROOT before, which has been fixed for the o2 and FAIRROOT recipes in the meantime, but appeared again in a recent update of configuration.

**Comment by awegrzyn** [comment]
@PascalBoeschoten can you take a look?
In addition, I think there's a missing line in the `osx*)` section:
```
[[ ! $PROTOBUF_ROOT ]] && PROTOBUF_ROOT=`brew --prefix protobuf`
```

**Comment by PascalBoeschoten** [comment]
Hi, I made a PR #967

**Comment by ktf** [comment]
Closing this in favour of the PR.
