### ISSUE TITLE
On macOS: issue with BOOST_ROOT in Common-O2, Configuration and Monitoring recipes

### ISSUE THREAD

**Issue by aphecetche** [alisw/alidist#951]
Had a problem today with the Common-O2 package on my Mac.

[log.txt](https://github.com/alisw/alidist/files/1534789/log.txt)

The issue is that on Mac the recipe "forces" the BOOST_ROOT variable to "brew --prefix boost".

Which is a double problem I guess. First, and directly related to the immediate problem, brew --prefix [package] returns something even if [package] is not actually installed.
  
❯ brew list boost
Error: No such keg: /usr/local/Cellar/boost

~
❯ brew --prefix boost
/usr/local/Cellar/boost/1.65.1

Second, I feel that trying to set BOOST_ROOT env variable at all is somehow misguided. The recipe specifies that boost is a dependency and that should be enough, right ?

**Comment by aphecetche** [comment]
Actually the issue is also relevant for Configuration and Monitoring packages.

**Comment by ktf** [comment]
I think this can be closed thanks to #956.
