### ISSUE TITLE
ReadoutCard build fails TCL required

### ISSUE THREAD

**Issue by KlewinS** [alisw/alidist#958]
build of ReadoutCard fails during building Common-O2@v0.3.0 because of missing TCL

[log.txt](https://github.com/alisw/alidist/files/1542814/log.txt)

**Comment by awegrzyn** [comment]
@sy-c @Barthelemy @PascalBoeschoten There is no TCL recipe in alidist

**Comment by ktf** [comment]
Can we please make sure that TCL is optional?

**Comment by Barthelemy** [comment]
@KlewinS out of curiosity, on which platform is it ? 
@ktf yes

**Comment by sy-c** [comment]
Common-O2 v1.2.1 fixes the spurious dependency.
pull request for alidist created: https://github.com/alisw/alidist/pull/963

**Comment by awegrzyn** [comment]
#963

**Comment by ktf** [comment]
This is still not working on mac.

**Comment by Barthelemy** [comment]
@ktf I have removed tcl on my mac (cmake does not find it). Before the change of Sylvain it does not compile, after the change it does compile. Could you paste the error and make sure that you cleaned common-o2 build directory before testing ?

**Comment by ktf** [comment]
@Barthelemy the error can be found, for example, here:

https://ali-ci.cern.ch/repo/logs/AliceO2Group/AliceO2/724/ccb2fbefad5074bf199901167696b35acde737ac/fullLog.txt

**Comment by ktf** [comment]
Sorry, not true. The error is actually:

```
sw/BUILD/Common-O2-latest/log
  "_Tcl_VarEval", referenced from:
      SWIG_Tcl_ConvertPtr(Tcl_Interp*, Tcl_Obj*, void**, swig_type_info*, int) in Configuration_tcl_wrap.cxx.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libtclConfiguration.dylib] Error 1
make[1]: *** [CMakeFiles/tclConfiguration.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

I do not understand why the full log is different.

**Comment by ktf** [comment]
We should be cleaning the Common-O2 are as well, because it should be treated as an external.

**Comment by Barthelemy** [comment]
@ktf, ok let me have a look on mac again
@awegrzyn could you also check on your mac if it does that ?

**Comment by Barthelemy** [comment]
@ktf actually the problem you see appears only if you have tcl installed thus my confusion (I removed it on purpose to test the issue). I can reproduce it now. 
@awegrzyn you were right we need an extra bucket internally to the Common-O2.

**Comment by Barthelemy** [comment]
@sy-c The branch fix_for_tcl_mac contains a fix, could you check on your system ?

**Comment by awegrzyn** [comment]
@Barthelemy In the meantime I've verified on my macOS and CC7 and it compiles

**Comment by matthiasrichter** [comment]
I was just building the software stack with defaults-o2, build failed in Common because the TCL include path is not set correctly.

**Comment by KlewinS** [comment]
@Barthelemy sorry for the late reply, the system I tested it, should be CC7

**Comment by Barthelemy** [comment]
@KlewinS it should be ok now

**Comment by KlewinS** [comment]
thanks, now this problem seems to be solved, but another appeared:

> /home/tpc/alice/sw/SOURCES/Common-O2/v1.2.2/v1.2.2/test/testDataFormat.c:31:5: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
>      for (int j=0;j<payloadSize;j++) {
>      ^
> /home/tpc/alice/sw/SOURCES/Common-O2/v1.2.2/v1.2.2/test/testDataFormat.c:31:5: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
> /home/tpc/alice/sw/SOURCES/Common-O2/v1.2.2/v1.2.2/test/testDataFormat.c:51:5: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
>      for (int j=0;j<subBlockPtr->dataSize;j++) {
>      ^
> CMakeFiles/testDataFormat.dir/build.make:62: recipe for target 'CMakeFiles/testDataFormat.dir/test/testDataFormat.c.o' failed

**Comment by KlewinS** [comment]
thx, seems to work now
