### ISSUE TITLE
RapidJSON fails with gcc 7 toolchain

### ISSUE THREAD

**Issue by davidrohr** [alisw/alidist#977]
RapidJSON needs -Wno-error=implicit-fallthrough in CMAKE CXX flags (or a proper fix in the source) in order to run with current GCC

**Comment by ktf** [comment]
@PascalBoeschoten can you please look into this?

**Comment by PascalBoeschoten** [comment]
@davidrohr @ktf made PR: #980

**Comment by awegrzyn** [comment]
The same happens with `grpc`:
```
src/core/lib/support/murmur_hash.c:79:10: error: this statement may fall through [-Werror=implicit-fallthrough=]
src/core/lib/support/murmur_hash.c:81:10: error: this statement may fall through [-Werror=implicit-fallthrough=]
```
What about not treating this warning as error in dependencies that we don't maintain?

**Comment by ktf** [comment]
That would need to be done on a recipe by recipe basis, though. `-Werror=implicit-fallthrough=` is not set by us, but it's a new GCC default. In the end it might actually be easier to move to a newer version of the external which actually fixes the problem.

**Comment by PascalBoeschoten** [comment]
I would agree that in general we should move to newer versions, but sometimes this is non-trivial and a lot harder than adding a compiler flag. At least in the case of 3rd party libraries, I don't think this new GCC warning gives us any benefits.

**Comment by ktf** [comment]
Agreed, but blindly adding a compiler flag everywhere is not something we should do, for the sake of simplicity and maintainability. So if the fastest route is to simply hack one recipe while we prepare for the next version, fine with me, but do not expect global support for this as that is a shortcut, not a proper solution.

In this particular case I am actually surprised that you say that moving to a newer version is complicated, though. Why is that?

**Comment by PascalBoeschoten** [comment]
That was not referring to a particular case, just a general comment.

**Comment by dberzano** [comment]
OK so let's try to bump RapidJSON to see if it fixes the problem upstream.

**Comment by ktf** [comment]
@PascalBoeschoten Ok, agreed then. 

Notice however that the most common case where updating might not be OK is actually ROOT and in that case we do want to see all the possible errors and warnings that a new compiler gives us, because chances are they are genuine issues which we do not want to mask (at least that's my personal experience).

**Comment by ktf** [comment]
closing this as I guess it's not relevant anymore.
