### ISSUE TITLE
New repository rivet-hi

### ISSUE THREAD

**Issue by qgp** [alisw/alidist#986]
Hi,

could you please create a new repository rivet-hi with the privileges for me as for other PWG-MM packages?

We need this to develop and deploy a forked version of Rivet with additional HI support.

Cheers,
   Jochen

**Comment by qgp** [comment]
ping @ktf @dberzano 

FYI: @jgrosseo, @pkarczma

**Comment by ktf** [comment]
I missed your initial message, sorry.

https://github.com/alisw/rivet-hi

is now there. Please remember to follow the policy at:

https://github.com/alisw/alidist/#guidelines-for-handling-externals-sources

as usual and make sure you add it to the pwgmm owned externals in the documentation.
